### ISSUE TITLE
Inheritable @ViewFilters

### ISSUE THREAD

**Issue by aboodz** [Blazebit/blaze-persistence#1034]
### Description
I am not sure if this bug. I was trying to extend from entityViews where each defines a `@ViewFilter`. The code should be similar to what follows:

```
@ViewFilter(name = "prop1", value = Prop1FilterProvider.class)
public interface HasProp1 {
// code
}

@ViewFilter(name = "prop2", value = Prop2FilterProvider.class)
public interface HasProp2 {
// code
}

@EntityView(Entity.class)
public interface EntityView extends HasProp1, HasProp2 {
// code
}
```

### Expected behavior
Both `prop1` and `prop2` ViewFilter should be defined on EntityView.

### Actual behavior
I noticed it only inherits the `prop1` ViewFilter; `prop2` is undefined.

### Workaround
Define both filters on the EntityView directly 
```
@ViewFilters(value = {
        @ViewFilter(name = "prop1", value = Prop1FilterProvider.class),
        @ViewFilter(name = "prop2", value = Prop2FilterProvider.class)
})
@EntityView(Entity.class)
public interface EntityView extends HasProp1, HasProp2 {
// code
}
```
### Environment
Version:  1.4.0
JPA-Provider: Hibernate 5.0.4.Final
DBMS: PostgreSQL
Application Server: Netty 2.1.3.RELEASE

**Comment by beikov** [comment]
That's a bug indeed. We will take care of that in the 1.5.0 release. Thanks for the report :)
