### ISSUE TITLE
Question: headers link and keyset pagination 

### ISSUE THREAD

**Issue by ask4gilles** [Blazebit/blaze-persistence#1080]
Hi,
I need to return a page content and provide navigation links in the httpheaders.

Do you have any examples on how to provide headers Link pagination using keysets?

I’m currently using blaze persistence together with spring mvc/data.
I’m able to build headers link using the https://docs.spring.io/spring-data/data-commons/docs/current/api/org/springframework/data/web/PagedResourcesAssembler.html 
But from what I see, this only works for offset pagination?

Thanks!

**Comment by ask4gilles** [comment]
Sorry, I didn’t see https://github.com/Blazebit/blaze-persistence/issues/917
Would you have a concrete example?

**Comment by beikov** [comment]
Hey there. Maybe this example can help you: https://github.com/Blazebit/blaze-persistence/tree/master/examples/spring-data-webmvc

**Comment by ask4gilles** [comment]
Yeah, that’s the one I followed. But here you return the page itself and the links are in the body. I’m trying to return a ResponseEntity containing a list (the page content) and add links in the headers, does it make sense?

**Comment by beikov** [comment]
Yeah makes sense. I know what you want but wasn't able to create an out of the box integration for that yet. Basically, you have to serialize the KeysetPage as e.g. JSON or opaque string like in the GraphQL integration so that you can parse it back in your endpoint. I'd suggest you make it opaque the you can use the serializer and deserializer of the GraphQL integration

**Comment by beikov** [comment]
Here is some deserialization code: https://github.com/Blazebit/blaze-persistence/blob/master/integration/graphql/src/main/java/com/blazebit/persistence/integration/graphql/GraphQLEntityViewSupport.java#L365

**Comment by ask4gilles** [comment]
Alright, thanks, I’ll dive into this 🙂

**Comment by beikov** [comment]
I was unsure if anyone really uses Spring HATEOAS but since you are asking for it now, I'll work on integrating it into the final 1.5.0 release ;)

**Comment by beikov** [comment]
What kind of integration would you expect @ask4gilles ?

With a KeysetAwarePage, which you can declare as return type in your repository method, you can construct the JSON structure that is expected for a `@KeysetConfig` parameters and finally also construct the prev and next links to use keyset pagination. I could provide a utility to create this JSON string, but I think that's about all an integration could do. Do you have any ideas how we could integrate here? Maybe you know a bit more than me about Spring HATEOAS, I have never used it before, but I don't know if or how I can get the URL for _the current resource_ and replace a query parameter in that URL. If such a thing is possible, we could try to do that in the integration.

Let's maybe move this discussion to https://github.com/Blazebit/blaze-persistence/issues/917
