### ISSUE TITLE
Illegal reflective access by javassist warning

### ISSUE THREAD

**Issue by ask4gilles** [Blazebit/blaze-persistence#1086]
Hi,

It's more a question than an issue, but here are the details:

### Description
After a search invoking interface annotated with @EntityView, we get the warning message below.

### Expected behavior
No warning message

### Actual behavior
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by javassist.util.proxy.SecurityActions (file:XXXXXXXXXXX/org.javassist/javassist/3.25.0-GA/442dc1f9fd520130bd18da938622f4f9b2e5fba3/javassist-3.25.0-GA.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of javassist.util.proxy.SecurityActions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

### Steps to reproduce
Perform a search using interface annotated with @EntityView

### Environment

Version:            1.4.1
JPA-Provider:       Hibernate 5.4.12
DBMS:               PostgreSQL 9.5
Application Server:  Tomcat

**Comment by beikov** [comment]
Entity view implementations i.e. the Java classes that hold the state, are generated at runtime. You can configure that these classes should be generated during boot but at some point they must be generated. See https://persistence.blazebit.com/documentation/1.5/entity-view/manual/en_US/#proxy_eager_loading

As of version 1.5.0-Alpha2 which will be released this evening or tomorrow morning, you will be able to use an annotation processor to generate the entity view implementations already at compile time if you like which allows to avoid this warning.
