### ISSUE TITLE
Invalid merging of RowSelection in HibernateExtendedQuerySupport

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#1114]
This leads to wrong query results and to the following Hibernate warning being issued in cases where this is not necessary:
```
HHH000104: firstResult/maxResults specified with collection fetch; applying in memory!
```

**Comment by jwgmeligmeyling** [comment]
I've been looking for years to trace the source of this warning down (in my application) 😅

**Comment by Mobe91** [comment]
Well, there are cases where this warning is legitimate 😄
