### ISSUE TITLE
NPE when invoking EnitityViewManager.find() with Entity.class

### ISSUE THREAD

**Issue by sullrich84** [Blazebit/blaze-persistence#1126]
### Proposal for Improvement

When accidentally invoking `EnitityViewManager.find()` with `Entity.class` instead of `EntityView,class` BP will throw a `NPE` at 

https://github.com/Blazebit/blaze-persistence/blob/2167bc6775d42636dc2bdff12e28773258f91415/entity-view/impl/src/main/java/com/blazebit/persistence/view/impl/EntityViewManagerImpl.java#L769

Maybe adding a more meaningful error message would be helpful here?

**Comment by beikov** [comment]
Thanks for the feedback. I'll add a proper exception.
