### ISSUE TITLE
Incorrect rel=next link parameter in Spring HATEOAS links

### ISSUE THREAD

**Issue by kekbur** [Blazebit/blaze-persistence#1128]
### Description
The Spring HATEOAS example project generates incorrect `rel="next"` header URL parameters. When the sort query parameters are `age,asc` and `id,desc` the generated `rel="next"` link has the parameter `highest` with an incorrect value where the values for `age` and `id` are transposed.

### Expected behavior
`Link: <http://localhost:8080/cats?page=1&size=20&sort=age,asc&sort=id,desc&prevPage=0&highest={"age":4,"id":50}>;rel="next"`
...
`{"id":50,"name":"Cat 45","age":4,"owner":{"id":3,"name":"Person 2"},"mother":null,"father":null}`

### Actual behavior
`Link: <http://localhost:8080/cats?page=1&size=20&sort=age,asc&sort=id,desc&prevPage=0&highest={"age":50,"id":4}>;rel="next"`
...
``{"id":50,"name":"Cat 45","age":4,"owner":{"id":3,"name":"Person 2"},"mother":null,"father":null}``

### Steps to reproduce

1. `wget "https://repo1.maven.org/maven2/com/blazebit/blaze-persistence-examples-spring-hateoas/1.5.0-Alpha5/blaze-persistence-examples-spring-hateoas-1.5.0-Alpha5.jar"`
2. `java -jar 1.5.0-Alpha5/blaze-persistence-examples-spring-hateoas-1.5.0-Alpha5.jar`
3. `curl -s -D - "http://localhost:8080/cats?sort=age,asc&sort=id,desc"`
4. Observe the value of the `rel="next"` Link header.

### Environment

Version:            1.5.0-Alpha5
JPA-Provider:       
DBMS:               
Application Server:

**Comment by beikov** [comment]
Thanks for the report! I'll try to get that fixed in the next release. By any chance, have you checked in the debugger where this is wrong?

**Comment by kekbur** [comment]
I did look into it with a debugger, but quickly got lost in the code jungle. What I can tell is that the JSON object in question is created by `KeysetAwarePagedResourcesAssembler#serialize(Sort sort, Keyset keyset)`. The method calls `Keyset#getTuple` and expects it to return the keyset tuple as documented: "Returns the key set tuple ordered by the respective order by expressions.". But the returned array is in the wrong order. I hope this information is helpful.

Somewhat related to this issue: I'm trying to figure out if blaze-persistence would be suitable for my project that will use spring-data and provide a REST API with keyset pagination. `KeysetPageable` seems to be very close to what I'm looking for, but it has a bit too many features. It generates an SQL queries that count the total number of matching results, which I would prefer not to do for performance reasons. I also don't want to use any page numbers or numeric offsets anywhere.

The following code snippets illustrate what I'm trying to do.

---

**For the first page:**

```java
int maxResults = 5;
Keyset cursor = null;
KeysetPage keysetPage = new DefaultKeysetPage(/* I don't want to use this parameter */, maxResults, cursor, /* I don't want to use this parameter */);
Sort sort = Sort.by(Direction.ASC, "age")
    .and(Sort.by(Direction.DESC, "id"));
KeysetPageable keysetPageable = new KeysetPageRequest(keysetPage, sort);

List<Cat> page = catRepository.findAll(specification, keysetPageable);
```

Desired SQL:

```sql
[...] order by cat0_.age ASC nulls last, cat0_.id DESC limit 3
```

**Subsequent pages:**

```java
int maxResults = 5;
Keyset cursor = new DefaultKeyset(new Serializable[] { 0, 68L }); // assuming the last cat of the previous page had age=0 and id=68
KeysetPage keysetPage = new DefaultKeysetPage(/* I don't want to use this parameter */, maxResults, cursor, /* I don't want to use this parameter */);
Sort sort = Sort.by(Direction.ASC, "age")
    .and(Sort.by(Direction.DESC, "id"));
KeysetPageable keysetPageable = new KeysetPageRequest(keysetPage, sort);

List<Cat> page = catRepository.findAll(specification, keysetPageable);
```

Desired SQL:

```sql
[...] where cat0_.age>0 or cat0_.age is null or cat0_.age=0 and cat0_.id<68 order by cat0_.age ASC nulls last, cat0_.id DESC limit 3
```

Pagination information would be contained in query parameters as follows:

First page: `/cats`
Subsequent pages: `/cats?cursor={"age":0,"id":68}`

---

Do you think blaze-persistence is suitable for this use case?

**Comment by beikov** [comment]
>But the returned array is in the wrong order. I hope this information is helpful.

Thanks, that's very helpful.

> Do you think blaze-persistence is suitable for this use case?

Yeah, you can turn these parts off if you like. See `com.blazebit.persistence.PaginatedCriteriaBuilder#withCountQuery` which can be configured via `com.blazebit.persistence.spring.data.repository.KeysetPageRequest#KeysetPageRequest(com.blazebit.persistence.KeysetPage, org.springframework.data.domain.Sort, int, int, boolean, boolean)`.

If you want to work with just a cursor, then you will need to do some HTTP parameter parsing manually, but I think it shouldn't be too hard. Maybe GraphQL with the Relay specification implementation will be more appropriate for you? See here: https://github.com/Blazebit/blaze-persistence/tree/master/examples/spring-data-graphql

**Comment by kekbur** [comment]
Thanks for the pointers. I had to abuse the keyset API a bit, but this works exactly the way I want:

```java
@RequestMapping(path = "/cats2", method = RequestMethod.GET)
public Map<String, Object> findPaginated2(
	@RequestParam(name = "before", required = false) String before,
	@RequestParam(name = "after", required = false) String after,
	@RequestParam(name = "filter", required = false) final Filter[] filter)
{
	Specification<Cat> specification = getSpecificationForFilter(filter);

	int perPage = 10;
	int offset = before == null && after == null ? 0 : perPage;
	
	Sort sort = Sort.by(Direction.ASC, "age")
		.and(Sort.by(Direction.DESC, "id"));
	
	Keyset lowest = null;
	
	if (before != null)
	{
		lowest = new DefaultKeyset(cursorToKeyset(before));
	}
	
	Keyset highest = null;
	
	if (after != null)
	{
		highest = new DefaultKeyset(cursorToKeyset(after));
	}
	
	if (before != null && after != null)
	{
		throw new IllegalArgumentException("before and after are both non-null");
	}
	
	List<Keyset> keysets = Stream.of(lowest, highest)
		.filter(Objects::nonNull)
		.collect(toList());
	
	KeysetPage keysetPage = new DefaultKeysetPage(before == null ? 0 : perPage * 2, perPage, lowest, highest, keysets);
	KeysetPageable keysetPageable = new KeysetPageRequest(keysetPage, sort, offset, perPage, false, false);
	
	KeysetAwarePage<Cat> page = catRepository.findAll(specification, keysetPageable);
	Map<String, Object> map = new LinkedHashMap<>();
	
	if (offset != 0 && page.getKeysetPage() != null && page.getKeysetPage().getLowest() != null && page.getNumberOfElements() >= perPage)
	{
		UriComponents previous = ServletUriComponentsBuilder.fromCurrentRequest()
			.replaceQueryParam("before", keysetToCursor(page.getKeysetPage().getLowest().getTuple()))
			.replaceQueryParam("after")
			.build()
			.encode();
		map.put("previous", previous.toString());
	}
	
	if (page.getKeysetPage() != null && page.getKeysetPage().getHighest() != null && page.getNumberOfElements() >= perPage)
	{
		UriComponents next = ServletUriComponentsBuilder.fromCurrentRequest()
			.replaceQueryParam("after", keysetToCursor(page.getKeysetPage().getHighest().getTuple()))
			.replaceQueryParam("before")
			.build()
			.encode();
		map.put("next", next.toString());
	}
	
	map.put("content", page.getContent());
	
	return map;
}
```

With a bit of code restructuring this is the end result:

```java
@RequestMapping(path = "/cats3", method = RequestMethod.GET)
public CursorLinkedResponse<Cat> findPaginated3(
	@CursorConfig(maxResults = 10, sort = { @Order(property = "age", direction = Direction.ASC), @Order(property = "id", direction = Direction.DESC) })
	Cursor cursor,
	@RequestParam(name = "filter", required = false) final Filter[] filter)
{
	Specification<Cat> specification = getSpecificationForFilter(filter);

	KeysetAwarePage<Cat> page = catRepository.findAll(specification, cursor);
	
	return new CursorLinkedResponse<>(page);
}
```

**Comment by beikov** [comment]
Looks interesting. Do you think it might be worth adding support for this somehow in Blaze-Persistence? I'd gladly accept a PR for this :)

**Comment by kekbur** [comment]
> Do you think it might be worth adding support for this somehow in Blaze-Persistence?

I don't know, maybe. What I'm envisioning this kind of approach is useful for is an event timeline where the initial view shows items for the current date and there are arbitrarily many items before and after that date.

* The user can view past/future items by moving backwards/forwards using a keyset cursor.
* Page numbers don't make sense here.
* There can be arbitrary gaps between the dates of items, and that's ok.
* The keyset would be (event_date, event_id). Queries can efficiently retrieve the desired items using an index.

I've uploaded my work so far here: https://github.com/kekbur/cursor-pagination-demo. Maybe it can be useful to somebody.

Actually, I'm kind of gravitating towards using Quarkus instead of Spring Boot. Is blaze-persistence integration with it still a work in progress? I ran into a couple of problems which can describe in separate issues.

**Comment by beikov** [comment]
Interesting, thanks for sharing. Like I wrote, it would be awesome if you find the time to maybe integrate that directly into Blaze-Persistence. You seem to know your Spring-Fu ;)

We have a Quarkus integration even with support for native compilation: https://persistence.blazebit.com/documentation/1.5/entity-view/manual/en_US/#quarkus-integration

**Comment by beikov** [comment]
I debugged the issue and found this is the root issue as documented in #1144
The fix will be part of the next release
