### ISSUE TITLE
entity-view-processor generates syntactically invalid code for primitive arrays

### ISSUE THREAD

**Issue by kekbur** [Blazebit/blaze-persistence#1134]
### Description
entity-view-processor generates syntactically invalid code when an entity contains a field of a primitive array type such as `byte[]` and an entity view contains a getter for such a field.

Entity class:

```java
@Entity
public class Person implements Serializable
{
	private byte[] bytes;
```

Entity view:

```java
@EntityView(Person.class)
public interface PersonView
{
	byte[] getBytes();
```

### Expected behavior
Syntactically valid code is generated.

### Actual behavior
Syntactically invalid code is generated as shown below:

```java
@Generated(value = "com.blazebit.persistence.view.processor.EntityViewAnnotationProcessor")
@StaticImplementation(PersonView.class)
public class PersonViewImpl implements PersonView, EntityViewProxy {

    public static volatile EntityViewManager ENTITY_VIEW_MANAGER;
    public static final SerializableEntityViewManager SERIALIZABLE_ENTITY_VIEW_MANAGER = new SerializableEntityViewManager(PersonViewImpl.class, ENTITY_VIEW_MANAGER);

    private final byte[[] bytes;
```
Note the superfluous `[` in `byte[[]`.

### Steps to reproduce
1. `git clone -b byte-array-issue https://github.com/kekbur/blaze-persistence-quarkus-native-image-test.git && cd blaze-persistence-quarkus-native-image-test`
2. `./mvnw -Pnative clean compile`

### Environment

Version:            1.5.0-Alpha5

**Comment by beikov** [comment]
Thanks for the report, I read a bit into the code but I don't see how this could happen. Maybe the annotation processing types return something unexpected which leads to this.
