### ISSUE TITLE
getCountQuery doesn't respect distinct flag

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1151]
It seems our `getCountQuery` implementation doesn't respect the `distinct` flag i.e. it should construct a `count(distinct ...)` for the select list in that case. Also, it can't work when group by and `distinct` are combined.

**Comment by jwgmeligmeyling** [comment]
QueryDSL has a `fetchCount()` method as well. We've struggled with count queries with a `HAVING` clause as well (in particular having clauses that can't be expressed as a where clause, i.e. having clauses with an aggregate function in it). I suppose these are troublesome for Blaze-Persist then as well?

**Comment by beikov** [comment]
You mean that QueryDSL had issues with `fetchCount` with queries that uses group by and having predicates that contain aggregate functions? Would be interesting to know what was problematic so I can add tests for that.

**Comment by beikov** [comment]
As @jwgmeligmeyling mentioned, something like the following `SELECT a.key, sum(a.value) FROM Entity a HAVING sum(a.value) > 0` will need query wrapping. We will implement a count query for such queries and distinct queries like `SELECT (select count(*) from (...) x) from ValuesEntity e`

**Comment by jwgmeligmeyling** [comment]
I've just done a couple of tests in `CountQueryTest` against the current `master`, and they all worked flawlessly.

The scenario's I've tested:

- Having clause that cannot be expressed as a where clause, and thus requires a subquery
- Group by clause that is entropy increasing
- Count distinct on multiple columns

My scenario's were as follows, if you're interested in any of them let me know, then I'll provide them as patch. 👍  I wasn't sure for which of these scenarios tests already exist.

```java
@Test
public void testCountWithHavingClauseThatCannotBeExpressedAsWhereClause() {
    CriteriaBuilder<Tuple> crit = cbf.create(em, Tuple.class)
            .from(Person.class, "owner")
            .leftJoin("owner.ownedDocuments", "d")
            .select("owner.id")
            .select("count(d.id)")
            .groupBy("owner.id")
            .having("count(d.id)").gtExpression("3");

    final Long expected = (long) crit.getResultList().size();
    final Long actual = crit.getCountQuery().getSingleResult();
    assertEquals(expected, actual);
}

@Test
public void testCountWithGroupByClauseThatCannotBeRemoved() {
    CriteriaBuilder<Tuple> crit = cbf.create(em, Tuple.class)
            .from(Person.class, "owner")
            .leftJoin("owner.ownedDocuments", "d")
            .select("count(d.id)")
            .groupBy("CASE WHEN d.id < 2 THEN TRUE ELSE FALSE END");

    final Long expected = (long) crit.getResultList().size();
    final Long actual = crit.getCountQuery().getSingleResult();
    assertEquals(expected, actual);
}


@Test
public void testCountDistinctWithGroupByClauseThatCannotBeRemoved() {
    CriteriaBuilder<Tuple> crit = cbf.create(em, Tuple.class)
            .from(Person.class, "owner")
            .leftJoin("owner.ownedDocuments", "d")
            .distinct()
            .select("owner.id")
            .select("min(d.id)");

    final Long expected = (long) crit.getResultList().size();
    final Long actual = crit.getCountQuery().getSingleResult();
    assertEquals(expected, actual);
}
```

**Comment by beikov** [comment]
Thanks for testing! I think these cases are covered by the following testsuite methods:

* `testCountWithHavingClauseThatCannotBeExpressedAsWhereClause` is covered by `com.blazebit.persistence.testsuite.CountQueryTest#countQueryFromHavingQuery`
* `testCountWithGroupByClauseThatCannotBeRemoved` is covered by `com.blazebit.persistence.testsuite.CountQueryTest#countQueryWithGroupBy`
* `testCountDistinctWithGroupByClauseThatCannotBeRemoved` is covered by `com.blazebit.persistence.testsuite.CountQueryTest#countQueryWithDistinct`
