### ISSUE TITLE
Generated group by clauses fail for some subquery uses

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1156]
In PostgreSQL the following SQL query that we generate fails:

```
select 
    case when exists (select 1 from tbl_b b where b.a = a.id) then 'A' else 'B' end,
    count(*)
from tbl_a a
group by
    case when exists (select 1 from tbl_b b where b.a = a.id) then 'A' else 'B' end
```

saying that one has to group by `a.id` although it already groups by the whole case when statement that contains the column. We already have code in place that can decompose correlated expressions, but up until now this always worked for PostgreSQL. We will have to investigate what goes wrong here.

**Comment by jwgmeligmeyling** [comment]
It appears that PostgreSQL's detection for expression equivalency doesn't work on subqueries... In Hibernate 5.4 you could work around this using group by alias (for dialects that support it), but for other ORM's I am not sure how this could be done. Maybe add another wrapping subquery? 

i.e.
```
select a, count(*) from (
select 
    case when exists (select 1 from tbl_b b where b.a = a.id) then 'A' else 'B' end as a,
    *
from tbl_a a
)
group by
    case when exists (select 1 from tbl_b b where b.a = a.id) then 'A' else 'B' end
```

**Comment by beikov** [comment]
Hmm, there must be a bug somewhere as we seem to handle this already... https://github.com/Blazebit/blaze-persistence/blob/master/core/impl/src/main/java/com/blazebit/persistence/impl/GroupByExpressionGatheringVisitor.java#L232

**Comment by beikov** [comment]
Indeed, we messed up here... https://github.com/Blazebit/blaze-persistence/blob/master/core/parser/src/main/java/com/blazebit/persistence/parser/expression/AbortableVisitorAdapter.java#L353
