### ISSUE TITLE
Version read from Manifest prevent shadowing, hence fat/uber JAR won't start. [Micronaut]

### ISSUE THREAD

**Issue by soberich** [Blazebit/blaze-persistence#1157]
### Description

Version read from Manifest causes `NumberFormatException` on string `[WORKING]` shadowing, for sure in case when compile and runtime dependency of Hibernate differs. When version is the same it somehow passes, yet I am no sure why, how.
Exception happens at:

https://github.com/Blazebit/blaze-persistence/blob/master/integration/hibernate-base/src/main/java/com/blazebit/persistence/integration/hibernate/base/function/AbstractHibernateEntityManagerFactoryIntegrator.java#L79
### Expected behavior

Some fallback to non string input, maybe to `0.0.0` to avoid this scenario.
### Actual behavior
![image](https://user-images.githubusercontent.com/25544967/92036834-20775400-ed71-11ea-949c-9a6070a7b192.png)

### Environment
Version:                 1.5.0-SNAPSHOT
JPA-Provider:       Hibernate 5.4.19.Final, 5.4.20.Final
Application Server: any

**Comment by beikov** [comment]
There is an SPI(`com.blazebit.persistence.integration.hibernate.base.spi.HibernateVersionProvider`) to provide the Hibernate version through different means. This is a known issue for uber-jars. We heavily rely on the version, so we really need it, but I understand the message could be better.

**Comment by beikov** [comment]
I'll improve the error message by pointing to the SPI.
