### ISSUE TITLE
QUESTION: PaginationView with list of EntityView

### ISSUE THREAD

**Issue by alexferreiradev** [Blazebit/blaze-persistence#1164]
I would a json from my api like that:
```JSON
{
  "total": 100,
  "models": [
{
"id": 1
}
]
}
 ```
What is the best way to do that, create a DTO or are there some way with entityViews ?

**Comment by alexferreiradev** [comment]
I got that with DTO, I tried with entityView, but did not have success. I did like this:
```JAVA
                        List<HomeAtendimentoView> atendimentoViewList = atendimentoService.listarPaginado(listCommand);
			PaginaDTO<HomeAtendimentoView> paginaDTO = new PaginaDTO<>(atendimentoViewList);
			return Response.ok().entity(paginaDTO).build();
```

**Comment by beikov** [comment]
Hi Alex,

I suppose you are using Spring Data? If so, you can take a look into the documentation about how this can be done with Spring-Data means: https://persistence.blazebit.com/documentation/1.5/entity-view/manual/en_US/#usage

If you want to implement this by hand, you can use the PaginatedCriteriaBuilder API along with entity views if you like. It could roughly look like the following:

```
@EntityView(HomeAtendimento.class)
interface HomeAtendimentoView {
  @IdMapping
  Long getId();
  // Other attributes
}

CriteriaBuilder<HomeAtendimento> cb = criteriaBuilderFactory.create(entityManager, HomeAtendimento.class);
// Your query logic on the criteria builder
PagedList<HomeAtendimentoView> list = entityViewManager.applySetting(
    EntityViewSetting.create(HomeAtendimentoView.class, offset, pageSize), 
    cb
).getResultList();

PaginaDTO<HomeAtendimentoView> paginaDTO = new PaginaDTO<>(list, list.getTotalSize());
```

Here is some more information about this: https://persistence.blazebit.com/documentation/1.5/core/manual/en_US/#pagination

**Comment by alexferreiradev** [comment]
Thanks for the answer, but I would some way without DTO, I got with entityView, but My question now is are there way to do the list and total without set like parameter, a automatically way to criteriaBuilder and entityView return the total filtered and the results models in one object, like in my PaginaView below ? 

I create a sample project to test and after apply in my original post at my work. See below:

My EntityView to represent my page of results:
```JAVA
@EntityView(Produto.class)
public interface PaginaView {

	@MappingParameter("total")
	Long getTotal();

	@MappingParameter("produtoList")
	List<ProdutoView> getProdutoList();
}
```
My repository to create my page: 
```JAVA
public PaginaView findPagina(ProdutoCommand command) {
		CriteriaBuilder<Produto> cb = cbf.create(em, Produto.class);
		EntityViewSetting<ProdutoView, PaginatedCriteriaBuilder<ProdutoView>> setting = EntityViewSetting.create(ProdutoView.class, command.getOffset(), command.getLimit());
		setting.addAttributeSorter("id", Sorters.ascending());

		Range<Date> range = Range.between(new Date(Long.parseLong(command.getDataHora())), new Date());
		setting.addAttributeFilter("dateTime", range);
		PaginatedCriteriaBuilder<ProdutoView> produtoViewCriteriaBuilder = evm.applySetting(setting, cb);

		EntityViewBuilder<PaginaView> builder = evm.createBuilder(PaginaView.class);
		builder.with("total", produtoViewCriteriaBuilder.getCountQuery().getSingleResult());
		builder.with("produtoList", produtoViewCriteriaBuilder.getResultList());

		return builder.build();
	}
```
Is the best way to create a PaginaView or are there some API way (with Blaze) to archive that goal ?

**Comment by alexferreiradev** [comment]
I did not pay attention in your answer the object Page, is what I need. Thank you again
