### ISSUE TITLE
Accessing superclass attribute in treated expression wrongly omits case when wrapper

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1174]
An expression like `TREAT(alias.publication AS Book).id` produces `alias.publication.id` whereas it should produce `CASE WHEN TYPE(alias.publication) = Book THEN alias.publication.id ELSE NULL END`. This is probably because the `id` member is defined on the super type `Publication` rather than `Book`.

**Comment by jwgmeligmeyling** [comment]
I remember running into this once. Does the new case approach handle abstract super types well BTW?

**Comment by beikov** [comment]
Not sure what you mean by "handle", but if there are multiple subtypes available it will use an IN predicate.

**Comment by jwgmeligmeyling** [comment]
Yes that's what I meant! 👍
