### ISSUE TITLE
Unable to deserialize Instant object from ISO 8601 (with jax-rs integration)

### ISSUE THREAD

**Issue by jloupdef** [Blazebit/blaze-persistence#1195]
Starting with blaze 1.5, I cannot find a way to deserialize Instant object from ISO 8601 date in Entity View.

As stated in 1.4 documentation, blaze used existing ObjectMapper to deserialize entityView and could therefore be configured (https://persistence.blazebit.com/documentation/1.4/entity-view/manual/en_US/index.html#usage-5)

Starting with 1.5, (changed in [this commit](https://github.com/Blazebit/blaze-persistence/commit/3785a964c4831aa1c432299d4e74e3ac62e37a00) ) the object mapper used is created from scratch ([see here](https://github.com/Blazebit/blaze-persistence/blob/1.5/integration/jaxrs/src/main/java/com/blazebit/persistence/integration/jaxrs/EntityViewMessageBodyReader.java#L83), and cannot seams to be accessed in any way to be configured, for example for supporting ISO 8601 dates format, which is a common use case :

```
        objectMapper.registerModule(new JavaTimeModule());
        objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
```

### Description
Have a way to configure blaze internal objectMapper to support ISO 8601 dates format for example

### Expected behavior
Post following json object and process it correctly through jax-rs in EntityView :
{"datetime": "2018-12-04T18:47:38.927Z"}

### Actual behavior
`com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `java.time.Instant` (no Creators, like default constructor, exist): no String-argument constructor/factory method to deserialize from String value ('2020-11-09T08:00:00.000Z')`

### Steps to reproduce
Submit the given json as body to a post endpoint (with jax-rs blaze integration) and building a simple entity view :
`@UpdatableEntityView
@CreatableEntityView
@EntityView(MyEntity.class)
public interface MyUpdateView {
    @IdMapping
    Long getId();

    Instant getDatetime();
    void setDatetime(Instant datetime);
}`

### Environment
Blaze 1.5 and upper

**Comment by beikov** [comment]
Hi,

this is unfortunate. Can you try creating a subtype of `com.blazebit.persistence.integration.jaxrs.EntityViewMessageBodyReader` with a higher priority i.e. `@Priority(Priorities.USER - 2)`

**Comment by jloupdef** [comment]
Creating a subtype is not really a solution as everything is private and without getter, I still need to copy nearly all the class's content. My current workaround has been to copy the full file in my project, give it a higher priority and configure the object mapper directly, but without making a subtype.

**Comment by beikov** [comment]
Ah yes, makes sense. I will fix this by injecting `Instance<ObjectMapper>` and bind that if satisfied. Would that be fine for your use case?

**Comment by jloupdef** [comment]
Yes it would by fine for me (another way is to keep a reference on created objectMapper and give access to it through a getter, this way people could customize it to their needs without interfering with their own mapper, but I don't know if there is use cases where keeping two objectMappers makes sense).
Anyway, thank you for quick responses and your work on this amazing project !

**Comment by beikov** [comment]
I'm not sure if it is thread safe to allow changes to the `ObjectMapper` later on, so I would prefer doing this during initialization and then be done.

> Anyway, thank you for quick responses and your work on this amazing project !

Thanks, glad you like it :)
