### ISSUE TITLE
When bind cte can't as alias

### ISSUE THREAD

**Issue by luyuanx2** [Blazebit/blaze-persistence#1198]
![image](https://user-images.githubusercontent.com/26129033/98655586-981dbc80-237a-11eb-9378-3c6647114cc6.png)

**Comment by beikov** [comment]
Hi @luyuanx2, thanks for the report! We will look into this. I guess you want this alias for usage in the `ORDER BY` clause? You can workaround that by using the expression directly there as well.

**Comment by luyuanx2** [comment]
I want to use group by clause

**Comment by beikov** [comment]
Group bys are created implicitly when an aggregate function is used, so you don't need add that explicitly. Apart from that, the use of a select alias in the group by will currently still expand to the actual expression, but this should be fixed by https://github.com/Blazebit/blaze-persistence/issues/1075

**Comment by luyuanx2** [comment]
when i use the expression directly，there another error occurs
![image](https://user-images.githubusercontent.com/26129033/98668575-08343e80-238b-11eb-9e94-81314590c3f3.png)

**Comment by luyuanx2** [comment]
> Group bys are created implicitly when an aggregate function is used, so you don't need add that explicitly. Apart from that, the use of a select alias in the group by will currently still expand to the actual expression, but this should be fixed by #1075

Are there other solutions?

**Comment by beikov** [comment]
The problem you are facing there is only on MySQL and a fix to handle such cases was developed as part of https://github.com/Blazebit/blaze-persistence/issues/1185 but there is no release for this yet. You can see if 1.6.0-SNAPSHOT works for you. You could also disable this faulty MySQL emulation by providing a custom `DbmsDialect` that returns `true` for `supportsGroupByExpressionInHavingMatching`: https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/#customize-dbms-dialect

**Comment by luyuanx2** [comment]
> The problem you are facing there is only on MySQL and a fix to handle such cases was developed as part of #1185 but there is no release for this yet. You can see if 1.6.0-SNAPSHOT works for you. You could also disable this faulty MySQL emulation by providing a custom `DbmsDialect` that returns `true` for `supportsGroupByExpressionInHavingMatching`

ok，thanks，I'll try

**Comment by jwgmeligmeyling** [comment]
Both `bind(...)` and `as(alias)` are wrapping operations. Currently the serializer only supports `bind(expression).as(alias)` and not .bind(expression.as(alias))`. I will change the serializer so that it can handle both situations. Please try if `bind(expression).as(alias)` works as a workaround.

**Comment by jwgmeligmeyling** [comment]
I've implemented a fix in #1199
