### ISSUE TITLE
Wrong table updated on ManyToMany relations with two different join tables on same object

### ISSUE THREAD

**Issue by jloupdef** [Blazebit/blaze-persistence#1217]
### Description
I have en entity describing a field and another one using the first entity as two different types, "attribute" and "characteristic":

```
public static class ObjectField {
		@Id
		@GeneratedValue(strategy = GenerationType.IDENTITY)
		private Long id;
}
public static class ObjectInstance {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@ManyToMany
	@JoinTable(name = "objecttype_characteristics")
	private Set<ObjectField> characteristics;

	@ManyToMany
	@JoinTable(name = "objecttype_attributes")
	private Set<ObjectField> attributes;
}
```

At creation everything is fine, but on update the wrong JoinTable is being updated (the insert is done in the wrong one resulting depending on the order of the internal request, in no data in jointable or all in the same).

### Expected behavior
All data should go in the right jointable
```
clean jointable1
insert in jointable1
clean jointable2
insert in jointable2
```

### Actual behavior

What happened is either : 

```
clean jointable1
insert data for jointable1 in jointable1
clean jointable2
insert data for jointable2 in jointable1
```

resulting in all data in jointable 1

or

```
clean jointable1
insert data for jointable1 in jointable2
clean jointable2
insert data for jointable2 in jointable2
```
resulting in no data in jointable 1

### Steps to reproduce
Here is attached a unit test based on quarkus, but nothing is really specific to quarkus and should be easily be ported to something else (I will try to update it with unit test template if I can)
[Test.txt](https://github.com/Blazebit/blaze-persistence/files/5601832/Test.txt)
On 6 tests, 2 fails on my setup.

### Environment
Blaze 1.5.1
Quarkus 1.9.2.FINAL
Java 11

**Comment by beikov** [comment]
Thanks for the report. I'll look into this as soon as I can.

**Comment by jloupdef** [comment]
The issue seams to come from the QueryPlanCache and how the cacheKey is calculated:
Here is the four cache keys components obtained:
delete on first join table:
`SELECT 1 FROM FailTest$ObjectInstance e LEFT JOIN e.attributes _collection WHERE collection_dml_support(e.id) = :id`
insert on first join table:
`SELECT val.id, treat_integer(:id) FROM FailTest$ObjectField val WHERE val.id = :val_id_0 AND 999=999 AND val.id IS NULL`

delete on second join table:
`SELECT 1 FROM FailTest$ObjectInstance e LEFT JOIN e.characteristics _collection WHERE collection_dml_support(e.id) = :id`
insert on second join table:
`SELECT val.id, treat_integer(:id) FROM FailTest$ObjectField val WHERE val.id = :val_id_0 AND 999=999 AND val.id IS NULL`

As the key obtained for the second insert is the same as the first (join table name not taken in account), the same query plan is executed, hence the same request.

I cannot find a way to disable query plan caching with quarkus integration to validate this theory, any idea on that ?

**Comment by beikov** [comment]
Wow, what an analysis! In fact, we fixed something similar on master already: https://github.com/Blazebit/blaze-persistence/commit/0426fface4e71d2857caf31bba933358d30a040f

Could you maybe give a SNAPSHOT a shot?

**Comment by jloupdef** [comment]
Yes it's working fine with 1.6.0-SNAPSHOT, I suppose there is no chance to see a release 1.5.2 with only bugfixes ?

**Comment by beikov** [comment]
Could you try disabling the query plan cache by setting the property: https://persistence.blazebit.com/documentation/1.5/core/manual/en_US/#QUERY_PLAN_CACHE_ENABLED

Generally, we only do public fix releases for critical bug fixes. Although this is critical, it should be possible to workaround this issue by using the mentioned property. If you want such fixes to be back-ported, you'd have to consider commercial support: https://persistence.blazebit.com/support.html

**Comment by jloupdef** [comment]
Hi, I cannot find how to set this property using current Quarkus integration. I finally splitted the elements with two different objects to get it to work.

Commercial support is not an option for now, but good to know that it exists.

I think you can close this issue as it is fixed in master.

**Comment by beikov** [comment]
Thanks and sorry for the trouble. I'll do the 1.6.0-Alpha2 release soon.
