### ISSUE TITLE
How to mapping EmbeddableId with EntityView ?

### ISSUE THREAD

**Issue by alexferreiradev** [Blazebit/blaze-persistence#1235]
### Description
I need to mapping a entity that has a composed primary key, mappied in JPA with @EmbeddableId. I had searched in the documentation, but saw only FlatViews and @IdMapping("key"). However, I tried with both, and I got exceptions. 

I try with:
```java
@EntityView(Unidade.class)
public interface UnidadeView {

	@IdMapping("pk")
	UnidadePKView getPk();

	String getBairro();

	String getCidade();
}

@EntityView(UnidadePK.class)
public interface UnidadePKView {

	@Mapping("id")
	Integer getId();

	@Mapping("ano")
	Integer getAno();
}

@Entity
public class Unidade implements Serializable {
    
    @EmbeddedId
    private UnidadePK pk;
...
}

@Embeddable
public class UnidadePK implements Serializable {

    private Integer id;
    private Integer ano;
...
}

```
But got `java.lang.IllegalArgumentException: Parameter value [100] did not match expected type [*.*.*.UnidadePK (n/a)]`, so I want some documentation to how to map EmbeddableId like UnidadePK. 

### Expected behavior

Mapping with @IdMapping("pk") the blaze understand that is a EmbeddableId.

### Actual behavior

got `java.lang.IllegalArgumentException: Parameter value [100] did not match expected type [*.*.*.UnidadePK (n/a)]`

### Environment

Version:            1.5.0
JPA-Provider:    Hibernate  3.2.1.ga  
DBMS:               SqlServer 
Application Server:  Quarkus 1.7.0

**Comment by beikov** [comment]
Hi Alex,

what kind of query are you using i.e. can you share a full stack trace?

The mapping you have looks fine, so there must be an issue with the code that queries the data.

**Comment by alexferreiradev** [comment]
Sorry, i found the error. I was trying to use find with the ID, but I need the UnidadePK object:

`UnidadeView unidadeView = evm.find(em, UnidadeView.class, unidadePK);`

but I was using: 
`UnidadeView unidadeView = evm.find(em, UnidadeView.class, ciGerencia.getUnidadeID());`

Thank you so much. Sorry for the time wasted.

**Comment by beikov** [comment]
No problem :)
