### ISSUE TITLE
how to use 'SQL_CACHE'  in select statement

### ISSUE THREAD

**Issue by HLLavender** [Blazebit/blaze-persistence#1238]

**Comment by HLLavender** [comment]
mysql statement: SELECT SQL_CACHE a.name,sum(a.cost)  from a

**Comment by beikov** [comment]
This is not supported, but you can implement this yourself if you want. Create a custom JpqlFunction as described here: https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/#custom-jpql-functions

The function would look like this:

```
    @Override
    public void render(FunctionRenderContext context) {
        context.addChunk("SQL_CACHE");
        context.addArgument(0);
    }
```

and in your query, you use this for the first select item e.g. `select SQL_CACHE(a.name), sum(a.cost) from a`

**Comment by beikov** [comment]
I'll close this issue for now. If you have further questions, feel free to comment here.
