### ISSUE TITLE
Alias bug in Generated SQL After Adding Lateral Join

### ISSUE THREAD

**Issue by hanserya** [Blazebit/blaze-persistence#1239]
### Description
The title is pretty explanatory. Something in the framework is resulting in a bug when choosing the appropriate table alias to use when the same entity is joined to a query through CTEs or sub selects. If I correct this one alias in the generated SQL manually, then it runs correctly on the database via OmniDB.

Here are the immediately relevant instructions issued to create the criteria builder:

#### Criteria Builder Setup
```
CriteriaBuilder<TankInventoryActivity> criteriaBuilder = criteriaBuilderFactory.create(entityManager, Tuple.class)
        .from(SampleReadingsCte.class, "samples")
        .innerJoinOn(TankReading.class, "startReading").on("samples.sampleStartReadingId").eqExpression("startReading.readingId").end()
        .innerJoinOn(TankReading.class, "endReading").on("samples.sampleEndReadingId").eqExpression("endReading.readingId").end()
        .selectNew(new TankInventoryActivityObjectBuilder());
```

#### TankInventoryActivityObjectBuilder Excerpt
```
public class TankInventoryActivityObjectBuilder implements ObjectBuilder<TankInventoryActivity> {

  @Override
  public <X extends SelectBuilder<X>> void applySelects(X queryBuilder) {
    //this is effectively the select clause for the main query
    queryBuilder
        .select("samples.tankId")
        .select("samples.targetDateTime")
        .select("startReading.readingDateTime", "sampleStartDateTime")
        .select("startReading.volume", "startVolume")
        .select("endReading.readingDateTime", "sampleEndDateTime")
        .select("endReading.volume", "endVolume")
        .select("dropArrival.volume + earliestDelivery.volume + scheduledDelivery.volume", "deliveredVolume");
  }
...
```

### Expected behavior

I'd expect the correct alias to be referenced in the final predicate that is executed against the database as such:
```
INNER JOIN      PUBLIC.tank_readings tankreadin1_ 
ON              (( 
                                                NULL IS NULL) 
                AND             sampleread0_.sample_start_reading_id=tankreadin1_.reading_id) 
INNER JOIN      PUBLIC.tank_readings tankreadin22_ 
ON              ( 
                                sampleread0_.sample_end_reading_id=tankreadin22_.reading_id) 
```

#### From
```
...
INNER JOIN      PUBLIC.tank_readings tankreadin1_ 
ON              (( 
                                                NULL IS NULL) 
                AND             sampleread0_.sample_start_reading_id=tankreadin1_.reading_id) 
INNER JOIN      PUBLIC.tank_readings tankreadin22_ 
ON              ( 
                                sampleread0_.sample_end_reading_id=tankreadin2_.reading_id) 
...
```

As you can see, the **second** join to `tank_readings` is aliased as `tankreadin22_` in the from clause but then referenced as `tankreadin2_` in the join predicate. The select clause works just fine:

#### Select
```
SELECT          sampleread0_.tank_id                                           AS col_0_0_, 
                sampleread0_.target_date_time                                  AS col_1_0_, 
                tankreadin1_.reading_date_time                                 AS col_2_0_, 
                tankreadin1_.volume                                            AS col_3_0_, 
                tankreadin22_.reading_date_time                                AS col_4_0_, 
                tankreadin22_.volume                                           AS col_5_0_, 
                deliveredv23_.volume+deliveredv28_.volume+deliveredv33_.volume AS col_6_0_ 
FROM            ( ...
```

### Steps to reproduce
Sorry, but I don't have time to create exact steps to reproduce. I just sunk a couple of days getting this all setup to resolve a time-sensitive problem only to be tripped at the finish line. My last gasp now will be to convert these into subqueries and hope that performance holds up or am I going to be forced to toss it **all** and roll a native SQL solution - which is going to force me to delete some unit tests I'd setup for this code. Hopefully the subselect approach will serve as a workaround, but I at least wanted to get this in front of you if only to spare some poor soul from running into this in the future because it does not appear that the framework works are advertised. The best I have is what is in front of me and it is just too much to throw on here for you. The point where everything seems to fall apart; however, is when I configure a lateral join on the query I posted above as such:

```
criteriaBuilder
        .leftJoinLateralSubquery(DeliveredVolumeCte.class, "dropArrival")
        .from(SiteInventoryOrder.class, "siteOrder")
        .innerJoinOn(SiteInventoryDrop.class, "drop").on("siteOrder.orderId").eqExpression("drop.order.orderId").end()
        .innerJoinOn(SiteInventoryTankDrop.class, "tankDrop")
        .on("samples.tankId").eqExpression("tankDrop.tankId")
        .on("drop.dropId").eqExpression("tankDrop.drop.dropId").end()
        .innerJoinOn(SiteInventoryProductDrop.class, "productDrop").on("tankDrop.tankDropId").eqExpression("productDrop.tankDrop.tankDropId").end()
        .where("drop.arrivalTime").betweenExpression("startReading.readingDateTime")
        .andExpression("endReading.readingDateTime")
        .bind("volume").select("SUM(productDrop.deliveredGrossQuantity)")
        .end();
```

As you can see, I am referencing `startReading` and `endReading` here. There is not problem with the SQL alias that is generated from `startReading` but `endReading` is again referenced as `tankreadin2_` in the generated SQL instead of the `tankreadin22_` alias that ends up getting assigned to the table on the join:

```
LEFT OUTER JOIN lateral 
                ( 
                           SELECT     sum(siteinvent9_.delivered_gross_qty) 
                           FROM       PUBLIC.orders siteinvent6_ 
                           INNER JOIN PUBLIC.drops siteinvent7_ 
                           ON         ( 
                                                 siteinvent6_.id=siteinvent7_.order_id) 
                           INNER JOIN PUBLIC.dropproducts siteinvent8_ 
                           ON         ( 
                                                 sampleread0_.tank_id=siteinvent8_.tank_id 
                                      AND        siteinvent7_.id=siteinvent8_.drop_id) 
                           INNER JOIN PUBLIC.drop_product_lines siteinvent9_ 
                           ON         ( 
                                                 siteinvent8_.id=siteinvent9_.drop_product_id) 
                           WHERE      siteinvent7_.arrival_time BETWEEN tankreadin1_.reading_date_time AND        tankreadin2_.reading_date_time) deliveredv23_(volume)
ON              (( 
                                                NULL IS NULL) 
                AND             1=1) 
```

If I remove the above lateral join, then it works - but that's not good enough. I still need this data and I can't really go back and get it with a second pass given the required performance metrics of this operation. Something is causing that alias to change, but the change is not reflected everywhere that I would expect it to be.

My reference query is around 162 lines whereas the SQL that is eventually spit out is around 215 lines long. The query is entirely non-trivial or I would just paste it on here. If you want to see the reference query to get and idea of the complexity, then I can certainly provider it. I just don't want to plop a massive chunk of code in this issue if no one is interested in working with it.

### Environment

Version:                      (Core only) 1.5.1 
JPA-Provider:              Hibernate
DBMS:                         Postgres 9.6.18
Application Server:      Undertow (Spring Boot 2.1.14)

**Comment by hanserya** [comment]
OK, I think I have worked around the problem. I still need to make sure this doesn't add excessive overheard but luckily the vast majority of the heavy lifting is already done by the time we get to this step. I think it will turn out fine and should be able to stick with this toolkit for the time being.

I've gone back and refactored the query builder instructions to instead pull this data into the final results by converting the syntax from lateral joins to inline queries within another CTEs select clause. I then map this new CTE onto the object builder. The changes are as follows:

#### Initializing the criteriaBuider
```
CriteriaBuilder<TankInventoryActivity> criteriaBuilder = criteriaBuilderFactory.create(entityManager, Tuple.class)
        .from(TankInventoryActivityCte.class)
        .selectNew(new TankInventoryActivityObjectBuilder());
```

#### Mapping to ObjectBuilder
```
public class TankInventoryActivityObjectBuilder implements ObjectBuilder<TankInventoryActivity> {

  @Override
  public <X extends SelectBuilder<X>> void applySelects(X queryBuilder) {
    //this is effectively the select clause for the main query
    queryBuilder
        .select("tankId")
        .select("targetDateTime")
        .select("sampleStartDateTime")
        .select("startVolume")
        .select("sampleEndDateTime")
        .select("endVolume")
        .select("dropArrivalVolume + earliestDeliveryVolume + scheduledDeliveryVolume", "deliveredVolume");
  }
  ...
```

#### New CTE Instructions
```
FullSelectCTECriteriaBuilder<CriteriaBuilder<TankInventoryActivity>> baseQuery = criteriaBuilder.with(TankInventoryActivityCte.class)
        .from(SampleReadingsCte.class, "samples")
        .innerJoinOn(TankReading.class, "startReading").on("samples.sampleStartReadingId").eqExpression("startReading.readingId").end()
        .innerJoinOn(TankReading.class, "endReading").on("samples.sampleEndReadingId").eqExpression("endReading.readingId").end()
        .bind("tankId").select("samples.tankId")
        .bind("targetDateTime").select("samples.targetDateTime")
        .bind("sampleStartDateTime").select("startReading.readingDateTime")
        .bind("startVolume").select("startReading.volume")
        .bind("sampleEndDateTime").select("endReading.readingDateTime")
        .bind("endVolume").select("endReading.volume");

    //these act like an inline function that will run once for each record that matches the join criteria
    // within each sub-select
    //each performs a different lookup to find tank deliveries given the various states our order can be in
    baseQuery = describeDropArrivalSubSelect(baseQuery);
```

#### Lateral to Inline Query
```
private FullSelectCTECriteriaBuilder<CriteriaBuilder<TankInventoryActivity>> describeDropArrivalSubSelect(FullSelectCTECriteriaBuilder<CriteriaBuilder<TankInventoryActivity>> baseQuery) {

    //this pulls delivered volumes to each tank from drops that have an arrival date between the sample start/end dates
    return baseQuery
        .bind("dropArrivalVolume").selectSubquery()
        .from(SiteInventoryOrder.class, "siteOrder")
        .innerJoinOn(SiteInventoryDrop.class, "drop").on("siteOrder.orderId").eqExpression("drop.order.orderId").end()
        .innerJoinOn(SiteInventoryTankDrop.class, "tankDrop")
        .on("samples.tankId").eqExpression("tankDrop.tankId")
        .on("drop.dropId").eqExpression("tankDrop.drop.dropId").end()
        .innerJoinOn(SiteInventoryProductDrop.class, "productDrop").on("tankDrop.tankDropId").eqExpression("productDrop.tankDrop.tankDropId").end()
        .where("drop.arrivalTime").betweenExpression("startReading.readingDateTime").andExpression("endReading.readingDateTime")
        .select("SUM(productDrop.deliveredGrossQuantity)")
        .end();
  }
```

I still cannot seem to find any problems with the way I had setup the lateral joins, which points to a potential overwrite bug occurring when the join node switches to a lateral subquery. Hopefully this helps identify the root cause and helps anyone else out that may come across the same issue.

If y'all are already aware of the bug (or can point out where I am being daft), then feel free to close this issue. Otherwise, my hope is that we can keep it open and work towards a resolution. I am the team's "optimizer" and am rather particular about queries coming out exactly the way I expect them to when I am fine tuning a process. I am also rather particular about code portability and testability, so I very much would like to work with you in whatever capacity I can to identify the problem.

**Comment by jwgmeligmeyling** [comment]
Which Hibernate version are you using? There seems to have been a join regression in a late 5.4.x (https://github.com/Blazebit/blaze-persistence/pull/1237).

**Comment by beikov** [comment]
Thanks for the detailed description @hanserya. There are indeed join issues in Hibernate 5.4.23+ and this could be the cause for the problem that you are seeing here. Could you try downgrading to 5.4.23 and check again? I am already working on a fix for that join related issue, so maybe Hibernate 5.4.27.Final will work fine again.

I'll try to reproduce your issue in our test suite. It would help us a lot if you could provide your entity model, as right now, we can only guess what is behind the names you used in your queries and this could play a role here.

**Comment by hanserya** [comment]
Sorry for the lateness in my reply. I am actually running Hibernate 5.3.17. Unless I am mistaken, that is the version of Hibernate that is currently provided by my version of Spring Boot. 

We have work planned to upgrade our version of Spring Boot further, but we are in the unfortunate (and familiar) position of having inherited a code base where the prior developers implemented various "customizations" that make upgrading difficult without needing to account for a lot of breaking changes. 

I can certainly try rolling to the version of Hibernate as requested to test but I am honestly afraid of failures creeping in from elsewhere. I'll give it a shot and let you know.

I'll also see about pulling together some hyphenated versions of my object model and uploading it in just a bit. It might be next weekend; however, before I can pull that together for you if I am unable to peel away to address it later this evening. The wife and kiddos are only so patient with Dad and his projects around the holidays.

**Comment by jwgmeligmeyling** [comment]
The regression mentioned was only introduced in Hibernate 5.4.23+, so it cannot have caused the issue in 5.3.17.

Could you please share the full query? Generally both the JPQL query string (the outcome of `criteriaBuilder.getQueryString()`) and the produced SQL turn out to be very useful for us.

**Comment by beikov** [comment]
>I am actually running Hibernate 5.3.17

That's fine then. We only wanted to rule out issues due to join problems in Hibernate. No need to upgrade then.

>I'll also see about pulling together some hyphenated versions of my object model and uploading it in just a bit.

Sure, totally understand that. No rush :)

**Comment by beikov** [comment]
Closing stale issue. Please re-open it with a reproducer when it is still a problem @hanserya
