### ISSUE TITLE
Explicit association joins are not rendered into the respective "table reference"

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1240]
When we write a query like the following:

```
CriteriaBuilder<Document> crit = cbf.create(em, Document.class)
    .select("d")
    .from(Document.class, "d")
    .from(Person.class, "p")
    .leftJoin("d.people", "person")
```

We currently render it as the following HQL:

```
SELECT d
FROM Document d, Person p
LEFT JOIN d.people person
```

which is wrong, because the join is now part of the second group i.e. what SQL calls "table reference". A table reference can not refer to other table references, unless lateral is used, so one way around this would be to avoid rendering table references at all and instead render joins, but I'm not sure what the effect on DBMS optimizers would be, so if we do this, there should be a configuration property to restore the old behavior.

To workaround the problem, one just has to move the explicit join up i.e. before starting a new table reference like this:

```
CriteriaBuilder<Document> crit = cbf.create(em, Document.class)
    .select("d")
    .from(Document.class, "d")
    .leftJoin("d.people", "person")
    .from(Person.class, "p")
```

I understand that this might not always be possible and we can do better. We need some kind of knowledge about "table references" in our join model to handle this. When we need to render a table reference due to a join dependency, we could render it as cross join to make the aliases on the LHS available. In case of a join dependency across "table references", it's necessary to render table references as cross joins anyway, so this should be fine.

**Comment by jwgmeligmeyling** [comment]
How would

```
CriteriaBuilder<Document> crit = cbf.create(em, Document.class)
    .select("d")
    .from(Document.class, "d")
    .leftJoin("d.people", "person")
    .from(Person.class, "p")
```

be rendered then? Would it convert the table reference to an inner join?

Personally I wouldn't be surprised if both builders returned the same - problematic - JPA and SQL, because to me it seems to make quite some sense that all `from` clauses are processed first.

**Comment by beikov** [comment]
That would render as:

```
SELECT d
FROM Document d
LEFT JOIN d.people person, Person p
```

Internally, we respect the order of explicit joins/from items the user gives us which is why this is an issue right now. Unfortunately, JPA does not have a cross join, so re-interpreting the "table reference" as cross join by doing a `a join b on 1=1` is the best we can do.

**Comment by jwgmeligmeyling** [comment]
Woah, never knew that was valid syntax 😄  No wonder it was overlooked.
