### ISSUE TITLE
NullPointerException when using spring-boot-devtools

### ISSUE THREAD

**Issue by slyoldfox** [Blazebit/blaze-persistence#1247]
### Description
Created the demo project using the spring-boot maven archetype:
`mvn archetype:generate "-DarchetypeGroupId=com.blazebit" "-DarchetypeArtifactId=blaze-persistence-archetype-spring-boot-sample" "-DarchetypeVersion=1.5.1"`

Add the spring-boot-devtools dependency:
```
<dependency>
     <groupId>org.springframework.boot</groupId>
     <artifactId>spring-boot-devtools</artifactId>
     <optional>true</optional>
</dependency>
```

### Expected behavior
The Application should startup.

### Actual behavior
Application startup fails with NullPointerException
```
Caused by: java.lang.NullPointerException: null
	at com.blazebit.persistence.view.impl.metamodel.ViewMetamodelImpl.<init>(ViewMetamodelImpl.java:117) ~[blaze-persistence-entity-view-impl-1.5.1.jar:1.5.1]
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.<init>(EntityViewManagerImpl.java:261) ~[blaze-persistence-entity-view-impl-1.5.1.jar:1.5.1]
```

### Environment

Version:         1.5.1    
JPA-Provider:       
DBMS:               
Application Server: Spring Boot

This is due to the fact that the Spring Devtools RestartClassLoader instantiates another Class instance for the entities.

When `EntityModelImpl.getManagedTtype` the `Class` instance which is passed as an argument, for the same domain-type, will be a different `Class` instance. This will cause `.classMap.get()` to return `null`.

The bug is inside `EntityViewConfigurationDelegate`. 
Instead of using:
`Class<?> clazz = Class.forName(candidate.getBeanClassName());`

You should use the `ClassUtils` from Spring itself which will gracefully recognize Spring Boot's `RestartClassLoader`.

Something like this seems to work for me locally:
`Class<?> clazz = ClassUtils.forName( candidate.getBeanClassName(),  resourceLoader == null ? null : resourceLoader.getClassLoader() );`

I will see if I can create a PR for this, however a test case is a bit complicated due to the fact it includes classloaders.

**Comment by beikov** [comment]
Hi, please note that there is no out of the box integration with dev tools yet as you can read here: https://persistence.blazebit.com/documentation/1.5/entity-view/manual/en_US/#spring-boot-devtools

**Comment by slyoldfox** [comment]
Yes I saw the documentation about it, but it seems to work fine here after this fix (as far as I can see?)

**Comment by beikov** [comment]
I'm open for any contributions in this area and it might very well be that easy, but I am not dev tools expert, so to be honest, I don't know. If it works for you with this fix, please open a PR and I'll integrate it :)

**Comment by slyoldfox** [comment]
I gave it a go to fix this, I hope this works out :-)

General rule of thumb is use the ClassLoader as much as possible instead of using the Class.forName constructs - so I'm not sure if there might be other issues still around (just starting out with the demo).
