### ISSUE TITLE
Method reflection data missing for entity view bootstrap

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1253]
[`com.blazebit.persistence.integration.quarkus.deployment.BlazePersistenceProcessor#263`](https://github.com/Blazebit/blaze-persistence/blob/e80f12bb979aa0139b4d640f80383be5a1b6aa61/integration/quarkus/deployment/src/main/java/com/blazebit/persistence/integration/quarkus/deployment/BlazePersistenceProcessor.java#L263) currently does not add the method reflection data: `reflectionProducer.produce(new ReflectiveClassBuildItem(true, false, false, entityViewClassName));` but this is needed at runtime currently in `com.blazebit.persistence.integration.quarkus.runtime.EntityViewRecorder#entityViewManagerSupplier` through the call to [`com.blazebit.persistence.view.spi.EntityViewConfiguration#addEntityView`](https://github.com/Blazebit/blaze-persistence/blob/e969fbfcc10b4d09bf4ffafdaeb025d60e3fefb8/integration/quarkus/runtime/src/main/java/com/blazebit/persistence/integration/quarkus/runtime/EntityViewRecorder.java#L61), which does the annotation reading. This was reported on the Quarkus Zulip by a user: https://quarkusio.zulipchat.com/login/#narrow/stream/187030-users/topic/Blaze.20Persistence.20in.20Native-Mode

IMO we shouldn't do any annotation reading at runtime. We should remove the `EntityViewListenersBuildItem` and `EntityViewsBuildItem` and instead create a `EntityViewConfigurationBuildItem` so that we do the annotation reading already during image building. If that turns out to be impossible, adding the reflection data for methods is necessary.

**Comment by Mobe91** [comment]
Your suggested approach was what I tried during the initial development of the Quarkus extension. However, it's not possible because `EntityViewConfiguration` is not `Serializable`. Here is an exempt of the exception that gets thrown during image build with this approach:
```
[ERROR] Caused by: java.lang.RuntimeException: Cannot serialise field 'mappingIndex' on object 'com.blazebit.persistence.view.impl.metamodel.MethodAttributeMapping@5ed28611' as the property is read only
[ERROR]         at io.quarkus.deployment.recording.BytecodeRecorderImpl.loadComplexObject(BytecodeRecorderImpl.java:1292)
[ERROR]         ... 21 more
```

Apart from that, I was not able to consistently reproduce this issue with the example project provided, independent of including methods in reflection or not. Also, our own native image integration tests did not show this issue. Not sure how to proceed here....

**Comment by beikov** [comment]
Like I told you, I was able to reproduce this consistently with the example project.

Does the exception happen during build time or runtime? If it happens at runtime, we might be able to get away with registering `@Substitution` for fields in `EntityViewConfigurationImpl` etc. to make them non-final and add setters so that de-serialization at runtime works. Too bad that setting final fields doesn't work, but then Java Serialization would work as well...

**Comment by beikov** [comment]
Seems like the serialization approach won't work for now, but could be done as an improvement for a future Quarkus version: https://quarkusio.zulipchat.com/login/#narrow/stream/187038-dev/topic/BytecodeRecorder.20for.20complex.20build.20items

**Comment by beikov** [comment]
After thinking more about this and understanding the reasoning, I think the only viable approach is to adapt the configuration code such that we can use the `BytecodeRecorder` substitutions for a custom serialization/deserialization protocol.

Maybe it's enough to introduce a few constructors in implementations for Quarkus to be able to set the final fields and setters for setting mutable fields. Since we would add these methods into implementations it wouldn't be a big deal as that would not be user facing.

**Comment by Mobe91** [comment]
> Does the exception happen during build time or runtime?

The exception happens during build time.
