### ISSUE TITLE
Are there some way to use filter contains or "like" with integer ? 

### ISSUE THREAD

**Issue by alexferreiradev** [Blazebit/blaze-persistence#1264]
### Description

I need some way to use filter in a entity atributte Integer to make a sql like:
`"select * from entity where id like '576031%' "`
Are there some way to do that ? I tried with `ContainsFilter`, but receive:
`Parameter value [%576031%] did not match expected type [java.lang.Integer (n/a)]`

I tested my MSSQL with a native sql and works fine. The SGBD convert the id to text and use like to filter.

My entityView:
```java
@Mapping("id")
@AttributeFilter(name = "eq", value = ContainsFilter.class)
public abstract Integer getCodigo();
```

My Filter:
```java
idFiltro.ifPresent(f -> entityViewSetting.addAttributeFilter("codigo", "eq", f));
```

### Expected behavior

Make a sql like: `"select * from entity where id like '576031%' "`

### Actual behavior

Exception with: Parameter value [%576031%] did not match expected type [java.lang.Integer (n/a)]

### Environment

<blaze-persistence.version>1.5.0</blaze-persistence.version>

JPA-Provider:       Hibernate 5.2.7.Final		-->
DBMS:              MS SQL 
Application Server: <quarkus.platform.version>1.7.0.Final</quarkus.platform.version>

**Comment by beikov** [comment]
Hi @alexferreiradev 

if you want a string search, you will have to do a cast in the mapping. Also, to do a prefix search, you can use the `StartsWithFilter`.

```
@Mapping("CAST_STRING(id)")
@AttributeFilter(name = "eq", value = StartsWithFilter.class)
public abstract String getCodigo();
```

**Comment by beikov** [comment]
This is an SPI, so you could even create a custom filter if you want to do the cast just for the filter. See https://persistence.blazebit.com/documentation/1.5/entity-view/manual/en_US/#custom-filters for more information on this topic.

**Comment by alexferreiradev** [comment]
Thank you for the fasted answer. I did not know about the cast way, I will use that. Thank you.

**Comment by beikov** [comment]
Glad I could help you :)
