### ISSUE TITLE
Issues with Optional when using annotation processing

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1270]
The annotation processor generates for the static metamodel `SingularAttribute<X, Optional>` i.e. without the parameter types which is unfortunate. IMO we should somehow make sure it uses the actual target type instead.
Apart from that, the impl classes initialize null for Optional, which is a bummer. IMO we should try to register some defaults.

On top of that, the runtime uses `java.util.Optional` as class when trying to figure out the target element type for subview attributes in `com.blazebit.persistence.view.impl.EntityViewManagerImpl#initializeStaticMetamodel#559` which results in `ClassNotFoundException java.util.OptionalRelation`. The problem is that we use the wrong type i.e. we need to use the actual model type rather than the java type.

**Comment by EugenMayer** [comment]
Thank you for working on that one!

**Comment by beikov** [comment]
Another issue that came up is, that the generated implementation classes require the static metamodel to work properly. To prevent possible NPEs due to that, we should validate the configuration i.e. generating just implementation without static metamodel should be disallowed. Also, disabling static metamodel scanning without also disabling implementation scanning should be disabled as well.

**Comment by beikov** [comment]
Another issue that just came up is that the generated builders use a wrong type parameter i.e. the inner class `Init` extends the base builder but passes `EntityViewBuilder<View>` as type parameter, although it should pass `Init` so that fluent building works.

**Comment by EugenMayer** [comment]
Thanks for working on that one!
