### ISSUE TITLE
Prototype entity view instatiator

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#128]
If you want to access properties that you mapped in an entity view within it's constructor, you have to map it again in the constructor as parameter. We can maybe initialize fields before calling the constructor. This would effectively solve the issue because then one could use the getters.

**Comment by beikov** [comment]
As per JVMS-2.9 it should be allowed to invoke putfield before invoking the constructor: https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-2.html#jvms-2.9
Therefore this is actually doable and should be prototyped!

**Comment by beikov** [comment]
Just tried it out, apparently the verifier disallows putfield before proper initialization. Seems we have to take the unsafe path.

**Comment by beikov** [comment]
Actually this brings more problems than it solves. I think a better solution would be to introduce a post construct method.

**Comment by beikov** [comment]
PostConstruct won't work because you can't work with finals in that case.
I think one possible solution would be to source map the generated proxy class and just copy the constructor contents. Finally we create the object with Objenesis

**Comment by beikov** [comment]
Added first prototype: https://github.com/Blazebit/blaze-persistence/commit/f5773375bb66ff5716d93d468c3e84103d542fdc
Does not work properly yet because of random NPEs. See the mailing list for reference: http://mail.openjdk.java.net/pipermail/jdk8-dev/

**Comment by beikov** [comment]
Actually I found the problem already. The constructor will try to put the values into the field slots of it's class. Since we have a different class here, we need to take care that the slots of the target objects class match the slots of the class the constructor belongs to. This shouldn't be too hard and with sun.misc.Unsafe we can even check if the slots match. If they don't we could abort or retry.

**Comment by beikov** [comment]
The prototype which uses the serialization construtor is done but the whole thing is unstable on JDK < 8: https://travis-ci.org/Blazebit/blaze-persistence/builds/75816397
In my opinion the only possible way to get this working is to delay the ```invokespecial``` call to the super constructor until all fields are initialized, but the verifier complains about that.
I guess I have to define the class with Unsafe directly just like ReflectionFactory does in order to skip the verifier.

**Comment by beikov** [comment]
Loading the bytecode via Unsafe to skip the verifier works suprisingly well! I am thinking of integrating this solution(5b4d7409b971ddfb8b6d6c6b37dd38f28682cb2b) into the master branch and make it configurable.

**Comment by asm0dey** [comment]
How will you workaroud it after removing Unsafe in JDK 9?

**Comment by beikov** [comment]
According to what was written on the mailing list(http://mail.openjdk.java.net/pipermail/jigsaw-dev/2015-August/004433.html) there will be a replacement for sun.misc.Unsafe. I am following that discussion and will fix problems that might occur with the UnsafeInstantiator on JDK9.
I am open for other implementation suggestions, but so far I didn't come up with any other approach that offers the same functionality so elegantly.
The only idea I had so far was to allow the injection of an interface that a class implements if it's for the same entity. I guess that would look like less voodoo, but still, that wouldn't be as convenient. Here an example:

```
@EntityView(Animal.class)
interface BaseAnimalView {
  String getName();
}

@EntityView(Animal.class)
abstract class MyAnimalView implements BaseAnimalView {
  private final String title;
  public MyAnimalView(BaseAnimalView self) {
    this.title = self.getName();
  }
  public String getTitle() {
    return title;
  }
}
```

Would that be a better approach? It kind of forces you to create a separate interface and then you also have to add that in the constructor. Doesn't really feel that cool but would definitely be something that always works. It would require to instantiate a BaseAnimalView proxy for every MyAnimalView proxy which is a waste.

**Comment by asm0dey** [comment]
I agree that Unsafe approach can be very beautiful. Maybe you should use it and fall back to pure java approach if functionality won't be available in JDK9. Also you can publish 2 versions of library — for <=JDK8 and >=JDK9 if hanges there will be breaking.

**Comment by beikov** [comment]
Playing around with the thought of including this in 1.1.0 and enabling it by default. I would also add a config option to be able to disable it.

**Comment by beikov** [comment]
Merged into with https://github.com/Blazebit/blaze-persistence/pull/153

**Comment by beikov** [comment]
Fixed by https://github.com/Blazebit/blaze-persistence/commit/a15cadf8f6e83ef94bad8f1da73972baad911148
