### ISSUE TITLE
Support polymorphic entity views in JAX-RS endpoint

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1300]
See https://stackoverflow.com/questions/67232469/blaze-persistence-entityview-inheritance-mapping for details.

The idea is to make use of `@JsonTypeInfo` from Jackson to construct a subtype instead of the declared type.

**Comment by euks** [comment]
Hi, I'm the one who made the question on stackoverflow. I needed to deserialize (in a jaxws operation) my entity views organized in a hierarchy. I made it work using jackson annotation for inheritance. This is the base view:
```
@EntityView(Content.class)
@EntityViewInheritance
@JsonTypeInfo(
        use = JsonTypeInfo.Id.NAME,
        property = "type")
@JsonSubTypes({
        @JsonSubTypes.Type(value = DescriptiveContentView.class, name = "descriptive"),
        @JsonSubTypes.Type(value = MediaContentView.class, name = "media"),
        @JsonSubTypes.Type(value = WebContentView.class, name = "web")
})
@JsonTypeName("content")
public abstract class ContentView {
    @IdMapping
    public abstract Long getId();
    public abstract boolean isPublished();
}
```
And here's a subview:

```
@EntityView(DescriptiveContent.class)
@JsonTypeName("descriptive")
public abstract class DescriptiveContentView extends ContentView {
    public abstract Set<LocalizedParagraphView> getLocalizedParagraphs();
}
```

**Comment by beikov** [comment]
Hi, so does this configuration you have there already work? Or is that what you would like to use?

**Comment by euks** [comment]
This configuration already works

Il giorno lun 26 apr 2021 alle 21:08 Christian Beikov <
***@***.***> ha scritto:

**Comment by beikov** [comment]
Interesting. So what is it that does not work?

**Comment by euks** [comment]
Nothing. It works like a charm. I hadn't try the Jackson annotations cause I thought they were not supported.

**Comment by beikov** [comment]
Ahh, that's nice. I wasn't aware that this is working correctly to be honest 😄
