### ISSUE TITLE
Generated EntityViewImpl constructor will throw NPE for additional @Mapping collection fields

### ISSUE THREAD

**Issue by sullrich84** [Blazebit/blaze-persistence#1307]
### Description

Generated `CatWithKittenViewImpl` constructor will throw `NullPointerExceptions` for additional `@Mapping` collection fields. See the following scenario:

    public interface CatWithKittenView extends CatIdView {
		@Mapping("kittens[gender=com.example.Gender.MALE].owner")
		Collection<PersonIdView> getMaleKittenOwners();
	}

The generated `CatWithKittenViewImpl` constructor:

	public CatWithKittenViewImpl(        Long id) {
        this.$$_kind = (byte) 1;
        this.maleKittenOweners = (Collection<PersonIdView>) (java.util.Collection<?>) CatWithKittenView_.maleKittenOwners.attr().getCollectionInstantiator().createCollection(0);
        this.id = id;
    }

In this case `CatWithKittenView_.maleKittenOwners` will throw the NPE since there is no `maleKittenOwners` field mapped in the enitiy.

### Environment

Version: 1.6.0
JPA-Provider: 5.4
DBMS: MariaDB
Application Server: Tomcat (Spring Boot)

**Comment by beikov** [comment]
Did you set the `com.blazebit.persistence.view.static_metamodel_scanning_disabled` to `true`? https://persistence.blazebit.com/documentation/1.6/entity-view/manual/en_US/#STATIC_METAMODEL_SCANNING_DISABLED

The static implementations do not work when disabling this setting.

**Comment by sullrich84** [comment]
We have `com.blazebit.persistence.view.static_metamodel_scanning_disabled`, `com.blazebit.persistence.view.static_builder_scanning_disabled` and `com.blazebit.persistence.view.static_implementation_scanning_disabled` set to `true`

**Comment by beikov** [comment]
Can you please confirm if enabling the scanning resolves your issue?

**Comment by sullrich84** [comment]
Removing the `entityViewConfiguration.setProperty("com.blazebit.persistence.view.static_metamodel_scanning_disabled", "true");` solved the reported issue 👍🏻

**Comment by beikov** [comment]
Thanks for confirming!
