### ISSUE TITLE
Get clause dependencies right for fetch joins

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#131]
Today we have added the SELECT clause to the clause dependencies for fetch join nodes (and recursively to their parents) because there was a case in which an explicit fetch join was not included in the final query due to empty clause dependencies.
However, the current workaround is not entirely right since there are cases in which a fetch of one node in the hierarchy does not imply the fetch of all other nodes in the hierarchy. This should be done right.

**Comment by beikov** [comment]
We will add the temporary fix in https://github.com/Blazebit/blaze-persistence/milestones/1.0.3

**Comment by beikov** [comment]
I can't remember what the "not entirely right" meant. We should have made that explicit when we still knew what it was about. If you don't know it either and no problems arise, I think this is closed.
