### ISSUE TITLE
Efficient Entity View Result Streaming

### ISSUE THREAD

**Issue by kekbur** [Blazebit/blaze-persistence#1317]
JPA 2.2 added the method `getResultStream()` to the `TypedQuery` interface with a default implementation that first loads all the results into memory and then returns a stream.

Blaze Persistence has multiple classes which implement `TypedQuery`, for example `ObjectBuilderTypedQuery` and `TypedQueryWrapper`.

I would suggest adding implementations of `getResultStream()` to those classes so that they do not use the inefficient default implementation.

TypedQueryWrapper.java:
```java
//...
    @Override
    public Stream<X> getResultStream() {
        return delegate.getResultStream();
    }
//...
```

ObjectBuilderTypedQuery.java:
```java
//...
    @Override
    public Stream<X> getResultStream() {
        return super.getResultStream().map(tuple -> {
            if (tuple instanceof Object[]) {
                return builder.build((Object[]) tuple);
            } else {
                return builder.build(new Object[] { tuple });
            }
        });
    }
//...
```

These changes allow entity view results to be streamed without first being fully loaded into memory if the underlying JPA provider supports it. I've tested it to work with Hibernate 5.4.

**Comment by beikov** [comment]
Hi,

I don't think this will in general do what you want unfortunately. It's a bit more complex when collections are involved, but maybe there are none in your case and it's fine? Anyway, there is an open issue about supporting this #254

I will still try to see what I can do about this specific issue. Thanks for the report!

**Comment by kekbur** [comment]
You're right, there are no collections involved in my use case. Thanks for looking into this.

**Comment by jwgmeligmeyling** [comment]
Hibernate 5.2 and up require Java 8 anyway, so we could set the language level in these modules to Java 8 and extend `TypedQueryWrapper` and `ObjectBuilderTypedQuery` there. Then these implementations can delegate the `stream()` call. However, that likely also means moving these from `com.blazebit.persistence.impl.query` to `com.blazebit.persistence.spi`. And I am not sure if all places where `TypedQueryWrapper` and `ObjectBuilderTypedQuery`  are currently have access to `ExtendedQuerySupport`.

**Comment by beikov** [comment]
As discussed today with @jwgmeligmeyling, it's just not doable to support this without bumping the language level to 1.8 because we need `Stream` in the method signature of our query implementations, so we will defer this to 2.0
