### ISSUE TITLE
Issue with LocalDate as literal in 1.6+

### ISSUE THREAD

**Issue by jcputney** [Blazebit/blaze-persistence#1321]
### Description
Our application is working just fine in 1.5, but when we try upgrading to 1.6, we all of a sudden start seeing query exceptions when trying to use LocalDate/LocalDateTime as literals in the criteria builder.

### Expected behavior
Dates get properly parsed into the query

### Actual behavior
We get an error message that says `java.lang.IllegalArgumentException: org.hibernate.QueryException: unexpected char: '{'` with the date being parsed into the query as `{d '2021-07-12'}`

### Steps to reproduce
We're using a PaginatedCriteriaBuilder to build an EntityView query against a simple Entity model. We're not doing much more than just saying `builder.where("field").leLiteral(LocalDate.now())` and we're getting the error message. Most of our queries use dates, so this is breaking our entire application. If I find time, I will setup a proper test case for this.

### Environment
Version: 1.6+
JPA-Provider: Hibernate 5.3.20.Final
DBMS: MySQL 5.7
Application Server:  Wildfly 24

**Comment by beikov** [comment]
Thanks for the report. I'll look into it next week when I'm back from my vacation :)

**Comment by jwgmeligmeyling** [comment]
How did it get parsed on 1.5? Because `{d '2021-07-12'}` seems a valid date literal to me. Were your prior tests also against Hibernate 5.3.20.Final?

**Comment by jcputney** [comment]
@jwgmeligmeyling not sure, is there a way to check what was being parsed? The only way I can tell right now is because I'm receiving the error message. Yes, it was working on 1.5/1.5.1 on Hibernate 5.3.20.Final.

**Comment by beikov** [comment]
The exception suggests that the literal is passed through to HQL but it doesn't support the JDBC escape syntax properly. For this purpose, we actually created some emulations if I remember correctly, but these are conditional based on the Hibernate version. Are you running with an uber jar maybe @jcputney ?

**Comment by jcputney** [comment]
@beikov No, we're just using the version built into Wildfly 24

**Comment by beikov** [comment]
It would be awesome if you could share a reproducer for this because we actually have a test for this. You can add your reproducer to that test if you like: https://github.com/Blazebit/blaze-persistence/blob/master/core/testsuite/src/test/java/com/blazebit/persistence/testsuite/TemporalLiteralRenderingTest.java

**Comment by beikov** [comment]
I was able to reproduce your issue and just opened a PR to fix this. In case you want to verify that your particular issue is fixed, let me know if the fix works for you :)
