### ISSUE TITLE
how to build like querydsl  .where(A.and(B).or(C)).where(D.and(E).or(F))

### ISSUE THREAD

**Issue by 943739901** [Blazebit/blaze-persistence#1323]
I am coding a util to build dynamic conditions. convert json into conditions.
data format like this 
``` json
[
        {
          "val": "grade 2021",
          "key": "gradeName",
          "op": "LIKE"
        },
        {
          "l": "and",
          "value": "class 2",
          "key": "name",
          "op": "LIKE"
        },
        {
          "l": "or",
          "val": "1",
          "key": "id",
          "op": "EQ"
        },
 ]
```
may be multiple arrays.
I used many "if" adapting "whereAnd" and "whereOr", because I must know when to end them.
Is there a method like this?

.where(A.and(B).or(C))
.where(D.and(E).or(F))

 I did not find how to code like above from doc.  (I don’t really want to generate Q class if there are other solutions)

**Comment by jwgmeligmeyling** [comment]
Assuming you use the Blaze-Persistence CriteriaBuilder API and not the Blaze-Persistence Querydsl integration (in the latter case, it would work the same as you're accustomed to in Querydsl).

For the `CriteriaBuilder` API you would need to use the `whereOr` and `whereAnd` builder modes:

```java
.whereOr()
    .whereAnd()
         .where("a")
         .where("b")
    .endAnd()
    .where("c")
.endOr()
```

**Comment by 943739901** [comment]
Is there only this way ?

**Comment by jwgmeligmeyling** [comment]
There is also .setWhereExpression(“a OR b”)

**Comment by 943739901** [comment]
thank you , Finally I solved the problem with 'whereOr'
