### ISSUE TITLE
Annotation Processor generates invalid import statements with annotations like NotNull 

### ISSUE THREAD

**Issue by ahofmeister** [Blazebit/blaze-persistence#1324]
### Description

Using javax.validation annotations with annotation processor generates invalid import statements for the view implementation and the view builder.  

The use case was to use those annotations in order to validate incoming views from JAX-RS requests, like `NotNull`.

### Expected behavior

I expect the annotation processor to generate a valid view class implementation.

### Actual behavior

The import for `@Min(20)` is right before the import of the attribute type (label). 
```
package com.example;

import @javax.validation.constraints.Min(20L) java.lang.Integer;
import com.blazebit.persistence.view.EntityViewManager;
import com.blazebit.persistence.view.SerializableEntityViewManager;
import com.blazebit.persistence.view.StaticImplementation;
import com.blazebit.persistence.view.spi.type.EntityViewProxy;
import java.util.Map;
import java.util.Objects;
import javax.annotation.Generated;
```

### Steps to reproduce

See: https://github.com/ahofmeister/blaze-persistence-annotation-processor-reproducer

### Environment

Version:            
JPA-Provider:       
DBMS:               
Application Server:  Quarkus 2.0.2.Final

**Comment by beikov** [comment]
Thanks for the report and reproducer. I'll look into it as soon as possible.

**Comment by beikov** [comment]
I recently fixed a similar issue in Hibernate, so the implementation will be similar: https://github.com/hibernate/hibernate-orm/pull/4096

**Comment by ahofmeister** [comment]
btw: We tested our use case with the version 1.6.6 and it works perfectly. Thanks so much! :)
