### ISSUE TITLE
QueryDSL add Support for 5.0

### ISSUE THREAD

**Issue by eiswind** [Blazebit/blaze-persistence#1329]
I tried to update QueryDSL to 5.0 and it failed with an Exception like:

```
java.lang.NoSuchFieldError: hints

	at com.blazebit.persistence.querydsl.AbstractBlazeJPAQuery.getQueryable(AbstractBlazeJPAQuery.java:234)
```

Are there plans to update to 5.0.0?

**Comment by beikov** [comment]
Hi, would you mind trying out the current snapshot? Support for 5.0 was committed recently: https://github.com/Blazebit/blaze-persistence/commit/ecdb6858b134b9265253905f45c3a4c97677526e

**Comment by eiswind** [comment]
Thanks for the hint. Can I find a snapshot build on any maven repository? Did not find it in the docs. Or do I have to build my own?

**Comment by beikov** [comment]
The OSS snapshots are available in the Sonatype repository: `https://oss.sonatype.org/content/repositories/snapshots/`

**Comment by eiswind** [comment]
Thanks for letting me know. I tired some basic examples, which seem to work!

**Comment by beikov** [comment]
Great to hear that. I will try to publish a release this weekend after integrating some GraphQL related updates.
