### ISSUE TITLE
GraphQL: Sorting does only work for fields which are fetched in the requests

### ISSUE THREAD

**Issue by EugenMayer** [Blazebit/blaze-persistence#1331]
Consider we are sorting by `id` and `title`, both fields of the `EntityGraphQlView`.
We are adding those to the `settings` in the data-fetcher statically.

Now, when running a query like this 

```graphql
query{
  pages(first: 10, offset: 0){
    edges {
      node {
      	id
        title
    	}
    }
    totalCount
  }
}
```
It would work just fine. 

But using a query which will not fetch the `title` field 

```graphql
query{
  pages(first: 10, offset: 0){
    edges {
      node {
      	id
    	}
    }
    totalCount
  }
}
```

will fail with

```
"java.lang.IllegalArgumentException: Attribute 'PageGraphQlView_title' not found on type 'Node'",
```

**Comment by beikov** [comment]
The solution here is to render the expression directly instead of the alias or force the fetching of the expression. I'll look into this ASAP.
