### ISSUE TITLE
Updatable non-PK subview mapping referring to PK-Id view fails persisting

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1334]
The case is the following:

```
@Entity
public class Node {
  @Id
  Long id;
  @ManyToOne(fetch = LAZY)
  @JoinColumn(name = "uid", referencedColumnName = "uid")
  User user;
}

@Entity
public class User {
  @Id
  Long id;
  @Column(name = "uid", unique = true)
  Long uid;
}

@EntityView(Node.class)
@UpdatableEntityView
public interface NodeView {
  Long getId();
  UserIdView getUser();
  void setUser(UserIdView user);
}

@EntityView(User.class)
public interface UserIdView {
  Long getId();
  Long getUid();
}
```

Flushing a `NodeView` doesn't work because the FK column is set to null due to the use of a proxy for `User`. The problem is in `AbstractEntityLoader` which should never use the id-mapping of the target view, but instead use the FK-mapping. We might need to emit a warning though if the target view does not have an attribute for that FK-mapping.

**Comment by EugenMayer** [comment]
Thanks for takling this one. I just tested the broken invocation path (production).

Using 1.6.0 without the work around you helped with, throws an exception. Using 1.6.2 does not.

Or in other words, it has been fixed successfully and I'm super happy, thanks!
