### ISSUE TITLE
JPA Criteria joins over embeddables do not render properly

### ISSUE THREAD

**Issue by ask4gilles** [Blazebit/blaze-persistence#1350]
Hi @beikov ,

Follow up from https://github.com/Blazebit/blaze-persistence/issues/1333 and https://github.com/Blazebit/blaze-persistence/issues/1348#issuecomment-913167000 where you said:

> Looks like a bug in Spring Data 2.5 ;)
> You can make use of a specification to model this though or if you want to use an entity view, use an attribute filter:
> ```
> @EntityView(BundleRequestEntity.class)
> public interface BundleRequestSimpleView {
>     @AttributeFilter(EqualFilter.class)
>     @Mapping("bundleRequestParameters.tokenRange.keyAlias")
>     String getKeyAlias();
> }
> @Repository
> public interface RequestRepository extends JpaRepository<BundleRequestEntity, UUID> {
>     default List<BundleRequestSimpleView> findByBundleRequestParametersTokenRangeKeyAlias(String keyAlias) {
>         return findAll(setting -> setting.withAttributeFilter("keyAlias", keyAlias));
>     }
>     List<BundleRequestSimpleView> findAll(EntityViewSettingProcessor<BundleRequestSimpleView> processor);
> }
> ```
Please find here attached a reproducer. [demo.zip](https://github.com/Blazebit/blaze-persistence/files/7116085/demo.zip)

Run this application and target http://localhost:8080/demo
No exception.

Run the application with  'blaze' as profile and target http://localhost:8080/demo
then you will see the exception

The 'blaze' profile triggers the BP configuration (see `DemoApplication`)

Let me know if I'm missing something here ;-)

Thanks!

**Comment by beikov** [comment]
Thanks for the reproducer, I will take a look ASAP.
