### ISSUE TITLE
JPA criteria like expression fails with escape character

### ISSUE THREAD

**Issue by perch24** [Blazebit/blaze-persistence#1362]
### Description
The JPA criteria API fails when parsing a like expression with an escape character. The JPQL parser outputs "Only a character literal is allowed as escape character in like predicate" when creating the criteria builder.

### Steps to reproduce
Adding the following test to jpa-criteria/testsuite/src/test/java/com/blazebit/persistence/criteria/WhereTest.java will reproduce the issue.

```java
    @Test
    public void likeWithEscapeCharacter() {
        BlazeCriteriaQuery<Long> cq = BlazeCriteria.get(cbf, Long.class);
        BlazeCriteriaBuilder cb = cq.getCriteriaBuilder();
        Root<Document> root = cq.from(Document.class, "document");

        cq.select(root.get(Document_.id));
        cq.where(cb.like(root.get(Document_.name), "abc\\_%", '\\'));

        CriteriaBuilder<?> criteriaBuilder = cq.createCriteriaBuilder(em);
        assertEquals("SELECT document.id FROM Document document WHERE document.name LIKE :generated_param_0 ESCAPE :generated_param_1", criteriaBuilder.getQueryString());
        assertEquals("abc\\_%", criteriaBuilder.getParameterValue("generated_param_0"));
        assertEquals('\\', criteriaBuilder.getParameterValue("generated_param_1"));
    }
```

### Environment

Version: 1.6.3-SNAPSHOT           
JPA-Provider: N/A       
DBMS: N/A              
Application Server: N/A

**Comment by beikov** [comment]
Hi and thanks for the bug report. I'll look into it for the next release. You should be able to workaround this by using `cb.literal()` explicitly, like this:

        cq.where(cb.like(root.get(Document_.name), "abc\\_%", cb.literal('\\')));
