### ISSUE TITLE
groupBy generates wrong query in Querydsl integration

### ISSUE THREAD

**Issue by abarazal** [Blazebit/blaze-persistence#1364]
I've moved from pure Querydsl to Blaze Persistence because I'm trying to generate a query grouped by two fields. The problem is when I add `groupBy` method it generates a wrong query.
This is my code:
```java
BlazeJPAQuery<TicketRow> query = new BlazeJPAQuery<>(entityManager, cbf).from(turnRequest)
                .select(Projections.constructor(TicketRow.class, grain.name, turnRequest.deliveryDate.stringValue(),
                        ticket.id, customer.businessName, dealer.businessName, Expressions.asNumber(0),
                        zone.name, ticketType.name, ticketStatus.name))
                .innerJoin(ticket).on(ticket.id.eq(turnRequest.ticket.id))
                .innerJoin(grainZone).on(grainZone.id.eq(ticket.grainZone.id))
                .innerJoin(grain).on(grain.id.eq(grainZone.grain.id))
                .innerJoin(zone).on(zone.id.eq(grainZone.grain.id))
                .innerJoin(dealer).on(dealer.id.eq(ticket.dealer.id))
                .innerJoin(turnRequestStatus).on(turnRequestStatus.id.eq(turnRequest.status.id))
                .innerJoin(ticketType).on(ticketType.id.eq(ticket.type.id))
                .innerJoin(ticketStatus).on(ticketStatus.id.eq(ticket.status.id))
                .innerJoin(customer).on(customer.id.eq(ticket.customer.id))
                .groupBy(ticket.id, turnRequest.deliveryDate)
                .orderBy(turnRequest.deliveryDate.asc(), turnRequest.id.asc())
                .offset(page*(long)size)
                .limit(size);
        long count = query.fetchCount();
        List<TicketRow> results = new ArrayList<>();
        if (count > 0)
            results = query.fetch();
```
And this is the query generated after `fetch` call:
```sql
select grain3_.name as col_0_0_,
    cast(turnreques0_.delivery_date as char) as col_1_0_,
    ticket1_.id as col_2_0_,
    customer9_.business_name as col_3_0_,
    dealer5_.business_name as col_4_0_,
    zone4_.name as col_5_0_,
    tickettype7_.name as col_6_0_,
    ticketstat8_.name as col_7_0_
from turn_request turnreques0_
    inner join ticket ticket1_ on (ticket1_.id = turnreques0_.ticket_id)
    inner join grain_zone grainzone2_ on (grainzone2_.id = ticket1_.grain_zone_id)
    inner join grain grain3_ on (grain3_.id = grainzone2_.grain_id)
    inner join zone zone4_ on (zone4_.id = grainzone2_.grain_id)
    inner join dealer dealer5_ on (dealer5_.id = ticket1_.dealer_id)
    inner join turn_request_status turnreques6_ on (
        turnreques6_.id = turnreques0_.turn_request_status_id
    )
    inner join ticket_type tickettype7_ on (tickettype7_.id = ticket1_.ticket_type_id)
    inner join ticket_status ticketstat8_ on (ticketstat8_.id = ticket1_.ticket_status_id)
    inner join customer customer9_ on (customer9_.id = ticket1_.customer_id)
group by ticket1_.id,
    turnreques0_.delivery_date,
    grain3_.name,
    cast(turnreques0_.delivery_date as char),
    customer9_.business_name,
    dealer5_.business_name,
    zone4_.name,
    tickettype7_.name,
    ticketstat8_.name,
    turnreques0_.id
order by turnreques0_.delivery_date ASC,
    turnreques0_.id ASC
limit ?
```

For some reason, `group by` sql sentence does not match with the code I wrote in `groupBy` method, it adds more fields than expected. The sql code generated should be:
```sql
group by ticket1_.id,
    turnreques0_.delivery_date
```

**Comment by beikov** [comment]
Hi! This is not "wrong" but is actually what databases usually expect i.e. that you group by all non-aggregate expressions. Some databases support determining that a subset of columns is "enough" for the same cardinality, but most don't support this functional dependence analysis, so these databases would require a full group by clause consisting of all non aggregate expressions contained in the SELECT, ORDER BY and HAVING clauses.

Blaze-Persistence by default generates these group by items as soon as you use an aggregate function or add a custom group by item to match the needs of most databases and make it more convenient for users. In your particular case, the group by items are in fact not necessary if the database supports functional dependency analysis, but we do not yet respect the support of the database during the generation of the group by items.

You can read more about this in the [documentation](https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/#implicit-group-by-generation) and can turn the feature off by setting the following configuration properties to `false`:

* `com.blazebit.persistence.implicit_group_by_from_select`
* `com.blazebit.persistence.implicit_group_by_from_having`
* `com.blazebit.persistence.implicit_group_by_from_order_by`

The configuration properties control whether to generate implicit group by items for the non-aggregate expressions of the respective clause. You should be able to set these properties by adding hints to your `BlazeJPAQuery`. You can refer to these properties through the `ConfigurationProperties` class which exposes fields for the constants.
