### ISSUE TITLE
LTS Java 17 officially support

### ISSUE THREAD

**Issue by boskokg** [Blazebit/blaze-persistence#1388]
I do not see any mentions of compatibility with Java 17.

Can you please tell is LTS Java 17 officially supported?

**Comment by beikov** [comment]
Hi @boskokg,
as of version 1.6.3 we are fully Java 17 compatible as has been fixed by https://github.com/Blazebit/blaze-persistence/issues/1361

**Comment by boskokg** [comment]
Thank you,
Can you please write that in the Documentation [()](https://github.com/Blazebit/blaze-persistence#supported-java-runtimes)
