### ISSUE TITLE
DB2 Express-C for DB2 Tests of blaze-persistence

### ISSUE THREAD

**Issue by cchet** [Blazebit/blaze-persistence#140]
As far as I remember did we talk about testing blaze-persistence on DB2, which seems to be possible because there is an community edition available which should support all necessary db2 specific stuff for testing.
I will install and take a look at it.
Maybe it works for us.
http://www-01.ibm.com/software/data/db2/express-c/download.html

**Comment by beikov** [comment]
This looks just like what we need: https://github.com/angoca/db2-travis
Note that this issue is related to: https://github.com/Blazebit/blaze-persistence/issues/130

**Comment by cchet** [comment]
The installation is the same as with the full licensed DB2. (is a DB2 10.5)

**Comment by beikov** [comment]
I added DB2 9.7 as available from the ubuntu partner packages to the build matrix.
