### ISSUE TITLE
How to use @MappingSubquery in entity views as abstract classes?

### ISSUE THREAD

**Issue by gorkembalcisoy** [Blazebit/blaze-persistence#1403]
### Description
I used entity views as interfaces, but I need @ViewConstructor annotation and change interfaces to abstract classes. But, my @MappingSubquery annotated subqueries do not compile after that.

Exception : No eligible constructor exists for subquery provider in SubqueryProviderHelper.class

### Environment

Version:            
JPA-Provider:       
DBMS:               
Application Server:

**Comment by beikov** [comment]
The exception you are seeing is because inner classes within interfaces are static by default, whereas within classes, they are non-static i.e. capture the instance from within which they were created. Just make the class static and it should work.

**Comment by gorkembalcisoy** [comment]
Thank you
