### ISSUE TITLE
how can I sort  Correlation mapping result

### ISSUE THREAD

**Issue by nmvr2600** [Blazebit/blaze-persistence#1407]
for example: 
`    @Mapping("Person[age IN VIEW(age)]")
    List<PersonView> getSameAgedPersons();`
how can I sort PersonView by some column? I tried use @OrderBy, but it seems that annotation can't work here.
The @Limit can order the result, but I don't want limit the result count.

**Comment by beikov** [comment]
Hi. You can let a collection become sorted by using a `SortedSet` or by supplying a custom Comparator via `@CollectionMapping`. Also see https://persistence.blazebit.com/documentation/1.6/entity-view/manual/en_US/#sorted-collection-mapping

**Comment by nmvr2600** [comment]
all right, I will try that. thx.
