### ISSUE TITLE
Upgrade Blaze Persistence to Quarkus 2.6.1.Final and generate proper metadata

### ISSUE THREAD

**Issue by gsmet** [Blazebit/blaze-persistence#1414]
As seen in https://github.com/quarkusio/quarkus-platform/pull/417, the Blaze Persistence Quarkus extension does not provide all the necessary metadata for modern Quarkus.

Quarkus 2 has been around for a long while now so let's make the extension more modern.

I'm going to work on this.

**Comment by beikov** [comment]
Fixed via https://github.com/Blazebit/blaze-persistence/pull/1416
