### ISSUE TITLE
Stream processing of results not working for entity views

### ISSUE THREAD

**Issue by dsarlo-viso** [Blazebit/blaze-persistence#1421]
### Description
We updated to 1.6.4 because there was a bugfix included for getResultStream() since this was throwing an exception for us earlier on #1393. The fix included in #1394, seems to have introduced this odd behavior. 

### Expected behavior
When using getResultList().stream(), we get the following response:

```
[ {
  "businessUnitId" : null,
  "typeIds" : [ 1 ],
  "presentCount" : 0,
  "validatedCount" : 0,
  "createdDate" : "2022-01-14T15:16:59.905673Z",
  "dataTypeIds" : [ 11 ],
  "rId" : 12601,
  "id" : 1,
  "risk" : "TESTING",
  "riskScore" : 0.36666667,
  "reasonDetail" : "Created",
  "relevantControlCount" : 13,
  "test" : "TESTING",
  "score" : 0.36666667,
  "status" : "TESTING",
  "userId" : 1,
  "userName" : "Test"
}, {
  "businessUnitId" : null,
  "typeIds" : [ 1 ],
  "presentCount" : 0,
  "validatedCount" : 0,
  "createdDate" : "2022-01-14T15:17:22.026997Z",
  "dataTypeIds" : [ 11 ],
  "rId" : 12601,
  "id" : 2,
  "risk" : "TESTING 2",
  "riskScore" : 0.36666667,
  "reasonDetail" : "Modified",
  "relevantControlCount" : 13,
  "test" : "TESTING 2",
  "score" : 0.36666667,
  "status" : "TESTING 2",
  "userId" : 2,
  "userName" : "Test 2"
} ]
```

This is the expected output

### Actual behavior
When using getResultStream(), we get the following response:

```
[ [ 1, null, 1, 0, 0, "2022-01-14T15:16:59.905673Z", 11, 12601, "TESTING", 0.36666667, "Created", 13, "TESTING", 0.36666667, "TESTING", 1, "Test" ], [ 2, null, 1, 0, 0, "2022-01-14T15:17:22.026997Z", 11, 12601, "TESTING 2", 0.36666667, "Modified", 13, "TESTING 2", 0.36666667, "TESTING 2", 2, "Test 2" ] ]
```

### Steps to reproduce
Reproduced in Project: https://github.com/dsarlo-viso/blaze-web-implementation-issues

Just have to hit the following endpoints:
`Create a user POST http://localhost:8080/api/web-mvc`
With the body:
```
{
    "firstName": "Blaze",
    "lastName": "Entity"
}
```
`Get user profiles (ResultStream) GET http://localhost:8080/api/web-flux`
You should see something like this:
```
[
    [
        "cbaec5bb-8641-47f6-8584-cf53e383b325",
        "Test",
        "Test",
        null,
        null,
        null
    ],
    [
        "15c2b3c8-8f3c-4a26-acbe-c9e3d0e6c138",
        "Blaze",
        "Entity",
        null,
        null,
        null
    ]
]
```

### Environment

Version: 1.6.4
JPA-Provider: Hibernate 5.4.32.Final (Spring Data JPA 2.4.13)
DBMS: PostgreSQL 13.3
Application Server: Spring Boot 2.4.13

**Comment by beikov** [comment]
Well, what would you expect here? You are join fetching a collection which increases the cardinality by N for every output object, so real streaming doesn't work. Should this throw an exception or maybe consume the whole stream to produce a correct result? I think an exception might be best here. What do you think?

If you change `UserProfileView` to use any fetch strategy other than JOIN for `links`, it will work

```
@Mapping(fetch = FetchStrategy.MULTISET)
List<LinkView> getLinks();
void setLinks(List<LinkView> links);
```

**Comment by beikov** [comment]
I actually think throwing an exception here is the proper thing to do so a user knows that something has to be changed in order for streaming to work, so I implemented that as part of https://github.com/Blazebit/blaze-persistence/pull/1424
