### ISSUE TITLE
Add #orderById short-cut for paginated queries

### ISSUE THREAD

**Issue by msavy** [Blazebit/blaze-persistence#1439]
## Feature request

When using BlazePersistence with more generic paginated code, it would be quite helpful to have a way to tell BP to just use the unique ID of a given entity as indicated by `@Id` for ordering (i.e. doesn't work properly without a unique #orderBy). Often that's a field called `id` and you can just guess, but not always, and it may be complicated by composite IDs.

I was thinking it could look something like:

```java
 PaginatedCriteriaBuilder<T> cb = criteriaBuilderFactory
                            .create(entityManager, type)
                            .from(type)
						   .where("foo").eq("bar")
						   .orderById(true) // (1)
                            .page(0, 100);
```
(1) ordered by whatever Id is specified in the `@Entity` model.

Edit: I see you already have `PaginatedCriteriaBuilder#getIdentifierExpressions` which can pick these up, so I guess it would be a case of wiring those in

**Comment by beikov** [comment]
I haven't tried this yet, but I think the following could do what you want to achieve:

```java
 PaginatedCriteriaBuilder<T> cb = criteriaBuilderFactory
                            .create(entityManager, type, "alias")
                            .from(type)
						   .where("foo").eq("bar")
						   .orderByDesc("alias")
                            .page(0, 100);
```

**Comment by msavy** [comment]
> I haven't tried this yet, but I think the following could do what you want to achieve:
> 
> ```java
>  PaginatedCriteriaBuilder<T> cb = criteriaBuilderFactory
>                             .create(entityManager, type)
>                             .from(type, "alias")
> 						   .where("foo").eq("bar")
> 						   .orderByDesc("alias")
>                             .page(0, 100);
> ```

Oh, cool! I'll have to give that a try. If it works it might be a nice addition to the docs; I could make a PR for that perhaps.

**Comment by msavy** [comment]
This appears to works well. Had no idea about this shortcut.

Will do a docs PR soon.
