### ISSUE TITLE
getResultList returning a list containing one object of null values rather than an empty list

### ISSUE THREAD

**Issue by dsarlo-viso** [Blazebit/blaze-persistence#1442]
### Description

We are querying for a list of sub views using the function `EntityViewManager.applySetting(EntityViewSetting setting, CriteriaBuilder criteriaBuilder, String entityViewRoot)`. When these sub views exist in the db, we properly receive the results as a list. What we are having trouble with is when there aren't any of these sub views in the db.

What we are doing:
```
 CriteriaBuilder<Link.class> cb = cbf.create(em, Link.class).from(ClientProfile.class);
 cb = cb.where("org.id").eq(orgId);
 CriteriaBuilder<LinkView.class> linkBuilder = evm.applySetting(EntityViewSetting.create(LinkView.class), cb, "links");
 return linkBuilder.getQuery().getResultList();
```

### Expected behavior

Expected result when links exist on a client profile: 
```
[{"url": "value", "name": "value"}]
```

Actual result when links exist on a client profile:
```
[{"url": "value", "name": "value"}]
```

Expected result when links do not exist on a client profile: 
```
[]
```

Actual result when links do not exist on a client profile: 
```
[{"url": "null", "name": "null"}]
```

### Actual behavior

When there are no values in the db for the sub views we query for, we receive a result list with one element with null fields.

### Steps to reproduce

As mentioned above, if we query for a list of sub views and none exist, we should see this behavior.

Provided the setup/query we are doing above.

### Environment

Version: 1.6.5
JPA-Provider: Hibernate 5.4.32.Final (Spring Data JPA 2.4.13)
DBMS: PostgreSQL 13.3
Application Server: Spring Boot 2.4.13

**Comment by beikov** [comment]
Hi, this is expected behavior for so called "flat views" because there is no value that is used to determine nullness in this case. If you were using a proper `@IdMapping` on e.g. `getUrl()`, the result will be empty, just as expected.

**Comment by dsarlo-viso** [comment]
@beikov `Link` is embeddable and embedded in `ClientProfile` so there is no `@IdMapping`. Any advice as to what we should be doing here?

Link Entity:

ClientProfile Entity:
```

**Comment by beikov** [comment]
You could try map it like this to emulate an id over all values.

```java
@EntityView(Link.class)
public interface LinkView extends Id {
    @IdMapping("this")
    @JsonIgnore
    Id getId();

    @EntityView(Link.class)
    public interface Id {
        String getName();
        String getUrl();
    }
}
```

**Comment by dsarlo-viso** [comment]
Did this and changed the UpdateView to match, but I keep getting this exception on startup:

```
Caused by: java.lang.IllegalArgumentException: There are error(s) in entity views!
Invalid id attribute mapping for embeddable entity type 'com.daniel.test.domain.Link' at attribute id[com.daniel.test.view.LinkView.getId] for managed view type 'com.daniel.test.view.LinkView'!
Invalid id attribute mapping for embeddable entity type 'com.daniel.test.domain.Link' at attribute id[com.daniel.test.view.LinkUpdateView.getId] for managed view type 'com.daniel.test.view.LinkUpdateView'!
```

I attempted something similar yesterday without `@JsonIgnore` and received the same exception.

@beikov

**Comment by beikov** [comment]
Unfortunately, the only way to avoid the "empty object" for now, is to use a list index by annotating `@OrderColumn` on the entity collection. A possible alternative is to use a simple wrapper view:

```java
@EntityView(ClientProfile.class)
public interface ClientProfileLinkViews {
    @IdMapping
    Long getId();
    List<LinkView> getLinks();
}
```

```java
 CriteriaBuilder<Link.class> cb = cbf.create(em, Link.class).from(ClientProfile.class);
 cb = cb.where("org.id").eq(orgId);
 CriteriaBuilder<ClientProfileLinkViews> linkBuilder = evm.applySetting(EntityViewSetting.create(ClientProfileLinkViews.class), cb);
 return linkBuilder.getQuery().getResultList().get(0).getLinks();
```

**Comment by dsarlo-viso** [comment]
Thanks for that! Looks like we will need to get the data we want through ClientProfileView instead for now. We do use a list index for links using `@OrderColumn` and that doesn't seem to help in this situation.

**Comment by beikov** [comment]
FYI I'm looking into this as part of https://github.com/Blazebit/blaze-persistence/issues/1593
