### ISSUE TITLE
Path expression colliding with entity name causes errors

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1450]
With the following model:

```java
@Entity(name = "products")
public class Product { ... }
@Entity(name = "suppliers")
public class Supplier {
    @OneToMany
    List<Product> products;
}
```

we run into parsing issues for an expression like `products`, because that is interpreted as `EntityLiteral` instead of as `PathExpression`. We must adapt the parser so that `EntityLiteral` can only be parsed in special cases like `=`/`<>` and `in` predicates.

The workaround is, rename the association or the entity name to avoid running into this.

**Comment by jwgmeligmeyling** [comment]
Isnt this problematic for a full query parser down the road? Would a TYPE(x) IN (A, B, C) be incorrectly treated as paths here? How does JPQL handle this?

**Comment by beikov** [comment]
In HQL, since the query parser has a complete query, it is possible to just look at the type of the LHS expression and determine based on the type whether to parse an identifier as entity literal or path expression.
