### ISSUE TITLE
QueryDSL exists subquery in case when expression doesn't work

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1453]
An expression like the following:

```java
Expressions.cases().when(
JPQLNextExpressions.selectFrom(table).where(predicates).exists()
).then(true).otherwise(false)
```

fails with the error

```
java.lang.IllegalArgumentException: Parameter name "param_1" does not exist
```

Where param_1 seems to be the `true` in the case expression (ParameterManager.satisfyParameter)

**Comment by jordijansen** [comment]
Is there a known workaround for this issue while we wait for 1.6.7?

Im running into this problem now.

**Comment by beikov** [comment]
Yes, you can and should use always use literals for compile time constants:

```java
Expressions.cases().when(
JPQLNextExpressions.selectFrom(table).where(predicates).exists()
).then(JPQLNextExpressions.literal(true)).otherwise(JPQLNextExpressions.literal(false))
```

**Comment by jordijansen** [comment]
Thanks! That worked perfectly. 

Good to know I should use literals. Replacing those where I can :)
