### ISSUE TITLE
Querydsl left join subquery

### ISSUE THREAD

**Issue by gero1992** [Blazebit/blaze-persistence#1455]
Hi there! I’m new to Blaze Persistence and I really like the possibility to join subqueries.
I’m using the querydsl extension and I was wondering is it possible to do something like this: 

`

SELECT
  s.id,
  e_sub.emp_count
FROM
  shop s
  LEFT JOIN
    (SELECT
       e.id  AS emp_id,
       COUNT(e) AS emp_count
  FROM
    employee e
  WHERE
    e.archived = false
    GROUP BY e.id) AS e_sub ON s.id = e_sub.empId

`

**Comment by beikov** [comment]
Hey there, yeah that's easily possible. See the documentation about the features and how to use them: https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/index.html#subquery-joins

**Comment by gero1992** [comment]
Thanks for the quick answer @beikov. Yes I checked the documentation before I created the issue here, but I can't find such example. It's working fine when I select the whole entity, but that's not the case.
Technically I'm trying to join a Tuple and that's causing the issue. I want to perform the aggregate function in the subquery and select the field in the main query.

It looks something like this:
`
QEmployee subEmployee = new QEmployee("subEmployee");

        new BlazeJPAQuery<>(entityManager, criteriaBuilderFactory)
                .select(store, Expressions.numberPath(Long.class, "eCount"))
                .from(store)
                .leftJoin(select(subEmployee.fkStore, subEmployee.count().as("eCount"))
                        .from(subEmployee)
                        .where(subEmployee.archived.eq(false))
                        .groupBy(subEmployee.fkStore),
                        subEmployee)
                .on(store.eq(subEmployee.fkStore))
                .fetch();
`
Which is not compiling, because:

`Cannot resolve method 'leftJoin(com.blazebit.persistence.querydsl.BlazeJPAQuery<com.querydsl.core.Tuple>, com.example.jpa.entity.QEmployee)'`

**Comment by beikov** [comment]
To model this, you need a CTE entity: https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/index.html#common-table-expressions

More info on CTEs here: https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/index.html#ctes

**Comment by gero1992** [comment]
Thank you! Works great 🙏

**Comment by DaiYuANg** [comment]
> Thank you! Works great 🙏

Hello Can you show me the code example, I am in this trouble too, thanks.
