### ISSUE TITLE
In Spring 2.5, a new "deleteAllInBatch(...)" method was added

### ISSUE THREAD

**Issue by corbettcode** [Blazebit/blaze-persistence#1466]
In Spring 2.5, a new "deleteAllInBatch(...)" method was added

	/**
	 * Deletes the given entities in a batch which means it will create a single query. This kind of operation leaves JPAs
	 * first level cache and the database out of sync. Consider flushing the {@link EntityManager} before calling this
	 * method.
	 *
	 * @param entities entities to be deleted. Must not be {@literal null}.
	 * @deprecated Use {@link #deleteAllInBatch(Iterable)} instead.
	 */
	@Deprecated
	default void deleteInBatch(Iterable<T> entities){deleteAllInBatch(entities);}

	/**
	 * Deletes the given entities in a batch which means it will create a single query. This kind of operation leaves JPAs
	 * first level cache and the database out of sync. Consider flushing the {@link EntityManager} before calling this
	 * method.
	 *
	 * @param entities entities to be deleted. Must not be {@literal null}.
	 * @since 2.5
	 */
	void deleteAllInBatch(Iterable<T> entities);

**Comment by beikov** [comment]
You could workaround this in your app for now by delegating to the `deleteInBatch` method which is properly implemented.
