### ISSUE TITLE
Self joining entity delete failing

### ISSUE THREAD

**Issue by StefanDuPreez-dev** [Blazebit/blaze-persistence#1472]
### Description
When we perform a delete on a self-joining entity by using another foreign key, the delete fails because of the foreign key constraint.

### Steps to reproduce
2 entities created with a join from the detail to the header and a self join from the detail to itself
```java
@Entity
@Table(name = "header", schema = "", catalog = "test")
public class HeaderEntity {
    private Integer headerId;
    private Set<HeaderDetailEntity> details = new HashSet<>();

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Id
    @Column(name = "header_id", nullable = false)
    public Integer getHeaderId() {
        return headerId;
    }

    public void setHeaderId(Integer headerId) {
        this.headerId = headerId;
    }

    @OneToMany(fetch = FetchType.LAZY,mappedBy = "header")
    public Set<HeaderDetailEntity> getDetails() {
        return details;
    }

    public void setDetails(Set<HeaderDetailEntity> details) {
        this.details = details;
    }
}
```

```java
@Entity
@Table(name = "header_detail", schema = "", catalog = "test")
public class HeaderDetailEntity {
    private Integer detailId;
    private HeaderEntity header;
    private HeaderDetailEntity parent;
    private Set<HeaderDetailEntity> children = new HashSet<>();

    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Id
    @Column(name = "detail_id", nullable = false)
    public Integer getDetailId() {
        return detailId;
    }

    public void setDetailId(Integer detailId) {
        this.detailId = detailId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "header_id")
    public HeaderEntity getHeader() {
        return header;
    }

    public void setHeader(HeaderEntity header) {
        this.header = header;
    }


    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "parent_detail_id")
    public HeaderDetailEntity getParent() {
        return parent;
    }

    public void setParent(HeaderDetailEntity parent) {
        this.parent = parent;
    }

    @OneToMany(fetch = FetchType.LAZY,mappedBy = "parent")
    public Set<HeaderDetailEntity> getChildren() {
        return children;
    }

    public void setChildren(Set<HeaderDetailEntity> children) {
        this.children = children;
    }
}
```

When running the following code the delete fails because of the foreign key on the parent failing
`DeleteCriteriaBuilder<HeaderDetailEntity> del = config.createCriteriaBuilderFactory().delete(session, HeaderDetailEntity.class)
                .where("header.headerId").eq(1);`

The delete comes out like this
`delete from test.header_detail where header_id = 1`

This is a problem because the database sorts the records by pk and the first record it tries to delete has children records linked to it.

Would it be possible to add an orderBy to the DeleteCriteriaBuilder so the delete can be constructed like
`delete from test.header_detail where header_id = 1 order by detail_id desc`

### Environment
Version: 1.6.6
JPA-Provider: Hibernate 5.4.17.Final  
DBMS: MySQL 8.0.25

**Comment by beikov** [comment]
Unfortunately this is not something that we can meaningfully emulate in other databases which is why I didn't bother to look into this so far. Usually, databases allow to defer constraint checks to the statement or transaction end, but unfortunately MySQL doesn't support that. Either way, deleting in some order is not going to solve this issue in general as you could have cycles.

I understand that MySQL has only this way of handling such situations, so I can offer you a "workaround"/hack for this.

You can introduce a custom function, let's call it `mysql_order`. The function will render a SQL fragment like `1 order by ...` where `...` represent the arguments that are passed to the function. With such a function, you could write a query like this:

```java
DeleteCriteriaBuilder<HeaderDetailEntity> del = config.createCriteriaBuilderFactory().delete(session, HeaderDetailEntity.class) .where("header.headerId").eq(1).where("1").eqExpression("mysql_order(id, 'DESC')");
```

I know it's not pretty from a usage perspective, but if I considered adding support for this, then I would implement it like this behind the scenes.

**Comment by StefanDuPreez-dev** [comment]
That worked like a charm, thank you. Unfortunately, MySQL does not support order by on deletes with joins, so it is not that easy.
I tried using an exists and an in but MySQL also does not allow the table that is being deleted from being in the same query.

This is invalid SQL: 
```SQL
delete from retail.transaction_detail
        where (branch_id, trn_dtl_id) in (select branch_id, trn_dtl_id
                                            from retail.transaction_detail
                                            join retail.transaction_header using (branch_id, trn_hdr_id)
                                         where (branch_id, branch_trade_id) in ((?, ?)))
order by branch_id, trn_dtl_id desc
```
But this is valid
```SQL
delete from retail.transaction_detail
        where (branch_id, trn_dtl_id) in (select * from (select branch_id, trn_dtl_id
                                            from retail.transaction_detail
                                            join retail.transaction_header using (branch_id, trn_hdr_id)
                                         where (branch_id, branch_trade_id) in ((?, ?))) as a)
order by branch_id, trn_dtl_id desc
```

Is there a way to simulate the subquery on another subquery?

**Comment by beikov** [comment]
Not sure if/why you really need to join the same table again, you could just use a query like this:

```
DeleteCriteriaBuilder<TransactionDetail> del = config.createCriteriaBuilderFactory()
.delete(session, TransactionDetail.class, "td") 
.whereExists()
  .from("td.header", "h")
  .where("h.headerId").eq(1)
.end()
.where("1").eqExpression("mysql_order(id, 'DESC')");
```

**Comment by StefanDuPreez-dev** [comment]
I tried that, but failed to realize I was using the target table and not the parent table in the exists clause. Thank you for that.
