### ISSUE TITLE
Hibernate filters are not being used in build-in functions

### ISSUE THREAD

**Issue by nlippke** [Blazebit/blaze-persistence#1499]
### Description
Blaze's built-in functions do not respect hibernate filters.

Example:
```java
@Entity
@FilterDef(name = "genderFilter", defaultCondition = "gender =:gender", parameters = @ParamDef(name = "gender", type = "java.lang.String"))
@Filter(name = "genderFilter")
public class Cat {
   ...
   @ManyToMany
   @Filter(name = "genderFilter")
    private Set<Cat> kittens = new HashSet<>();
   ...
}
```

If you now filter on all cats which have at least 2 female kittens
```java
Filter filter = hibernateSession.enableFilter("genderFilter");
filter.setParameter("gender", "f");

List<Cat> parents = cbf.create(em, Cat.class)
  .from(Cat.class, "cat");
  .where("size(kittens)").gt(1)
  .getResultList();
```

the result list counts also male cats, because

```sql
select *
from Cat cat0_
where cat0_.gender = ?
  and (select count(kittens1_.Cat_id) from Cat_Cat kittens1_ where cat0_.id = kittens1_.Cat_id) > ?
``` 

### Expected behavior
Subquery for size should also filter.

### Actual behavior
Filter is ignored.

### Steps to reproduce
The example is taken form this [Test case]( https://github.com/nlippke/CteTest/blob/9cb842af58b73571b105435e1dc07b6556f7898e/src/test/java/org/example/sample/SampleTest.java#L65)

**Comment by nlippke** [comment]
It turns out that this is even not working in plain JPQL with hibernate. The `size()` function is simply ignoring any filters. A possible workaround is to manually phrase the where-condition.

**Comment by beikov** [comment]
Hey @nlippke, is the size function the only usage that is problematic? I think we might be able to fix/workaround that. I'd be curious though if you can check whether Hibernate 6.1.0.Final has the same problem. I'm just about to finish the integration for that version and might be able to squeeze one more bug fix into the next Hibernate version, in case this is still problematic.

**Comment by nlippke** [comment]
I've checked out hibernate 6.1 and created a test there which passes correctly.

**Comment by beikov** [comment]
Thanks for testing that. One last question, is this only a problem for the size function? Or are there other collection related functions for which you also ran into this problem?

**Comment by nlippke** [comment]
The interesting part of the size function is that it results in an inner query. I am not aware of any other collection based function.
