### ISSUE TITLE
AbstractHibernateEntityManagerFactoryIntegrator  Index 3 out of bounds for length 3

### ISSUE THREAD

**Issue by licunzhi** [Blazebit/blaze-persistence#1519]
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.5.8</version>
        <relativePath/> 
    </parent>

SpringBoot version : 2.5.8

There are some errors in my app:

Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at com.blazebit.persistence.integration.hibernate.base.function.AbstractHibernateEntityManagerFactoryIntegrator.<clinit>(AbstractHibernateEntityManagerFactoryIntegrator.java:93) ~[blaze-persistence-integration-hibernate-base-1.6.6.jar:1.6.6]
	... 42 common frames omitted

I think it might appear in the version on divide operation

![image](https://user-images.githubusercontent.com/25954140/180609259-331388a8-5e22-43ae-b3f7-7f53e19372e7.png)

**Comment by beikov** [comment]
Are you using an uber-jar deployment? In that case you must provide the Hibernate version through a version provider SPI

**Comment by licunzhi** [comment]
> Are you using an uber-jar deployment? In that case you must provide the Hibernate version through a version provider SPI

ok, seems I saw some error messages about uber-jar.  Could pls give some examples or docs about config provider SPI?

**Comment by beikov** [comment]
Here is the SPI you have to implement https://www.javadoc.io/doc/com.blazebit/blaze-persistence-integration-hibernate-base/latest/com/blazebit/persistence/integration/hibernate/base/spi/HibernateVersionProvider.html

You will need a compile dependency on baze-persistence-integration-hibernate-base to see this class though.
