### ISSUE TITLE
BP data 2.4 is no longer compatible with spring boot 2.6.9+

### ISSUE THREAD

**Issue by EugenMayer** [Blazebit/blaze-persistence#1532]
It seems that 2.6.9 underwent a spring boot data minor upgrade, maybe the same one that went into 2.7.x - thus it is broken with bp data 2.4 right now.

to be honest, I am not sure bp should fix that, otherwise, we will need to have 2 different bp data 2.6 versions, one for 2.6.9 and above, and one for below.

It was odd that they upgraded spring boot data within a patch release, AFAIKC it is related to sec fixes

**Comment by beikov** [comment]
Can you give a small clue what is broken for you? I saw that there was an upgrade to Spring Data 2.6.5 but from the [changelog](https://github.com/spring-projects/spring-data-jpa/releases/tag/2.6.5) i can't tell what could have caused any breakage.

**Comment by EugenMayer** [comment]
@beikov do you think you can make this work for 2.6.0-2.6.8 and 2.6.9-2.6.11 at the same time, without releasing to bp data 2.6 versions? seems like this here does not fit your release concept and maybe not worth the effort, IMHO

**Comment by beikov** [comment]
Yeah, it should be possible to support all versions without having multiple integrations :)
