### ISSUE TITLE
GraphQL schema is not generated correcly when MappingSingular is used

### ISSUE THREAD

**Issue by EugenMayer** [Blazebit/blaze-persistence#1539]
When a MappingSingular is used with a Converter, pretty much the same like https://persistence.blazebit.com/documentation/1.6/entity-view/manual/en_US/#singular-collection-type-mappings, the generated GQL view, which has this definition

```
interface MyView {
  @MappingSingular
  Set<String> getBaseDNs();
}
```

While the entity has the following def.

```
class MyClass {
  @Basic
  @Column(columnDefinition = "TEXT")
  @Convert(converter = StringSetToStringConverter.class)
  private Set<String> baseDNs;
}
```

In the GQL schema, the actual type will be `String`, not `List<String>`. The actual GQL fetch value is somewhat a serialized array :
 
```
"baseDNs": "[bar, foo, moo]",
```

We tried this with 1.6.7 and against the current master `382a66cd0`

**Comment by EugenMayer** [comment]
> I was just about to create an issue laughing
> 
> Here is what I wrote so far:
> 
> With the QUERY flush strategy we bind the mapping singular attributes like they are, but Hibernate interprets a parameter that implements `java.util.Collection` as list parameter and expands the collection. We'll need some way to force Hibernate to treat this a singular parameter, e.g. using `TypedParameterValue` or something like that. Maybe a new `JpaProvider` method that binds singular parameters?

you mixed the issue :) - this one is not about hte flush strategy but the GQL part, even though the field is the same

**Comment by beikov** [comment]
Ohh, you are right. Didn't look careful enough. Thanks.
