### ISSUE TITLE
Are mappings with @JoinTable supported ?

### ISSUE THREAD

**Issue by cchet** [Blazebit/blaze-persistence#154]
I have the issue that an mapping is ignored on an entityView which maps an collection of the mapped entity which is mapped via @ManyToMany + @JoinTable. 
I do not see the this mapping in the generated query.

Could it be that this kind of JPA mappingis is not supported ?
If yes why no error or at leat a warning.

**Comment by beikov** [comment]
As it turned out, you forgot the entity view annotation on a subview. This should actually throw an error and should be covered by #142.
