### ISSUE TITLE
FR / Idea: Support sub-data-fetcher in GraphQL for EntityViews

### ISSUE THREAD

**Issue by EugenMayer** [Blazebit/blaze-persistence#1548]
## Motivation

I cases, where an GraphQL response should include a specific EV (which fetches data from the database), but also needs additional fields which cannot be fetched via the database. Areas like 'ldap configuration' loaded from the database, but also the server connection status `connectStatus` which uses the ldap client to test the connection. Via would love to be able to use [sub data fetchers](https://netflix.github.io/dgs/advanced/context-passing/) for that purpose.

## Example

This is the core view

```java
class LdapConfigurationView {
   String hostname;
   Integer port;
}
```

This is the extended view, included a pseudo computed field which does nothing (it's v6ue should be replaced via a sub data fetcher)

```java
class LdapConfigurationWithStatusView {
  default Boolean connectionStatus {
    return null;
  }
}
```

Our graphql queries would look like

```graphqls
    ldapServerConfigurations(
        "Amount of entries per page" first: Int!, "Start element index for the requested page" offset: Int!
    ): LdapConfigurationWithStatusViewConnection!
```

The implementation would be 

```java
// this is where we try to replace the value via a sub fetcher
  @DgsQuery(field = "ldapServerConfigurations")
  public Object getServerConfigurations(DataFetchingEnvironment dfe)
  {
    final var setting =
      graphQLEntityViewSupport.createPaginatedSetting(dfe);

    if (setting.getMaxResults() == 0) {
      return new GraphQLRelayConnection<>(Collections.emptyList());
    }

    return new GraphQLRelayConnection<>(ldapRepository.getServerConfigsPaged(setting));
  }
```

```java
// this is where we try to replace the value via a sub fetcher
@DgsData(parentType = "ldapServerConfigurations", field = "connectionStatus")
Boolean ldapConnectionStatus(DgsDataFetchingEnvironment dfe) {
  LdapConfigurationWithStatusView server = dfe.getSource();
  return ldapService.getStatus(server);
} 
```

While this should theoretically work, e.g. when we use a DTO instead of the the LdapConfigurationWithStatusView view, DGS will properly replace the value via the data-fetcher.

## What we try to improve

If we cannot use data fetchers, we will need to work arround it using

- creating a DTO for the view
- test the DFE configurations for the existince of the 'connectionStatus' field selection

```java
// this is where we try to replace the value via a sub fetcher
  @DgsQuery(field = "ldapServerConfigurations")
  public Object getServerConfigurations(DataFetchingEnvironment dfe)
  {
     final var setting =
      graphQLEntityViewSupport.createPaginatedSetting(dfe);

    List<LdapConfigurationWithStatusView> serverConfigurations =
      ldapRepository.getServerConfigsPaged(setting);
    if (setting.getMaxResults() == 0) {
      return null;
    }

    // since we cannot change fields on the viewImpl (only getters) we need to convert this into a
    // DTO to be able to set our computed status field before we return the response
    var serverListDTO = serverConfigurations.stream().map(x -> {
      var mapped = new LdapServerConfigurationListResponse();
      modelMapper.map(x, mapped);
      return mapped;
    }).toList();

    if (dfe.getSelectionSet().contains("edges/node/connectionStatus")) {
      // if the field is set, we calculate its value
      // this would definitely be the best case for a sub-data-fetcher but at the moment
      // sub-data-fetcher seem not to work, when the model is not defined in the graphql schema file, or it does
      // not work with views (we strongly think it's the second one).
      serverListDTO.forEach(config -> config.setStatus(ldapService.getConnectionStatus(config)));
    }

    return new GraphQLRelayConnection<>(serverListDTO);
  }
```

**Comment by EugenMayer** [comment]
After discussing with @beikov in Zulip he pointed me to an existing implementation

- https://github.com/Blazebit/blaze-persistence/blob/7956aa45921fa4bb9868163939d3af1d88560e2d/examples/spring-data-dgs/src/main/java/com/blazebit/persistence/examples/spring/data/dgs/fetcher/CatGraphQLApi.java#L73
- https://github.com/Blazebit/blaze-persistence/blob/7956aa45921fa4bb9868163939d3af1d88560e2d/examples/spring-data-dgs/src/main/java/com/blazebit/persistence/examples/spring/data/dgs/view/CatWithOwnerView.java#L32

This aims at the exact same thing and seems to work. Possible reasons we have a difference could be

- [ ] error in our implementation
- [ ] a specific name is set via GraphQLName which we do not use (maybe makes a difference in the way gql finds the fields) / schema generation issue
- [ ] we use a list / relay, the implementation here just returns a single entry

**Comment by beikov** [comment]
I just tested the example with 5.2.1 and sub data fetchers are invoked properly, so I assume there is an error in your implementation. You can reopen this issue with a reproducer if you find a bug.
