### ISSUE TITLE
GraphQL example contains invalid code

### ISSUE THREAD

**Issue by david-kubecka** [Blazebit/blaze-persistence#1560]
See https://github.com/Blazebit/blaze-persistence/blob/main/examples/spring-data-graphql/src/main/java/com/blazebit/persistence/examples/spring/data/graphql/view/CatWithOwnerView.java#L38. There a non-existing `GraphQLName` annotation is used (version 1.6.7).

A related question is how one can achieve similar functionality currently (mapping to a different field/type name in the schema).

**Comment by david-kubecka** [comment]
I see that it's actually a new feature in a future 1.6.8 release :-) Any idea when that one might come out?

**Comment by beikov** [comment]
Hey there. I think I will release it this week. I'll ping you here as soon as it's available on Maven Central.

**Comment by david-kubecka** [comment]
Any update on the release date? :-)

**Comment by beikov** [comment]
I didn't forget about pinging, don't worry 😃 

I would like to investigate the reports of the annotation processor getting stuck though before doing the release.

**Comment by beikov** [comment]
Version 1.6.8 was released today: https://persistence.blazebit.com/news/2022/blaze-persistence-1.6.8-release.html

**Comment by david-kubecka** [comment]
That's great news! Finally, I can continue with full BP integration into my project!

Meanwhile, I went through most BP documentation (especially entity views). I see there are a lot of changes in 1.6.8, especially in GraphQL integration so it might be worthwhile to reread that section. Any additional sections you would recommend returning to again?
