### ISSUE TITLE
New BP AP causes compile lockups

### ISSUE THREAD

**Issue by EugenMayer** [Blazebit/blaze-persistence#1567]
Good morning! I have done some tests here. I'am doing all tests in the CI, this means:

100% same jdk and environemnt for all tests
- iam using the exact same code base, just changing the BP version - anything else (without any exception) is the same
- i disabled any pipeline caching so AP runs are always enforced
- iam running the pipeline every full hour (new-bp-ap) and half our (old-bp-ap)

This was leading to the following result, that 
- with the new bp-ap we get the issue that the compile steps looks up and runs for ever, and the pipeline gets killed after 1 hour.
   Yet the lock-up happened 5 times of about 10 runs with the new bp-ap only. 
- With the old AP, it never happened. Wit the old AP we had the issue with the concurrent file writes 2 times, but this is expected and known.

So i would say this fairly proves that it is neither of this causes

- our codebase
- any other dependendcy change
- a JDK issue (we are running the most recent eclipse JDK 17 in the pipeline)

But it is fairly clear the cause of the new AP

**Comment by EugenMayer** [comment]
I did some more testing here using the version e304b2b7c20ea3d3703ef6aed701a121d04d3855 as a base.

We still stuck with the same result means, with e304b2b7c20ea3d3703ef6aed701a121d04d3855 we have no "locking compile issue", bu rather a concurrency issue on 1/5th of all runs. So this means, it is clear that `ad63760f868bc1f5f8c4fe9da830f55e38a2c63e` introduced the issue (which was what we assumed in the initial statement to this issue).

At least we can limit it on that scope alone - but i understand that this is quiet a huge code base change.

For me @beikov it must be something alone those things:

1. thread lock. Are any semaphores used which could result in a dead lock?
2. FileIO lock issue on write

I would say it could be either of thos because:
- when it happens, there is hardly any memory taken up during it getting stuck an on. So there is something dead-on waiting
- it seems like the CPU usage takes on and on while waiting. I assume that more and more threads run into the lock waiting, so we have a huge context-switch overhead and the CPU gets hogged more and more

Yet i could not have it reproduced the way that i can attach a debugger to it, since the CI will not allow me to do that, the box is shut down and i have no access to it.

**Comment by beikov** [comment]
There is no locking issue, otherwise we would be able to see that in the thread dump. The only possible reasons for such a behavior are:

* A bug in javac
* A data race caused by the annotation processor that leads to corrupted internal data structures, leading to some sort of endless loop

**Comment by EugenMayer** [comment]
After i happened to notice that our AP snapshot we based our tests on a build based on the PR here https://github.com/Blazebit/blaze-persistence/pull/1555

When we use this build, we run into the issues above.

Using a build based on on HEAD on main  (https://github.com/Blazebit/blaze-persistence/commit/ad63760f868bc1f5f8c4fe9da830f55e38a2c63e), does no longer show this kind of issues.

I assume this is great! IMHO we can close this issue because the current main build works just fine!

**Comment by beikov** [comment]
Happy to hear that this is not an issue anymore. Hope it doesn't pop up again 🤞
