### ISSUE TITLE
Suppress "unchecked" warnings in generated files

### ISSUE THREAD

**Issue by david-kubecka** [Blazebit/blaze-persistence#1572]
Currently, there's an `addSuppressWarningsAnnotation` option which should suppress warnings in generated code. Unfortunately, it only mentions some of the possible warnings but not the unchecked ones. During compilation, there are then messages like `Some input files use unchecked or unsafe operations.`.

Please add include also `unchecked` in the list of suppressed warnings.

**Comment by beikov** [comment]
Should be pretty easy to fix. Here is the code: https://github.com/Blazebit/blaze-persistence/blob/main/entity-view/processor/src/main/java/com/blazebit/persistence/view/processor/ClassWriter.java#L159

This would be a great first pull request :)

**Comment by david-kubecka** [comment]
PR here: https://github.com/Blazebit/blaze-persistence/pull/1724

**Comment by beikov** [comment]
Fixed via https://github.com/Blazebit/blaze-persistence/pull/1724

Thanks
