### ISSUE TITLE
Custom entity view class fails bytecode analysis when using 2 stack slot types

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#1575]
A simple entity view like the following fails to work because our analysis currently assumes every parameter consumes a single stack slot:

```java
    @EntityView(Document.class)
    static class CustomDocumentView {

        private final long id;
        private final String name;

        public CustomDocumentView(long id, String name) {
            this.id = id;
            this.name = name;
        }

        @IdMapping
        public long getId() {
            return id;
        }

        public String getName() {
            return name;
        }
    }
```

The stack slot of the parameter `name` is 3 instead of 2, which leads to issues in the analysis of the constructor.

**Comment by david-kubecka** [comment]
The issue is flagged with "workaround available" label. Can you please elaborate on the nature of the workaround?

**Comment by beikov** [comment]
The workaround is to not use primitive types. In Kotlin, this probably means using nullable types i.e. `Long?`
