### ISSUE TITLE
EntityView tests : attempted reuse of join table but with different columns

### ISSUE THREAD

**Issue by andyjefferson** [Blazebit/blaze-persistence#159]
If you look at 
https://github.com/Blazebit/blaze-persistence/blob/master/entity-view/testsuite/src/test/java/com/blazebit/persistence/view/entity/Document.java#L173
and
https://github.com/Blazebit/blaze-persistence/blob/master/entity-view/testsuite/src/test/java/com/blazebit/persistence/view/collections/entity/simple/DocumentForCollections.java#L107

you have two attempted uses of a table "personlist". The order column is named each time (consistently), but the FK back to the owner will be "DOCUMENTFORCOLLECTIONS_ID" in the latter and "DOCUMENT_ID" in the former. Suggest that you use a different table name (or fix the inconsistent column names).

I'd also quibble about use of CollectionTable annotation instead of JoinTable (this is not a Basic or Embeddable).

**Comment by beikov** [comment]
Thanks for the pointer regarding the collection table. I just fixed that.

These two entities aren't used in the same persistence unit as far as I can tell so I guess this won't be a problem for DN?

**Comment by andyjefferson** [comment]
Aren't they both in 
https://github.com/Blazebit/blaze-persistence/blob/master/entity-view/testsuite/src/test/resources/META-INF/persistence.xml  ?

All I know is that if I tried to use DN-5 with PostgreSQL with the entity-view/testsuite and run com.blazebit.persistence.view.collections.basic.BasicCollectionsTest as well as com.blazebit.persistence.view.basic.AbstractClassViewTest then I get problems because the schema of one conflicts with the other.

**Comment by beikov** [comment]
Actually the entity manager factory that I am creating is a container entity manager factory. I am providing a PersistenceUnitInfo with the classes that are used for that particular test.
