### ISSUE TITLE
How to integrate Blaze with QueryDSL into the SpringBoot project？

### ISSUE THREAD

**Issue by wsq93** [Blazebit/blaze-persistence#1609]
### Description
When I use QueryDSL5, I find that some methods are marked by @Deprecated, or even invalid. Blaze is mentioned in the description, so I try to integrate Blaze according to the document. However, it will fail at startup.

### Actual behavior

![图片](https://user-images.githubusercontent.com/44887680/198813080-f37815e0-aa4f-4c88-8b84-6678bfd34471.png)
![图片](https://user-images.githubusercontent.com/44887680/198813109-2623112c-de05-4024-a24d-f0eeda9bb1db.png)
![图片](https://user-images.githubusercontent.com/44887680/198813157-25285f10-e5d5-41a4-83b1-5e74e4abcd23.png)
![图片](https://user-images.githubusercontent.com/44887680/198813179-aeca7aeb-4241-4124-ba3b-108d0eae72ec.png)

---

    Caused by: java.lang.ClassNotFoundException: com.blazebit.persistence.impl.function.entity.ValuesEntity

---

### Environment

Version:  1.6.7
JDK17
SpringBoot2.6.13

**Comment by jwgmeligmeyling** [comment]
Try adding:

```
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-core-api-jakarta</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>compile</scope>
</dependency>
<dependency>
    <groupId>com.blazebit</groupId>
    <artifactId>blaze-persistence-core-impl-jakarta</artifactId>
    <version>${blaze-persistence.version}</version>
    <scope>runtime</scope>
</dependency>
```

as dependencies and use the [`jakarta`](https://github.com/querydsl/querydsl/releases/tag/QUERYDSL_5_0_0) classifier for `querydsl-apt`.

You should be able to replace any occurrence of `JPAQueryFactory` with `BlazeJPAQueryFactory` and immediately benefit from all the additional query features.

**Comment by wsq93** [comment]
Encountered a conflict between javax and jakarta. 
![图片](https://user-images.githubusercontent.com/44887680/198827804-ffbf1362-9072-424c-b6f5-3a7c8afe50c5.png)

Maybe I should wait for SpringBoot3.
Thank you!

**Comment by jwgmeligmeyling** [comment]
Both Querydsl and Blaze-Persistence should also work with `javax.persistence.EntityManager` just fine.
