### ISSUE TITLE
left join and fetchPage cause wrong result

### ISSUE THREAD

**Issue by Basil1991** [Blazebit/blaze-persistence#1642]
my env:
spring boot 2.7.5 + jpa +querydsl + blaze-persistence

table 1 t_template:
![image](https://user-images.githubusercontent.com/5119689/203933577-bebb0fec-5605-4259-bb0c-175b493b0170.png)
table 2 t_template_relation:
![image](https://user-images.githubusercontent.com/5119689/203933726-cf1bc02b-1d0f-4ab2-9db8-20d4db16fb49.png)
my code:
![image](https://user-images.githubusercontent.com/5119689/203933854-30b9dea0-d796-44e7-b215-4449e49fb3f8.png)
excution sql:
Hibernate: 
    select
        template0_.id as col_0_0_,
        (select
            count(*) 
        from
            t_template template2_ 
        where
            (
                template2_.deleted=0
            )) as col_1_0_ 
    from
        t_template template0_ 
    left outer join
        t_template_relation templatere1_ 
            on (
                templatere1_.template_id=template0_.id
            ) 
    where
        (
            template0_.deleted=0
        ) 
        and (
            template0_.id in (
                (
                    select
                        * 
                    from
                        ((select
                            template3_.id 
                        from
                            t_template template3_ 
                        where
                            (
                                template3_.deleted=0
                            ) 
                        order by
                            template3_.id DESC limit 1)) tmp)
                )
            ) 
        order by
            template0_.id DESC
----------
question 1: wrong count result . expect 6 but 3

question 2: strange where condition 
 and (
            template0_.id in (
                (
                    select
                        * 
                    from
                        ((select
                            template3_.id 
                        from
                            t_template template3_ 
                        where
                            (
                                template3_.deleted=0
                            ) 
                        order by
                            template3_.id DESC limit 1)) tmp)
                )
            )

**Comment by beikov** [comment]
1) Pagination with `fetchPage` is based on a root identity. If you want to work on result set row level, use the `limit`/`offset` methods instead.
2) The condition you see here is because it paginates based on the root entity. The condition might look odd on some DBMS due to the lack of LIMIT/OFFSET support in Hibernate before 6.1.

**Comment by Basil1991** [comment]
@beikov So how do i get PagedList object without fetchPage method? 
maybe use fetchResults method (@Deprecated)?

**Comment by beikov** [comment]
What is your use case? You want to fetch only the first template_relation for a particular template? If so, you will have to use a subquery and apply the limit in the subquery.

**Comment by Basil1991** [comment]
@beikov 
![image](https://user-images.githubusercontent.com/5119689/203992155-5d09b5a6-b67f-4e59-a1a7-54e92346524c.png)
It is my use case，i just want find way instead of fetchResults method，get pagedResult that included totalCount and List<Model> .

**Comment by beikov** [comment]
There is no way to do this currently with the QueryDSL API. One possible workaround is to make the `templateRelation` the query root i.e.

```java
var result = q.select(template.id)
    .from(templateRelation)
    .rightJoin(template).on(templateRelation.templateId.eq(template.id))
    .orderBy(template.id.desc())
    .fetchPage(0, 1);
```

But your query doesn't make a lot of sense to me, that's why I am asking for your use case. As far as I can see, the following query is equivalent:

```java
var result = q.select(template.id, q.select(count()).from(templateRelation).where(templateRelation.templateId.eq(template.id)))
    .from(template)
    .orderBy(template.id.desc())
    .fetchPage(0, 1);
```


@jwgmeligmeyling: Maybe we should allow creating a `FullQueryBuilder` in `ExtendedFetchable`? Or alternatively expose the `pageBy` API through e.g. `fetchPageBy`?

**Comment by Basil1991** [comment]
@beikov thanks for your reply.
use **querydsl fetchResult method** . I will got two sql
1: List<> query like :
select a.*,b.* 
from template a left join template_relation b on a.id =b.templateid
order by a.id desc
2. count query like:
select count(1)
from template a left join template_relation b on a.id =b.templateid
order by a.id desc
--------------------------
use **querydsl + blaze-persistence fetchPage method** . 
I think i will got one query like:
select a.*,b.*,(**subquery**) as count
from template a left join template_relation b on a.id =b.templateid
order by a.id desc
----------------------------
**It is just a testing, for technology selection**. so the use case has no sense .

**Comment by jwgmeligmeyling** [comment]
I think the Blaze-Persistence just outsmarts your query. You're not actually referencing `templateRelation` in the projection or where clause, so its probably removed from the query when determining the row uniqueness.

If you actually project the entity, I'd expect the result you're expecting (i.e. change `select(template.id)` with `select(template, templateRelation)`).

**Comment by jwgmeligmeyling** [comment]
> @jwgmeligmeyling: Maybe we should allow creating a `FullQueryBuilder` in `ExtendedFetchable`? 

As far as I remember, the issue was that the result of a query is not always a `FullQueryBuilder` (with CTE queries and set operations).

You can however do:

```
BlazeCriteriaBuilderRenderer<T> blazeCriteriaBuilderRenderer = new BlazeCriteriaBuilderRenderer<T>(criteriaBuilderFactory, entityManager, getTemplates());
Queryable<T, ?> queryable = blazeCriteriaBuilderRenderer.render(query);
```

To at least obtain the `Queryable` instance (which could then be cast)

**Comment by jwgmeligmeyling** [comment]
@beikov  so what should we do about the issue?

Expose `getQueryable<X extends Queryable>(builderClass)` in `ExtendedQueryable`?

**Comment by beikov** [comment]
Hmm, I think we should add an API to expose the pageBy stuff and also a way to make entity views easier to use. I guess that this requires some sort of way to create a FullQueryBuilder

**Comment by Basil1991** [comment]
> I think the Blaze-Persistence Core just outsmarts your (invalid) query. You're not actually referencing `templateRelation` in the projection or where clause, so the join is probably removed from the query when determining the row uniqueness.
> 
> If you actually project the entity, I'd expect the result you're expecting (i.e. change `select(template.id)` with `select(template, templateRelation)`).

----------------------
(i.e. change `select(template.id)` with `select(template, templateRelation)`).
It's right .
