### ISSUE TITLE
QueryDSL integration and EntityView

### ISSUE THREAD

**Issue by MaykoST** [Blazebit/blaze-persistence#1643]
Does blaze persistence support the usage of QueryDSL integration with EntityView? 
I looked through all the documentation and examples but I couldn't find it.

**Comment by beikov** [comment]
The integration story here is not perfect yet, but you can use it. 

```
BlazeCriteriaBuilderRenderer<T> blazeCriteriaBuilderRenderer = new BlazeCriteriaBuilderRenderer<T>(criteriaBuilderFactory, entityManager, getTemplates());
CriteriaBuilder<T> queryable = (CriteriaBuilder<T>) blazeCriteriaBuilderRenderer.render(query);

CriteriaBuilder<MyView> cb = evm.applySetting(queryable, EntityViewSetting.create(MyView.class));
```

@jwgmeligmeyling related to https://github.com/Blazebit/blaze-persistence/issues/1642#issuecomment-1327734819

**Comment by MaykoST** [comment]
Wow, what a quick response. Thank you very much and congratulations on the amazing project. I was reading the source code and I thought it was really cool.

**Comment by beikov** [comment]
Thanks. Nice to hear that you like it :)

**Comment by MaykoST** [comment]
I tried to use the example but i think i found a problem

Code:
![image](https://user-images.githubusercontent.com/2073416/204043970-95cc24b1-ab16-4596-a43e-77c736396904.png)

Map:
![image](https://user-images.githubusercontent.com/2073416/204044024-ee3e3b7f-a2df-4b61-b099-d8c35648f1cb.png)

Error:
![image](https://user-images.githubusercontent.com/2073416/204044112-28dc7c99-7ba3-4923-98f0-55332335cc2a.png)

As can be seen in the image the wroing positions are used to access the object in the array. 

My dependencies

querydsl:4.1.4
spring-boot:2.0.0
spring:5.0.4
laze-persistence: 1.6.8

java8
