### ISSUE TITLE
Query some columns (projection) and return the entity itself without using EntityView

### ISSUE THREAD

**Issue by giquieu** [Blazebit/blaze-persistence#1650]
Hello,
I would like to do a search with just a few columns of the entity and return the entity itself, without using EntityView.
I think I would use projections. Below I exemplify the situation
Any suggestions on how to achieve this use case?

Something like:

CriteriaBuilder<Product> cb = criteriaBuilderFactory.create(entityManager, Product.class);

cb.select("value");
cb.select("itens.description");

// If possible...
//cb.select("itens.product.id");

List<Product> list = cb.getResultList();

// Example of access
System.out.println(list.get(0).getItens().get(0).getDescription());

Entity example:
```
@Entity
@Table(name = "product")
class Product {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = true, updatable = false)
    private Long id;

    private String description;
    private BigDecimal value;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "product", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<Item> itens;

    // Get, Set...
} 

@Entity
@Table(name = "item")
class Item {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = true, updatable = false)
    private Long id;

    @JoinColumn(name = "product", nullable = false) 
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    private Product product;

    private String description;
    private  String obs;

    // Get, Set...
} 
```

**Comment by beikov** [comment]
Hi there, you can use something like this:

```java
CriteriaBuilder<Product> cb = criteriaBuilderFactory.create(entityManager, Product.class);

cb.where("value").eq(valueToSearch);
cb.where("itens.description").eq(descriptionToSearch);

cb.where("itens.product.id").eq(productIdToSearch);

List<Product> list = cb.getResultList();
```

Also look into the documentation to see some more examples: https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/#predicate-builder

**Comment by giquieu** [comment]
Okay, thanks for the reply. The library is fantastic, congrats.

What I'm looking for is column selection, returning the entity instead of the Object[] and without needing an EntityView..
Would it currently be possible is there any way to go to achieve this?
Example, please look at the clause in the select:

cb.select("value");
cb.select("itens.description");

// If possible...
//cb.select("itens.product.id");

cb.where("id").eq(1L);

Product product = cb.getSingleResult();

product.getValue(); -- Here is the value, because I used it in the select
product.getDescription() -- Here will be null, because I didn't use it in the select

**Comment by beikov** [comment]
Well, if you want to reduce the amount of data to select you have a few options:

* Use `.select(...)` and live with `Object[]`
* Use entity views
* Use `.selectNew` to construct a custom object

If your concern with entity views is the updatability, note that you can flush back entity views. There is no way to initialize just part of an entity though.

**Comment by giquieu** [comment]
Hello, @beikov 
Thanks for the suggestions.
Using .fetch behaves very similar to what I'm looking for.
Am I using .fetch for the right purpose? Do you think there would be any problems using it?

Example:

Views:
```
@EntityView(ProductView.class)
class ProductView {

    @IdMapping
    Long getId();

    String getDescription();
    BigDecimal getValue();

    List<ItemView> getItens();

} 

@EntityView(Item.class)
class ItemView {

    @IdMapping
    Long getId();

    String getDescription();
    String getObs();

} 
```


Criteria:
```
EntityViewSetting<ProductView, CriteriaBuilder<ProductView>> setting = EntityViewSetting.create(ProductView.class);

// Only desired columns...
setting.fetch("description");
setting.fetch("itens.obs");

CriteriaBuilder<ProductView> evm = entityViewManager.applySetting(setting, cb);

List<ProductView> list = evm.getResultList();
```

The select that is executed, columns that were not selected were executed as _null_:
```
select
	product0_.id as col_0_0_,
	product0_.description as col_1_0_,
	itens1_.id as col_3_0_,
	null as col_4_0_,
	itens1_.obs as col_5_0_,
	null as col_6_0_,
	null as col_7_0_,
	null as col_8_0_,
	null as col_9_0_,
	null as col_10_0_,
	null as col_11_0_
from
	product product0_
	left outer join item itens1_ on product0_.id = itens1_.product
where
	product0_.id = ?
```

**Comment by beikov** [comment]
Yes, if you want just a subset of the entity view to be read, then this is the way to go. The `null` parts might go away in the future: https://github.com/Blazebit/blaze-persistence/issues/1636

**Comment by giquieu** [comment]
@beikov Nice, thanks.

What good news!
I'm investing some time studying the framework, as soon as I feel safe I can try to contribute something... until then I'll follow the subject...

If I may, could I ask one more question, please?

About the OneToMany - ManyToOne relationship, which causes recursion in the mapping.
Example:
```
@EntityView(CoMaster.class)
public interface CoMasterView {
    
    String getIdentification();
    // Details OneToMany
    List<CoDetailView> getDetails();

}
```

```
@EntityView(CoDetail.class)
public interface CoDetailView {

    // Master ManyToOne
    CoMasterView getCoMaster();
    String getStyle();
    String getValue();

}
```

Is there a way to perform this mapping without causing recursion?
I looked here (https://github.com/beikov/bp-945/tree/master/src/main/java/test/view) the possibility of using the strategy of mapping "simple" views... 
Is that the only way possible? Or is there any plan to accept these mappings without causing recursion?

Thanks for your responses.

**Comment by beikov** [comment]
You can use `@Mapping(fetch = FetchType.SELECT)`, but usually there is no need to refer to the "whole" parent (`CoMasterView`) in a child view (`CoDetailView`). Normally, people create a base type:

```java
@EntityView(CoMaster.class)
public interface CoMasterIdView {
    @IdMapping
    String getIdentification();
}
```

and use the `CoMasterIdView` when mapping associations like this:

```java
@EntityView(CoDetail.class)
public interface CoDetailView {
    CoMasterIdView getCoMaster();
    String getStyle();
    String getValue();
}
```

This avoids the cyclic mapping and is usually fine because the "whole" parent (`CoMasterView`) is rarely necessary.

**Comment by giquieu** [comment]
Hello @beikov , thanks for the replies.
I added as an annotation on the List<> property and the cyclic mapping error still exists.
Something I didn't do?

```
@EntityView(CoMaster.class)
public interface CoMasterIdView {
    @IdMapping
    String getIdentification();

    @Mapping(fetch = FetchType.SELECT)
    List<CoDetailView> itens;
}
```

For now I'm mapping as per your suggestion to use the base type.

**Comment by beikov** [comment]
This is the full mapping that avoids the cycle which should work:

```java
@EntityView(CoMaster.class)
public interface CoMasterIdView {
    @IdMapping
    String getIdentification();
}
@EntityView(CoMaster.class)
public interface CoMasterView extends CoMasterIdView {
    // Details OneToMany
    List<CoDetailView> getDetails();
}
@EntityView(CoDetail.class)
public interface CoDetailView {
    CoMasterIdView getCoMaster();
    String getStyle();
    String getValue();
}
```

Please post the error you get when using `@Mapping(fetch = FetchType.SELECT)`.
