### ISSUE TITLE
CriteriaBuilderConfigurationImpl Exception

### ISSUE THREAD

**Issue by jacopotorrini** [Blazebit/blaze-persistence#1693]
### Description

Using an EntityManager with Blazebit persistence v.1.6.8 configured with jakarta and hibernate-6.0+ I have this error:
ava.lang.AbstractMethodError: Receiver class com.blazebit.persistence.impl.CriteriaBuilderConfigurationImpl does not define or inherit an implementation of the resolved method 'abstract com.blazebit.persistence.CriteriaBuilderFactory createCriteriaBuilderFactory(jakarta.persistence.EntityManagerFactory)' of interface com.blazebit.persistence.spi.CriteriaBuilderConfiguration.

Looking into blazebit code bytecode of CriteriaBuilderConfigurationImpl doesn't match with source code. The decompiled version uses javax EntityManagerFactory insted of jakarta one.

### Environment

 Version:            1.6.8
JPA-Provider:       Hibernate 6.1.1.Final		-->
DBMS:               HSQLDB

**Comment by beikov** [comment]
Hello, there are special jakarta artifacts all with the artifact id suffixed with `-jakarta`. Also see https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/#maven-setup
