### ISSUE TITLE
Create an integration dependency for quarkus 3

### ISSUE THREAD

**Issue by Pilpin** [Blazebit/blaze-persistence#1725]
Hello, 

The dependency com.blazebit:blaze-persistence-integration-quarkus relies on java ee and therefore does not work with quarkus 3.0.0.CR2.
Quarkus 3.0.0.Final is getting really close to being released, do you think a possible blaze-persistence-integration-quarkus-jakarta will be released soon as well ?

Thank you.

**Comment by beikov** [comment]
Thanks for bringing this up. This depends on completing the Hibernate 6.2 integration though. I have been working hard on fixing some issues that popped up in Hibernate while testing, but it took a bit longer than I expected. Anyway, this will be done "soonish" as lots of people are already waiting for this :)

**Comment by Pilpin** [comment]
Hello,

I'm wondering if I should wait for this or try and go back to quarkus 2.x, would you have an approximate ETA for 1.6.9 ?

Thank you !

**Comment by beikov** [comment]
I just finished fixing the Hibernate issues I mentioned before. I suspect that I can continue working on the Hibernate 6.2 integration next week. If everything goes smooth, I estimate 2-3 weeks until this done.

**Comment by RustamSultansoy** [comment]
any updates here?

**Comment by beikov** [comment]
Yeah, the integration is done. We are waiting for the new Hibernate 6.2.4 release and for Quarkus to update to that. You can play around with this by building the following PR if you want: https://github.com/Blazebit/blaze-persistence/pull/1718

**Comment by RustamSultansoy** [comment]
> Yeah, the integration is done. We are waiting for the new Hibernate 6.2.4 release and for Quarkus to update to that. You can play around with this by building the following PR if you want: #1718

@beikov it seems that they don't plan to update in upcoming 3.1 version (it's only in CR status). should we wait more or we can somehow upgrade hibernate version in current project by ourselves and start to use your lib?

**Comment by beikov** [comment]
I don't have a definitive answer yet, but I think that Quarkus will upgrade Hibernate soon. Tomorrow Hibernate 6.2.4 will be released. Soon after, I expect that https://github.com/quarkusio/quarkus/pull/33498 will bump to that version and will be merged. So maybe next week there should be a Quarkus version against which we can release.

The new integration is mostly usable with the current Quarkus 3.1.0 as well if you want to play around with it, but I wouldn't recommend this yet for production use until Quarkus upgrades to Hibernate 6.2.4.

**Comment by Sanne** [comment]
The Hibernate upgrade got merged in Quarkus mainline, so the next Quarkus release will have it.

**Comment by beikov** [comment]
Fixed via https://github.com/Blazebit/blaze-persistence/pull/1718

**Comment by famod** [comment]
@beikov great to see this merged!

Looking at the open issues for 1.6.9 is a bit daunting: https://github.com/Blazebit/blaze-persistence/milestone/32
Are you really going to tackle all these before releasing 1.6.9?
Asking because I started to migrate my Q2 app a few weeks ago and had to stop because of this issue.

**Comment by beikov** [comment]
I'll be moving some of the issues to 1.6.10. I'm mostly waiting for @EugenMayer at this point to finish off the Spring Boot 3 integration effort he started. Until he is done, I'll be working on some of the issues currently scheduled for 1.6.9, but I guess I will set a hard deadline for a release by the end of next week.

**Comment by Pilpin** [comment]
Hello, any news on a deadline for 1.6.9 ? Thank you !
