### ISSUE TITLE
EntityView limit mapping creates ParsingException

### ISSUE THREAD

**Issue by Pilpin** [Blazebit/blaze-persistence#1756]
### Description
Hello, I'm trying to collect only some entities from a collection so I decided to try the `@Limit` annotation but I get a `ParsingException`

Here is what the entities and views look like
```
@Entity
public class TraitementAnticoagulantEntity {
    @Id
    private Long id;
    [...]
    @OneToMany(mappedBy="traitement")
    private Set<TraitementAnticoagulantStatutEntity > statuts;
}

@Entity
public class TraitementAnticoagulantStatutEntity {
    @Id
    private Long id;
    [...]
    @ManyToOne
    private TraitementAnticoagulantEntity traitement;
}
```
```
@EntityView(TraitementAnticoagulantEntity .class)
public interface TraitementAnticoagulantView {
    @IdMapping
    Long getId();

    @Mapping("statuts")
    @Limit(limit = "5", order = {"date ASC", "id DESC"})
    SortedSet<TraitementAnticoagulantStatutView> getStatutsForInitial();
}

@EntityView(TraitementAnticoagulantStatutEntity.class)
public interface TraitementAnticoagulantStatutView extends Comparable<TraitementAnticoagulantStatutView > {
    @IdMapping
    Long getId();
    [...]
}
```

### Expected behavior
It works and returns the proper subcollection.

### Actual behavior
Character 726 is right before the second "LIMIT 5", so I guess the limit part is parsed twice.
 `org.hibernate.query.sqm.ParsingException: line 1:726 no viable alternative at input`
```
SELECT 1 FROM TraitementAnticoagulantEntity traitementAnticoagulantEntity LEFT JOIN TraitementAnticoagulantStatutEntity correlated_ext_statutsForInitial ON (1=1) WHERE (SELECT correlated_statutsForInitial.date, correlated_statutsForInitial.finTheorique, correlated_statutsForInitial.id, correlated_statutsForInitial.motif, correlated_statutsForInitial.note, correlated_statutsForInitial.traitement.id, correlated_statutsForInitial.type, correlated_statutsForInitial.version FROM TraitementAnticoagulantStatutEntity correlated_statutsForInitial WHERE correlated_statutsForInitial.traitement = traitementAnticoagulantEntity ORDER BY correlated_statutsForInitial.date ASC NULLS LAST, correlated_statutsForInitial.id DESC LIMIT 5 LIMIT 5) is not null
```

### Steps to reproduce
I can create a test case if needed.

### Environment
Quarkus 3.2.0
Hibernate 6.2.5
Blaze 1.6.9
PostgreSQL 15.0

**Comment by Pilpin** [comment]
I just "played around" with the debugger an I'm pretty sure it happens in `com.blazebit.persistence.impl.AbstractCommonQueryBuilder` when building a "lateral base query string" the function `applyJpaLimit` is called twice:
- the first time in `buildBaseQueryString0` line 3868 (this function is called from `buildBaseQueryString` which itself is called from `buildLateralBaseQueryString`) https://github.com/Blazebit/blaze-persistence/blob/c3cab22c10a76420e5e13f033c1f9cb469673043/core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java#L3868
- and once again in `buildLateralBaseQueryString` line 3750.
https://github.com/Blazebit/blaze-persistence/blob/c3cab22c10a76420e5e13f033c1f9cb469673043/core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java#L3750

**Perhaps the line 3867 is the culprit**, is it missing parentheses ?
https://github.com/Blazebit/blaze-persistence/blob/c3cab22c10a76420e5e13f033c1f9cb469673043/core/impl/src/main/java/com/blazebit/persistence/impl/AbstractCommonQueryBuilder.java#L3867
In my case `externalRepresentation = false `, `(!isMainQuery || countWrapped) = true`, `!isMainQuery && mainQuery.jpaProvider.supportsSubqueryLimitOffset() = true` which makes the whole condition = `true `(`false && true || true`).

Would this make sense instead ? So that when `externalRepresentation` is `false` the whole condition is false as well ?
```
if (externalRepresentation && ( (!isMainQuery || countWrapped) || !isMainQuery && mainQuery.jpaProvider.supportsSubqueryLimitOffset() ) ) { 
```

Thanks

**Comment by beikov** [comment]
Thanks for the bug report. I didn't dig into this yet, but maybe you can try providing a PR with a fix so we can see if it breaks any other tests?
From a quick look, the call to `applyJpaLimit` in `buildLateralBaseQueryString` might simply be wrong, so I'd suggest trying to just remove that call.

**Comment by Pilpin** [comment]
Here is the pull request https://github.com/Blazebit/blaze-persistence/pull/1764

**Comment by Pilpin** [comment]
Hello,

Do you have an ETA for 1.6.10 ? If not, would you consider releasing a "1.6.9.1" kind of version with this fix ?

Thanks

**Comment by beikov** [comment]
Thanks for pinging me. I'll try to squeeze in a release tomorrow with this fix.

**Comment by beikov** [comment]
Sorry for the delay, I'm planning to do the release this week

**Comment by Pilpin** [comment]
Great, thanks !
