### ISSUE TITLE
Allow a subview to be annotated with  @Limit when limit=1

### ISSUE THREAD

**Issue by Pilpin** [Blazebit/blaze-persistence#1757]
Hello,

It would be really cool to be able to map a view directly from a collection when using  `@Limit(limit= "1")`
```
@Mapping("things")
@Limit(limit = "1", order = {"date ASC", "id DESC"})
SomeView getThing();
```

Would it be possible ?

Thank you.

**Comment by beikov** [comment]
Does that not work? It should. What error do you get?

**Comment by Pilpin** [comment]
I think you're right, sorry about this, I misunderstood another exception.
I can't really test it out right now because of #1756 but I'm pretty sure I was wrong
