### ISSUE TITLE
Entity with `@Any`-mapped interface field in Hibernate 6 causes exception during Blaze configuration

### ISSUE THREAD

**Issue by ryanlarkin** [Blazebit/blaze-persistence#1758]
### Description
With Hibernate 6, `@Any`-mapped interface fields cause exception when calling `CriteriaBuilderConfiguration.createCriteriaBuilderFactory()`. Doing this would work in Hibernate 5.6 using Blaze 1.6.9.

### Expected behavior
`CriteriaBuilderConfiguration.createCriteriaBuilderFactory()` succeeds.

### Actual behavior
Hibernate throws `java.lang.IllegalArgumentException: Not a managed type`. E.g.:
```
java.lang.IllegalArgumentException: Not a managed type: interface org.hibernate.tutorial.em.Property
	at org.hibernate.metamodel.model.domain.internal.JpaMetamodelImpl.managedType(JpaMetamodelImpl.java:192)
	at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.managedType(MappingMetamodelImpl.java:467)
	at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.managedType(MappingMetamodelImpl.java:97)
	at com.blazebit.persistence.impl.EntityMetamodelImpl.discoverEnumTypes(EntityMetamodelImpl.java:309)
	at com.blazebit.persistence.impl.EntityMetamodelImpl.collectColumnNames(EntityMetamodelImpl.java:409)
	at com.blazebit.persistence.impl.EntityMetamodelImpl.<init>(EntityMetamodelImpl.java:127)
	at com.blazebit.persistence.impl.CriteriaBuilderFactoryImpl.<init>(CriteriaBuilderFactoryImpl.java:110)
	at com.blazebit.persistence.impl.CriteriaBuilderConfigurationImpl.createCriteriaBuilderFactory(CriteriaBuilderConfigurationImpl.java:2078)
	...
```

### Steps to reproduce

Add `Property`, its implementations, and `PropertyHolder` from [the Hibernate User Guide section on using `@Any`](https://docs.jboss.org/hibernate/orm/6.2/userguide/html_single/Hibernate_User_Guide.html#associations-any-property):
```Java
public interface Property<T> {
    String getName();
    T getValue();
}


@Entity
@Table(name="integer_property")
public class IntegerProperty implements Property<Integer> {
    @Id
    private Long id;

    @Column(name = "`name`")
    private String name;

    @Column(name = "`value`")
    private Integer value;

    @Override
    public String getName() {
        return name;
    }

    @Override
    public Integer getValue() {
        return value;
    }

    //Getters and setters omitted for brevity
}


@Entity
@Table(name="string_property")
public class StringProperty implements Property<String> {

    @Id
    private Long id;

    @Column(name = "`name`")
    private String name;

    @Column(name = "`value`")
    private String value;

    @Override
    public String getName() {
        return name;
    }

    @Override
    public String getValue() {
        return value;
    }

    //Getters and setters omitted for brevity
}
```

```Java
@Entity
@Table(name = "property_holder")
public class PropertyHolder {

    @Id
    private Long id;

    @Any
    @AnyDiscriminator(DiscriminatorType.STRING)
    @AnyDiscriminatorValue(discriminator = "S", entity = StringProperty.class)
    @AnyDiscriminatorValue(discriminator = "I", entity = IntegerProperty.class)
    @AnyKeyJavaClass(Long.class)
    @Column(name = "property_type")
    @JoinColumn(name = "property_id")
    private Property property;

    //Getters and setters are omitted for brevity

}
```
The test in [blaze-persistence-repro](https://github.com/ryanlarkin/blaze-persistence-repro) reproduces the error. See [592b715](https://github.com/ryanlarkin/blaze-persistence-repro/commit/592b7158d9743d722f8b95b1007dd944f88cf20e) for the `Property` and `PropertyHolder` additions that cause the failure

### Environment

Version:            1.6.9
JPA-Provider:       Hibernate 5.2.5.Final
DBMS:               H2 2.1.210
Application Server: N/A

### Notes

In Hibernate 5.6, `ManagedType.getAttributes()` of `PropertyHolder` did not include `PropertyHolder#property`. However the behaviour changed starting in Hibernate 6.0: [18a5248#L507-R512](https://github.com/hibernate/hibernate-orm/commit/18a52483ef6c8dd99a8e8499df59ad4ae38d66cb#diff-16e6d3e8450829e9b077f8b4ace8d630ae0a0faa56094f88f759a9ba6584b339L507-R512). When Blaze iterates through the attributes, it calls [`Metamodel.managedType( fieldType )`](https://github.com/Blazebit/blaze-persistence/blob/c3cab22c10a76420e5e13f033c1f9cb469673043/core/impl/src/main/java/com/blazebit/persistence/impl/EntityMetamodelImpl.java#L309C91-L309C122), but `fieldType` is the `Property` interface, resulting in an exception.

**Comment by Mobe91** [comment]
@tapegram Can you create a custom release of blaze-persistence with the fix of #1763 yourself to get unblocked as long as the PR is not merged? 

I think you should be able to create a custom release by running
```
mvn -P "blazebit-release,h2,hibernate-5.6,deltaspike-1.9,spring-data-2.7.x,deploy-xs2r-gitlab" release:clean release:prepare release:perform "-Darguments=-DskipTests -DskipITs '-DdeployAtEnd=false' '-Djdk8.home=<path-to-jdk8-home>'"
```
To release to a private repository you need to add repo authentication information to your Maven settings.xml
```xml
<settings>
  <servers>
	<server>
      <id>sonatype-nexus-snapshots</id>
      <configuration>
        <!-- configure authentication depending on your private repository -->
      </configuration>
    </server>
	<server>
      <id>sonatype-nexus-staging</id>
      <configuration>
        <!-- configure authentication depending on your private repository -->
      </configuration>
    </server>
  </servers>
</settings>
```
