### ISSUE TITLE
Limited subquery in case when results in parser exception with Hibernate 6

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#1771]
### Description

The following query works with Blaze-Persistence 1.6.9 and Hibernate 5.6.x but fails with a Hibernate parser exception when Hibernate 6 is used:
```java
CriteriaBuilder<Tuple> criteria = cbf.create(em, Tuple.class)
            .from(Document.class, "d")
            .selectCase()
            .whenSubquery().from(Document.class).select("1").setMaxResults(1).end().gtExpression("2")
            .thenExpression("TRUE")
            .otherwiseExpression("FALSE");
        criteria.getResultList();
```
Originally, I thought that this is just a Hibernate bug. However, running the following HQL fails in both Hibernate 5.6.x and Hibernate 6 with a parser exception:
```java
entityManager.createQuery("""
    SELECT CASE WHEN (SELECT 1 FROM Document dSub LIMIT 1) THEN TRUE ELSE FALSE END FROM Document d
""", Boolean.class).getResultList();
```
So I suppose that there is something in Blaze-Persistence that makes this work for Hibernate 5.6.x and it does not work for Hibernate 6.

### Expected behavior
The CriteriaBuilder query shown above works for both Hibernate 5.6.x and Hibernate 6.

### Actual behavior
The CriteriaBuilder query shown above works for Hibernate 5.6.x but not for Hibernate 6.

### Steps to reproduce
Will create a PR with a test case.

**Comment by beikov** [comment]
This is just a bad query. A limit without an order by makes no sense in subqueries, which is why ORM 6 does not support this anymore. Just add `order by dSub.id`
