### ISSUE TITLE
WhereOrBuilder.isEmpty() throws ClassCastException

### ISSUE THREAD

**Issue by QStormDS** [Blazebit/blaze-persistence#1776]
### Description
The construct
WhereOrBuilder<CriteriaBuilder<IViewEntity>>.where("columnName").isEmpty().endOr();
results in an ClassCastException since the update to spring 3.1 and blaze 1.6.9

Please find attacht a fully working demo that shows the issue.

### Expected behavior
.isEmpty() should filter all empty values.

### Actual behavior
java.lang.ClassCastException: class org.hibernate.query.sqm.tree.domain.SqmBasicValuedSimplePath cannot be cast to class org.hibernate.query.sqm.tree.domain.SqmPluralValuedSimplePath

### Steps to reproduce
- Download the attached demo
- Start the demo
- See the exception

### Environment
Version:            1.6.9				
JPA-Provider:       Hibernate 6.2.6.Final	
DBMS:               any			
Application Server: Java SE					

         
[isEmptyIssue.zip](https://github.com/Blazebit/blaze-persistence/files/12236837/isEmptyIssue.zip)

**Comment by beikov** [comment]
In your sample, `columnName`/`idContainer` refers to a basic attribute, but the `is empty` predicate is only supported for plural attributes. The exception by Hibernate could be improved, but if you want to check for an empty string you should rather use:

```
.where("length(idContainer)").eqLiteral(0)
```

Can you check what SQL the previous Hibernate version generated? I'd be curious if it might be appropriate to open a Hibernate JIRA ticket for this, to either improve the error message or add support for this sort of usage.

**Comment by QStormDS** [comment]
Hi, thanks for the explanation. 

Here is the SQL generated by Hibernate 5.6.10.Final:

`    select
        count(jpamydatae0_.id) as col_0_0_,
        jpamydatae0_.data_type as col_1_0_ 
    from
        mydata jpamydatae0_ 
    where
        not (exists (select
            jpamydatae0_.id 
        from
            mydata jpamydatae0_)) 
    group by
        jpamydatae0_.data_type`

**Comment by beikov** [comment]
Well, this query makes no sense whatsoever, so it wasn't "working" before in ORM 5 😄 
The solution I proposed will work with every ORM version.
