### ISSUE TITLE
How to integrate in the SpringBoot3.0.x project?

### ISSUE THREAD

**Issue by wsq93** [Blazebit/blaze-persistence#1786]
# Description

Projects that use SpringBoot version 3.1.2 can be launched. 
However, the SpringBoot version 3.0.9 project cannot be launched.

# SpringBoot3.1.2

## SQL
---
    CREATE TABLE IF NOT EXISTS sys_user (
      id bigserial PRIMARY KEY,
      create_time timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
      edit_time timestamp with time zone NOT NULL,
      enabled boolean NOT NULL DEFAULT false,
      password varchar(255) NOT NULL,
      username varchar(50) NOT NULL,
      account_non_expired boolean DEFAULT false,
      account_non_locked boolean DEFAULT false,
      credentials_non_expired boolean DEFAULT false,
      UNIQUE (username)
    );
    
    CREATE TABLE IF NOT EXISTS sys_role (
      id bigserial PRIMARY KEY,
      code varchar(80) NOT NULL DEFAULT '',
      rolename varchar(50) NOT NULL DEFAULT '',
      UNIQUE(code)
    );
    
    CREATE TABLE IF NOT EXISTS sys_user_role (
     user_id bigint NOT NULL,
     role_id bigint NOT NULL,
     PRIMARY KEY(user_id,role_id),
     FOREIGN KEY (role_id) REFERENCES sys_role(id) ON DELETE CASCADE ON UPDATE CASCADE ,
     FOREIGN KEY (user_id) REFERENCES sys_user(id) ON DELETE CASCADE ON UPDATE CASCADE
    );
---

## Code

pom.xml
----
    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
        <modelVersion>4.0.0</modelVersion>
        <parent>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-parent</artifactId>
            <version>3.1.2</version>
            <relativePath />
        </parent>
        <groupId>com.study</groupId>
        <artifactId>demo-blazebit</artifactId>
        <version>0.0.1</version>
        <properties>
            <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
            <maven.compiler.source>17</maven.compiler.source>
            <maven.compiler.target>17</maven.compiler.target>
            <blaze-persistence.version>1.6.9</blaze-persistence.version>
        </properties>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-web</artifactId>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-data-jpa</artifactId>
            </dependency>
            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
            </dependency>
            <dependency>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-jpa</artifactId>
                <version>${querydsl.version}</version>
                <classifier>jakarta</classifier>
            </dependency>
            <dependency>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-apt</artifactId>
                <version>${querydsl.version}</version>
                <scope>provided</scope>
                <optional>true</optional>
                <classifier>jakarta</classifier>
            </dependency>
            <dependency>
                <groupId>com.blazebit</groupId>
                <artifactId>blaze-persistence-core-api-jakarta</artifactId>
                <version>${blaze-persistence.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>com.blazebit</groupId>
                <artifactId>blaze-persistence-core-impl-jakarta</artifactId>
                <version>${blaze-persistence.version}</version>
                <scope>runtime</scope>
            </dependency>
            <dependency>
                <groupId>com.blazebit</groupId>
                <artifactId>blaze-persistence-integration-hibernate-6.2</artifactId>
                <version>${blaze-persistence.version}</version>
                <scope>runtime</scope>
            </dependency>
            <dependency>
                <groupId>com.blazebit</groupId>
                <artifactId>blaze-persistence-integration-querydsl-expressions-jakarta</artifactId>
                <version>${blaze-persistence.version}</version>
                <scope>compile</scope>
            </dependency>
        </dependencies>
    </project>
----

AppBlazebit.java
----
    package com.study;

    import org.springframework.boot.SpringApplication;
    import org.springframework.boot.autoconfigure.SpringBootApplication;
    
    @SpringBootApplication
    public class AppBlazebit {
	    
	    public static void main(String[] args) {
		    SpringApplication.run(AppBlazebit.class, args);
	    }
    }
----

application.yml
----
    server:
      port: 80
    spring:
      datasource:
        url: jdbc:postgresql://localhost:5432/testdb
        driverClassName: org.postgresql.Driver
        username: test
        password: 123456
----

BlazePersistenceConfiguration.java
----
    package com.study.config;
    
    import org.springframework.context.annotation.Bean;
    import org.springframework.context.annotation.Configuration;
    
    import com.blazebit.persistence.Criteria;
    import com.blazebit.persistence.querydsl.BlazeJPAQueryFactory;
    import com.blazebit.persistence.spi.CriteriaBuilderConfiguration;
    
    import jakarta.persistence.EntityManager;
    import jakarta.persistence.EntityManagerFactory;
    
    @Configuration
    public class BlazePersistenceConfiguration {
	    @Bean
	    public BlazeJPAQueryFactory createBlazeJPAQuery(EntityManager em, EntityManagerFactory entityManagerFactory) {
		    CriteriaBuilderConfiguration config = Criteria.getDefault();
		    return new BlazeJPAQueryFactory(em, config.createCriteriaBuilderFactory(entityManagerFactory));
	    }
    }
----

IndexController.java
----
    package com.study.controller;
    
    import java.util.ArrayList;
    import java.util.List;
    
    import org.springframework.beans.factory.annotation.Autowired;
    import org.springframework.web.bind.annotation.GetMapping;
    import org.springframework.web.bind.annotation.RestController;
    
    import com.blazebit.persistence.querydsl.BlazeJPAQueryFactory;
    import com.study.entity.QSysUser;
    import com.study.entity.SysRole;
    import com.study.entity.SysUser;
    import com.study.model.UserModel;
    
    @RestController
    public class IndexController {
	    @Autowired
	    private BlazeJPAQueryFactory queryFactory;
    
	    @GetMapping("/list")
	    public List<UserModel> getList() {
		    List<UserModel> result = new ArrayList<>();
		    
		    QSysUser qsu = QSysUser.sysUser;
		    List<SysUser> all = queryFactory.selectFrom(qsu).fetch();
		    
		    for (SysUser e : all) {
			    UserModel model = new UserModel();
			    model.setName(e.getUsername());
			    model.setTime(e.getCreateTime().toString());
			    for (SysRole r : e.getRoles()) {
				    model.getRoles().add(r.getRolename());
			    }
			    result.add(model);
		    }
		    return result;
	    }
    }
----

UserModel.java
----
    package com.study.model;
    
    import java.util.ArrayList;
    import java.util.List;
    
    public class UserModel {
	    private String name;
	    private String time;
	    private List<String> roles = new ArrayList<>();
          // getter、setter
    }
----
SysUser.java
----
    package com.study.entity;
    
    import java.io.Serializable;
    import java.time.LocalDateTime;
    import java.util.List;
    
    import jakarta.persistence.CascadeType;
    import jakarta.persistence.Column;
    import jakarta.persistence.Entity;
    import jakarta.persistence.FetchType;
    import jakarta.persistence.GeneratedValue;
    import jakarta.persistence.GenerationType;
    import jakarta.persistence.Id;
    import jakarta.persistence.Inheritance;
    import jakarta.persistence.InheritanceType;
    import jakarta.persistence.JoinColumn;
    import jakarta.persistence.JoinTable;
    import jakarta.persistence.ManyToMany;
    import jakarta.persistence.Table;
    
    @Table
    @Entity
    @Inheritance(strategy = InheritanceType.JOINED)
    public class SysUser implements Serializable {
	    private static final long serialVersionUID = 1L;
	    @Id
	    @GeneratedValue(strategy = GenerationType.IDENTITY)
	    private long id;
	    @Column(nullable = false)
	    private LocalDateTime createTime;
	    @Column(nullable = false)
	    private LocalDateTime editTime;
	    @Column(nullable = false)
	    private boolean enabled;
	    @Column(nullable = false)
	    private String username;
	    @Column(nullable = false)
	    private String password;
	    @Column(nullable = false)
	    private boolean accountNonExpired;
	    @Column(nullable = false)
	    private boolean accountNonLocked;
	    @Column(nullable = false)
	    private boolean credentialsNonExpired;
	    @ManyToMany(cascade = { CascadeType.REFRESH }, fetch = FetchType.EAGER)
	    @JoinTable(name = "sys_user_role", 
		    joinColumns = @JoinColumn(name = "user_id", referencedColumnName = "id"), 
		    inverseJoinColumns = @JoinColumn(name = "role_id", referencedColumnName = "id"))
	    private List<SysRole> roles;
          // getter、setter
    }
----
SysRole.java
----
    @Table
    @Entity
    public class SysRole implements Serializable {
	    private static final long serialVersionUID = 1L;
	    @Id
	    @GeneratedValue(strategy = GenerationType.IDENTITY)
	    private Long id;
	    @Column(nullable = false)
	    private String rolename;
	    @Column(nullable = false)
	    private String code;
	    @ManyToMany(cascade = { CascadeType.MERGE }, fetch = FetchType.EAGER)
	    @JoinTable(name = "sys_user_role", 
		    joinColumns = @JoinColumn(name = "role_id", referencedColumnName = "id"), 
		    inverseJoinColumns = @JoinColumn(name = "user_id", referencedColumnName = "id"))
	    private List<SysUser> users;
          // ...
    }
----

## Situation

This project can be launched and accessed through website http://localhost/list.

# SpringBoot3.0.9

## Code
pom.xml
----
    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
        <modelVersion>4.0.0</modelVersion>
        <parent>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-parent</artifactId>
            <version>3.0.9</version>
            <relativePath />
        </parent>
        <groupId>com.study</groupId>
        <artifactId>demo-blazebit</artifactId>
        <version>0.0.1</version>
        <properties>
            <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
            <maven.compiler.source>17</maven.compiler.source>
            <maven.compiler.target>17</maven.compiler.target>
            <blaze-persistence.version>1.6.8</blaze-persistence.version>
        </properties>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-web</artifactId>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-data-jpa</artifactId>
            </dependency>
            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
            </dependency>
            <dependency>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-jpa</artifactId>
                <version>${querydsl.version}</version>
                <classifier>jakarta</classifier>
            </dependency>
            <dependency>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-apt</artifactId>
                <version>${querydsl.version}</version>
                <scope>provided</scope>
                <optional>true</optional>
                <classifier>jakarta</classifier>
            </dependency>
            <dependency>
                <groupId>com.blazebit</groupId>
                <artifactId>blaze-persistence-core-api-jakarta</artifactId>
                <version>${blaze-persistence.version}</version>
                <scope>compile</scope>
            </dependency>
            <dependency>
                <groupId>com.blazebit</groupId>
                <artifactId>blaze-persistence-core-impl-jakarta</artifactId>
                <version>${blaze-persistence.version}</version>
                <scope>runtime</scope>
            </dependency>
            <dependency>
                <groupId>com.blazebit</groupId>
                <artifactId>blaze-persistence-integration-hibernate-5.6-jakarta</artifactId>
                <version>${blaze-persistence.version}</version>
                <scope>runtime</scope>
            </dependency>
            <dependency>
                <groupId>com.blazebit</groupId>
                <artifactId>blaze-persistence-integration-querydsl-expressions-jakarta</artifactId>
                <version>${blaze-persistence.version}</version>
                <scope>compile</scope>
            </dependency>
        </dependencies>
    </project>
----

## Situation

![image](https://github.com/Blazebit/blaze-persistence/assets/44887680/a30e0bc5-a657-4ec9-b8da-a620a71dc14a)

**Comment by beikov** [comment]
Spring Boot 3.0 is not supported because the Blaze-Persistence integration for Hibernate 6 requires at least version 6.2.
Since Spring only supports the latest minor version, you should be upgrading to Spring Boot 3.1 anyway.

**Comment by wsq93** [comment]
Thanks！
