### ISSUE TITLE
An error occurred in the case expression

### ISSUE THREAD

**Issue by wsq93** [Blazebit/blaze-persistence#1795]
I seem to have written in the wrong place

https://github.com/querydsl/querydsl/issues/3573

**Comment by jwgmeligmeyling** [comment]
Well the error comes from Hibernate and not Querydsl nor Blaze-Persistence 🤷🏻 

I believe type inference of parameters inside case statements has always been problematic in Hibernate. Try wrapping the numbers in a `JPQLNextExpressions.literal(value)` to force literal rendering.

**Comment by wsq93** [comment]
Ok, thanks! 
Perhaps I have found out how to handle it：
----
    result = queryFactory.select(
						new CaseBuilder()
							.when(qod.dist.sum().intValue().eq(JPQLNextExpressions.literal(0)))
							.then(1)
							.when(qod.dist.sum().intValue().eq(qod.need.sum().intValue()))
							.then(2)
							.otherwise(0)
					)
					.from(qod)
					.where(qod.code.eq(no))
					.fetchFirst();
----
