### ISSUE TITLE
Polymorphism-aware entity view validation

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#180]
In the following entity view scenario, the view validation fails because AbstractOffer does have a mapped property 'foo'.

``` java
@EntityView(AbstractOffer.class)
public interface ProductVariantOfferView {
   public Boolean getFoo();
}
```

``` java
@Entity
public class AbstractOffer { }
```

``` java
@Entity
public class WebShopOffer extends AbstractOffer { }
```

``` java
@Entity
public class PhysicalShopOffer extends AbstractOffer {
   private boolean foo;

   public Boolean getFoo() {
        return foo;
    }

    public void setFoo(Boolean foo) {
        this.foo = foo;
    }
}
```

**Comment by beikov** [comment]
I think the only good way to support this kind of mapping would be to implement it with the ```TREAT``` operator(https://github.com/Blazebit/blaze-persistence/issues/120). You would have a mapping like ```@Mapping("TREAT(this AS PhysicalShopOffer).foo")``` which would also require the introduction of an implicit **this** alias.

**Comment by beikov** [comment]
Superseded by #312
