### ISSUE TITLE
Question: Spring Data 3.1 Jakarta Jpa Repository + EntitySpecification + Paging + Entity Graph

### ISSUE THREAD

**Issue by thejeff77** [Blazebit/blaze-persistence#1815]
### Description
Question about default JpaRepository methods available via spring extensions.

Hey guys, I'm new to Blaze Persistence. I can see that the spring 3.1 support is relatively new, and I'm trying to solve an issue I'm having by integrating with your library. I want to do it optimally, so thus this question. 

First, here's the issue I'm trying to solve:

(kotlin)

Here's my code with Vanilla spring data. As you can see, I'm trying to get Pageable working with an Entity Graph and Entity Specification. 
```
@Repository
interface CustomJpaRepository :
    JpaRepository<CustomEntity, UUID>,
    JpaSpecificationExecutor<CustomEntity> {

    @EntityGraph("CustomEntity.oneToManyChild")
    override fun findAll(spec: Specification<CustomEntity>, pageable: Pageable): Page<CustomEntity>
}
```

Unfortunately, this _**breaks**_ because it paginates in-memory. I have this setting enabled for efficiency:   `spring.jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch=false`

This won't paginate efficiently...

I know I can do this with your Criteria API, however it adds a whole lot of code....

Are there any extension methods for a JpaRepository that allow a findAll with the combo of these 3 with Blaze? I.E. a Jpa Repository interface or something? Or my ability to specify EntityGraph as a parameter instead of an annotation?

I wanted to ask this before re-writing all of this with the CriteriaApi and bloating code more than possibly necessary.

Thanks for any help/clarification!

**Comment by beikov** [comment]
You're probably just missing an annotation. You have to replace your `@EnableRepositories` annotation with `@EnableBlazeRepositories` or if you want to work with both the Spring Data JPA repositories and Blaze-Persistence repositories, then you have to split your repositories into different packages and apply the `basePackage` setting respectively. Also see https://persistence.blazebit.com/documentation/1.6/entity-view/manual/en_US/index.html#spring-data-setup

**Comment by thejeff77** [comment]
@beikov thanks, I've added the annotation and still don't see much difference. It seems to me that Blaze Persistence doesn't extend a typical JpaRepository, is that correct? I'd have to define another EntityView and EntityViewSpecification for that EntityView, then specify this under basePackages and use it separately?

**Comment by thejeff77** [comment]
Trying to build a view in kotlin... 

```
@EntityView(CustomEntity::class)
interface CustomView {
    @get:IdMapping
    val id: UUID
}
```

seems to have issues:

```
Caused by: java.lang.IllegalArgumentException: Unknown managed type 'com.missionlane.payments.model.view.CustomView'
	at com.blazebit.persistence.impl.EntityMetamodelImpl.getEntry(EntityMetamodelImpl.java:691)
	at com.blazebit.persistence.impl.EntityMetamodelImpl.getManagedType(EntityMetamodelImpl.java:671)
	at com.blazebit.persistence.spring.data.impl.repository.BlazePersistenceRepositoryFactory.getRepositoryBaseClass(BlazePersistenceRepositoryFactory.java:257)
	at com.blazebit.persistence.spring.data.impl.repository.BlazePersistenceRepositoryFactory.lambda$getRepositoryInformation$2(BlazePersistenceRepositoryFactory.java:523)
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330)
	at com.blazebit.persistence.spring.data.impl.repository.BlazePersistenceRepositoryFactory.getRepositoryInformation(BlazePersistenceRepositoryFactory.java:521)
	at com.blazebit.persistence.spring.data.impl.repository.BlazePersistenceRepositoryFactory.getRepository(BlazePersistenceRepositoryFactory.java:425)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:279)
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:245)
	at org.springframework.data.util.Lazy.get(Lazy.java:114)
```

Sorry to be a pain, suggestions welcome though. Thanks for any reply.

**Comment by beikov** [comment]
You can try playing around with one of the quickstarts to figure out what you might be missing: https://github.com/Blazebit/blaze-persistence#quickstart

The error you just posted looks to me as if you were trying to setup a `JpaRepository` with entity views. If you want some convenience methods, you can use the `EntityViewRepository` interface, but note that if you want to implement `JpaRepository`, you still have to pass the entity type as type variable when implementing the interface.

**Comment by thejeff77** [comment]
[demo 4.zip](https://github.com/Blazebit/blaze-persistence/files/13120195/demo.4.zip)

I used the quickstart to generate a project, then used that template to create a kotlin project with my setup to see if I could reproduce the issue.

This example project showcases the issue: 

```
Caused by: java.lang.IllegalArgumentException: Unknown managed type 'com.example.demo.view.CatSimpleView'
	at com.blazebit.persistence.impl.EntityMetamodelImpl.getEntry(EntityMetamodelImpl.java:691) ~[blaze-persistence-core-impl-jakarta-1.6.9.jar:1.6.9]
```

I don't know if its because of the kotlin code, or because we also have jpa repositories enabled alongside in separate packages or what's going on. 

Make sure to run `./build_db_container.sh` to start the db (docker required)

**Comment by beikov** [comment]
From a quick look at the project, you should remove the bean for `EntityViewConfiguration` in `RepoConfig` i.e.

```
    @Bean
    fun entityViewConfiguration(): EntityViewConfiguration = EntityViews.createDefaultConfiguration()
```

**Comment by beikov** [comment]
The `@EnableEntityViews` annotation takes care of producing the bean. See https://persistence.blazebit.com/documentation/1.6/entity-view/manual/en_US/index.html#anchor-environment-spring

**Comment by thejeff77** [comment]
@beikov thank you! That fixed it in the demo but somehow not in my main app.. sorry that's a bit confusing, the IDE thinks that one wasn't defined. Curious why autoconfig doesn't setup the other beans by default via @ConditionalOnMissingBean annotation/autoconfig. This would simplify setup, andwould be a non-breaking change.

Thank you very much for your timely replies :)

**Comment by beikov** [comment]
It just never occurred to me that we could use conditional beans. Would be great if you could contribute that 😀

**Comment by thejeff77** [comment]
Definitely might.. if I can get it working and used in production I'll have a vested interest in keeping this working and easy to use. Now the demo isn't useful in reproducing my issue so I'll have to bang my head on the wall a while longer. Thanks again for help so far @beikov

**Comment by thejeff77** [comment]
I fixed it, a dumb typo as usual. Thanks again for the help.
