### ISSUE TITLE
Is there a way to change it to use the DBMS default sort?

### ISSUE THREAD

**Issue by zhanglc** [Blazebit/blaze-persistence#1825]
I noticed this quote [here](https://staging-persistence.blazebit.com/documentation/1.6/core/manual/en_US/#anchor-order-by-clause):

> Also note that by default, Blaze Persistence chose to use the NULLS LAST behavior instead of relying on the DBMS default, in order to provide better portability. It is strongly advised to always define the null precedence in order to get deterministic results.

Is there a way to change it to use the DBMS default sort?

we use: `blaze-persistence-core-api 1.6.9` and `querydsl 5.0` , and init by follow:

```java
    @Bean
    public BlazeJPAQueryFactory blazeJPAQueryFactory(EntityManager entityManager,
            CriteriaBuilderFactory criteriaBuilderFactory) {
        return new BlazeJPAQueryFactory(entityManager, criteriaBuilderFactory);
    }
```

thanks a lot.

**Comment by beikov** [comment]
Hi! There is no option to change the default. That default is encoded into the implementation on purpose, for exactly the reason that you quoted, so that you choose a null precedence that fits your needs :)

**Comment by zhanglc** [comment]
> Hi! There is no option to change the default. That default is encoded into the implementation on purpose, for exactly the reason that you quoted, so that you choose a null precedence that fits your needs :)

@beikov how to choose null precedence ?

**Comment by beikov** [comment]
You just add a second argument to `orderByAsc` or `orderByDesc` that specifies whether nulls should be first/last.

**Comment by zhanglc** [comment]
Thanks for the reply, is there no way to remove `nulls first` / `nulls last` with the current version ?

**Comment by beikov** [comment]
The only way to not render `null first` / `nulls last` in the resulting SQL is by using the same null precedence as the underlying database.

**Comment by beikov** [comment]
It is correct that Blaze-Persistence will always generate proper HQL that includes either `null first` or `nulls last` if the expression you order by is nullable. This shouldn't be a problem though if the null ordering you use matches the database default. I don't know which database you use, but e.g. H2 and MySQL treat `null` as the smallest element, so when you sort ascending, then `nulls first` is the default and for descending sorting, `nulls last` is the default. PostgreSQL and Oracle for example behave the other way around. There `nulls last` is the default for `asc` and `nulls first` the default for `desc`. Just match the default.

**Comment by zhanglc** [comment]
@beikov thanks a lot .
We use PostgreSQL , It works well as change the code to the ones you've hinted. 

Thanks a lot.
