### ISSUE TITLE
Warning like "Could not register the function xxx"

### ISSUE THREAD

**Issue by MindaDai** [Blazebit/blaze-persistence#1841]
Version:       1.6.10     
JPA-Provider:       5.6.15
DBMS:      MySql 5.7         
Application Server:  SpringBoot 2.7.17

![image](https://github.com/Blazebit/blaze-persistence/assets/50040676/a25371db-ffba-4184-844d-204c5994ab8a)

What is the problem? Does it affect normal use?

**Comment by beikov** [comment]
If you don't use these functions, then you don't have to worry about this. You should migrate to MySQL 8 though since 5.7 is not supported anymore AFAIK.

**Comment by MindaDai** [comment]
Ok,thanks!
