### ISSUE TITLE
EntityView calls method Assert.notNull(Object object) that was removed in SpringFramework 6.1.x

### ISSUE THREAD

**Issue by kokykolin** [Blazebit/blaze-persistence#1853]
The application crashes at initialization because the called method `void org.springframework.util.Assert.notNull(java.lang.Object)` is not found. This method was deprecated in May 2023, it was previously deprecated and the fact that it will be removed was also announced in the commentary. See the [commit](https://github.com/spring-projects/spring-framework/commit/7df2e2a8d2a845984cde806232181da486dcf7bd#diff-b2576ffd19482927c3f26b1d182f0d95332a6ab46e9ccf3118cebad4138bba9d).

The error is:
```
Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.blazebit.persistence.integration.view.spring.impl.AnnotationEntityViewConfigurationSource.<init>(AnnotationEntityViewConfigurationSource.java:58)

The following method did not exist:

    'void org.springframework.util.Assert.notNull(java.lang.Object)'
```

The places where the deleted method is called:
[AnnotationEntityViewConfigurationSource](https://github.com/Blazebit/blaze-persistence/blob/47915f4fc9f5c55950ef4be391e4288194f7fa8d/integration/entity-view-spring/src/main/java/com/blazebit/persistence/integration/view/spring/impl/AnnotationEntityViewConfigurationSource.java#L58C1-L60C40)
[EntityViewComponentProvider](https://github.com/Blazebit/blaze-persistence/blob/47915f4fc9f5c55950ef4be391e4288194f7fa8d/integration/entity-view-spring/src/main/java/com/blazebit/persistence/integration/view/spring/impl/EntityViewComponentProvider.java#L41)

**Comment by kokykolin** [comment]
> Please upgrade to 1.6.11 - this issue has been already solved IMHO.

The mentioned problem was simulated on version 1.6.11, I expected it to be solved in this version, but unfortunately it wasn't.

**Comment by EugenMayer** [comment]
Be sure you updated properly. We are using 1.6.11 with spring boot 3.2.1 and we do not run in any issues. Please post you dependency tree here and your dependency declaration for reference. We might find the cause there

**Comment by kokykolin** [comment]
> Be sure you updated properly. We are using 1.6.11 with spring boot 3.2.1 and we do not run in any issues. Please post you dependency tree here and your dependency declaration for reference. We might find the cause there

Thank you, here is our dependecy tree [dt_blaze-persistence_issue_1853.txt](https://github.com/Blazebit/blaze-persistence/files/13938717/dt_blaze-persistence_issue_1853.txt)

**Comment by EugenMayer** [comment]
you are using the wrong dependency for [entity-view-spring](com.blazebit:blaze-persistence-integration-entity-view-spring) .. it should be com.blazebit:blaze-persistence-integration-entity-view-spring-6.0

**Comment by kokykolin** [comment]
> you are using the wrong dependency for entity-view-spring .. it should be com.blazebit:blaze-persistence-integration-entity-view-spring-6.0

Solved, thank you! 🙏
