### ISSUE TITLE
Transform SIZE in where clause to COUNT in having clause

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#188]
Instead of creating a subquery for the SIZE function when appearing in the where clause, we can transform it into 
- A newly generated JOIN node
- GROUP BY parent JOIN node
- and replace the SIZE with a COUNT(newAlias) in the having clause 

as long as there are no group bys present.

Multiple SIZE usages require to use COUNT(DISTINCT newAlias) which is not possible for some DBs when the relation uses a composite id.

This tranformation should be deactivatable via a property.

**Comment by beikov** [comment]
Just as a side note, this issue is about composite ids and count: https://hibernate.atlassian.net/browse/HHH-11042
I found a solution that should work in general which we could also apply here. Maybe we also need a property for switching between strict ansi sql and non-strict.

**Comment by beikov** [comment]
The tuple count distinct emulation is implemented now.

**Comment by beikov** [comment]
Currently SIZE in the WHERE clause gets passed through unmodified for the JPA provider to handle.
In the HAVING clause, it gets rewritten to COUNT_TUPLE although I am not sure if this is correct how it is done right now. More tests are required for the HAVING clause usage. Especially a test that asserts the cases when the SIZE must be rewritten to a subquery.

Note that the use of SIZE in GROUP BY is currently not possible because of #195 
When SIZE is used in the ON clause, it must always be rewritten to a subquery. This must be properly tested.

**Comment by Mobe91** [comment]
The transformation of SIZE to subqueries in ON clauses is covered by the tests already.

**Comment by beikov** [comment]
As this transformation oftentimes requires the addition of a select item and grouping by all select items, I decided to not implement this as the performance is probably way worse than using a subquery.
