### ISSUE TITLE
By default, when using a "LIKE" query, the "ESCAPE" string is automatically concatenated.

### ISSUE THREAD

**Issue by CraKeyBoy** [Blazebit/blaze-persistence#1880]
### Description

I use ClickHouse as a database and employ Blaze-Persistence for dynamic querying. Starting from version 1.6.9, Blaze-Persistence automatically concatenates the statement "ESCAPE ''" when performing a "LIKE" query by default. However, this causes an error in ClickHouse because ClickHouse does not support appending "ESCAPE" after a "LIKE" query. Could you please help me with resolving this error? Additionally, I would like to know why it is necessary to concatenate the statement "ESCAPE ''".

I have already located the source code for the following class: "ResolvingQueryGenerator ".
Line 753 ~ 762
```
        if (predicate.getEscapeCharacter() != null) {
            sb.append(" ESCAPE ");
            if (predicate.getEscapeCharacter() instanceof StringLiteral) {
                TypeUtils.STRING_CONVERTER.appendTo(escapeCharacter(((StringLiteral) predicate.getEscapeCharacter()).getValue().charAt(0)), sb);
            } else {
                predicate.getEscapeCharacter().accept(this);
            }
        } else if (!externalRepresentation && !jpaProvider.supportsLikePatternEscape() && predicate.getEscapeCharacter() == null && (dbmsDialect.getDefaultEscapeCharacter()) != null) {
            sb.append(" ESCAPE ''");
        }
```

### Expected behavior

cb.where("s.name").like().value("%" + request.getUserName() + "%").noEscape();

```
 like '%xxx%' 
```

### Actual behavior

cb.where("s.name").like().value("%" + request.getUserName() + "%").noEscape();

```
 like '%xxx%'   ESCAPE ''
```

### Steps to reproduce

Just use a like query and look the query sql.

### Environment
Version: 1.6.11
Spring Boot: 2.3.12
JPA-Provider: Hibernate 5.4.32.Final
DBMS: clickhouse use mysql8 DbmsDialect
Application Server: N/A

**Comment by beikov** [comment]
Hi there. The code that you reference is for rendering the HQL fragment that is passed to Hibernate ORM. You can of course create a custom `DbmsDialect` that extends `MySQLDbmsDialect` and override the `getDefaultEscapeCharacter()` method to return `null` instead. This should allow you to workaround this problem.
Note that Clickhouse is not "supported" i.e. we don't regularly test with it or have a `DbmsDialect` implementation. Hibernate ORM also has no "support" for that database, so you might run into other issues. If you care about that database, please consider contributing support for it.

**Comment by beikov** [comment]
Also see [the documentation](https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/index.html#configuration-dbms-dialects) that explains a bit about `DbmsDialect`.

**Comment by CraKeyBoy** [comment]
OK，I use this method。thx。
