### ISSUE TITLE
Inconsistent behavior when fetching entity view subset with attribute filter

### ISSUE THREAD

**Issue by billysoderlund** [Blazebit/blaze-persistence#1889]
### Description

This is probably a bug, but the fix may not be what I am looking for. Nevertheless, right now it is inconsistent.

I have created a custom attribute filter provider where I am trying to filter the entity view based on if it contains certain sub views. I am also using the EntityViewSetting to only fetch a subset of the view.

### Expected behavior

I expect to get all persons that has kitten with id 1 and 4 and then a sub view list of all kittens no matter the id.

### Actual behavior

What happens is that the kitten sub view list also gets filtered and only returns kitten with id 1 and 4.

The weird thing here is if I would add another fetch for a sub view it all works as I expect.

### Steps to reproduce

Here is a demo. I have added two actions to the sample controller, "/owner" and "/owner/subset". The owner endpoint will filter the top view and include all kittens and puppies. The subset endpoint will filter both the top view and sub view.

[demo.zip](https://github.com/Blazebit/blaze-persistence/files/14996518/demo.zip)

### Environment

Version: 1.6.11
JPA-Provider: Spring Data JPA
DBMS: MySQL
Application Server: Spring Boot

**Comment by beikov** [comment]
Hi and thanks for providing a sample app for demonstration purposes. I think what you are roughly looking for is #109, but I haven't given that a lot of thought yet. Your example of trying to refer to sub-attribute filters within the collection element type is another dimension to this problem e.g. `addAttributeFilter("kittens.id", Arrays.asList(1L, 4L))`.

Usually, the type of a filter value must match the model type. In your example, you expect that filter values also support collections, which I guess is reasonable, given that you're trying to filter something within a collection.

I would recommend you to create a custom attribute filter on the collection attribute itself. In the custom implementation you can then create an exists subquery to avoid the filtering and implement your quantifier logic as you wish.

If you have any ideas on how Blaze-Persistence can provide this out of the box, please share your thoughts on #109
