### ISSUE TITLE
Exclude Certain Attributes in View

### ISSUE THREAD

**Issue by morphace** [Blazebit/blaze-persistence#1916]
Hi,

Is there a possibility to explicitly exclude the fetching of certain attributes in the views (@EntityView)?

The background of my question is that I have different views for different purposes that implement different interfaces, but stem from the same entity class. For optimisation purposes, in some cases, I'd like to avoid the fetching of certain related entities, which would otherwise be fetched, as the interface defines it.

Kind regards,
Markus

**Comment by beikov** [comment]
You can do that, but you will have to specify everything that you want to fetch. Also see https://persistence.blazebit.com/documentation/1.6/entity-view/manual/en_US/index.html#fetching-a-data-subset

**Comment by morphace** [comment]
Cool, exactly what I need!
