### ISSUE TITLE
Is there any way to use @Limit dynamically

### ISSUE THREAD

**Issue by shopera007** [Blazebit/blaze-persistence#1941]
Hello, 
How can I set a dynamic limit using the @Limit annotation in Blaze-Persistence when retrieving for example top-ranked answers for product questions in an entity view: 

Here i want 5 to be dynamic like passing it when constructing the query 

```
   @Limit(limit = "5", order = {"helpfulCount desc"})
        List<ProductAnswerView> answers,
```

Could you please help me out ?

**Comment by beikov** [comment]
Hi, you can use a parameter in the string e.g. `@Limit(limit = ":answerLimit", order = {"helpfulCount desc"})` and bind that parameter on `EntityViewSetting` with `addOptionalParameter("answerLimit", 5)`
