### ISSUE TITLE
sql bug

### ISSUE THREAD

**Issue by srx5223113** [Blazebit/blaze-persistence#1955]
I use where clauss
 ".where("sex").eq("1") .whereOr().whereAnd.where("id").eq("11").where("name").eq("tom").endAnd.where("code").eq("code1").endOr". The sql should be express as “ sex=1 and ((id=11 and name=tom)  or code=code1)。but actually is “sex=1 and (id=11 and name=tom  or code=code1)”。 Is it a bug?

**Comment by srx5223113** [comment]
but the root predicater of cb's where manager seems right.

**Comment by beikov** [comment]
The predicate you're seeing is correct. Hibernate ORM simplifies parenthesis. Since `and` binds stronger than `or` there is no need to put parenthesis around the `id=11 and name=tom` part.
