### ISSUE TITLE
Criteria Builder, aggregate function BOOL_OR automatically added to the GROUP BY clause

### ISSUE THREAD

**Issue by AlekseiPana** [Blazebit/blaze-persistence#1968]
### Description

While constructing a criteria with the usage of BOOL_OR, this aggregation also automatically added to the GROUP BY part of the query. This causes an error as "aggregate functions are not allowed in GROUP BY".
I've tried other aggregate functions like MAX or SUM - no issues there.
As there is a workaround - transform boolean true and false to 1 and 0 and use max, this it not critical for me, but still feel like this is an error that should be reported.

### Expected behavior
By using aggregate function BOOL_OR I've expected for it to not be added to a GROUP BY clause and cause an error in an SQL.
### Actual behavior

Given a simple criteriaBuilder:

```
CriteriaBuilder<Tuple> criteriaBuilder = criteriaBuilderFactory.create(entityManager, Tuple.class)
                .from(WatchlistMainEntity.class)
                .select("watchlistId")
                .select("SUM(CASE WHEN isActive = TRUE THEN recordCount ELSE 0 END)")
                .select("MAX(case WHEN isActive = TRUE THEN versionMajor ELSE 0 END)")
                .select("BOOL_OR(isActive)")
                .where("isProcessed").eq(true)
                .where("deletedAt").isNull()
                .orderByAsc("id");
```

the resulting query (using criteriaBuilder.getQueryString()) was like this:
```
SELECT
   watchlistId_1,
   SUM(
   CASE
      WHEN
         watchlistMainEntity.isActive = true 
      THEN
         watchlistMainEntity.recordCount 
      ELSE
         0 
   END
), MAX(
   CASE
      WHEN
         watchlistMainEntity.isActive = true 
      THEN
         watchlistMainEntity.versionMajor 
      ELSE
         0 
   END
), bool_or(watchlistMainEntity.isActive) 
FROM
   WatchlistMainEntity watchlistMainEntity 
   JOIN
      watchlistMainEntity.watchlistId watchlistId_1 
WHERE
   watchlistMainEntity.isProcessed = :param_0 
   AND watchlistMainEntity.deletedAt IS NULL 
GROUP BY
   watchlistId_1.code, watchlistId_1.dictionaryRegister.id, watchlistId_1.id, watchlistId_1.name, bool_or(watchlistMainEntity.isActive), watchlistMainEntity.id 
ORDER BY
   watchlistMainEntity.id ASC
```

Version:            
JPA-Provider: Hibernate 6.5.3.Final 
DBMS: PostgreSQL 17.0           
Application Server: Java SE

**Comment by beikov** [comment]
[Implicit group by generation](https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/index.html#implicit-group-by-generation) happens automatically when using an aggregate function.
The problem is that you didn't register the `bool_or` function as aggregate function. You can do that as described in the [docs](https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/index.html#custom-jpql-functions) by specifying the `JpqlFunctionKind` for `JpqlFunctionGroup`.

**Comment by jwgmeligmeyling** [comment]
Maybe you can use Blaze-Persistence internal [`OR_AGG`](https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/#window-functions) function instead, which already should be registered as aggregate function by default.

**Comment by AlekseiPana** [comment]
@beikov @jwgmeligmeyling thank you both for your suggestions.
OR_AGG was the most straightforward approach, I've decided to use it for now.
Registering functions is quite convenient if one want to create a custom function, thanks a lot, it will most certainly come in handy.
