### ISSUE TITLE
Custom Repository Implementations

### ISSUE THREAD

**Issue by billysoderlundext** [Blazebit/blaze-persistence#1969]
Does Blaze repositories support custom repositories like Spring do?

https://docs.spring.io/spring-data/jpa/reference/repositories/custom-implementations.html

**Comment by beikov** [comment]
I don't think it does, no. You would have to implement the repository logic yourself in a separate bean.
But maybe @Mobe91 or @EugenMayer knows better?

**Comment by billysoderlundext** [comment]
Thanks for the response! Sorry , my bad. I was referring to EntityViewRepository. 
But maybe the same concept applies, your filters and criteria builders are great, especially for advanced cases.

**Comment by billysoderlundext** [comment]
Thanks for the clarification.
