### ISSUE TITLE
Generalize expression type determination

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#212]
Currently we have to define the return type for every function in a mapping so that we can resolve it. We could instead do a general type resolving based on the registered JpqlFunction objects.
I don't know yet how to handle the builtin functions of a JPA provider but we would probably have to provide JpqlFunction instances for them too.

**Comment by beikov** [comment]
@Mobe91 this(https://github.com/Blazebit/blaze-persistence/commit/491f6494537fef77ec8e831f327b938571c345de) wouldn't have been necessary if the function return types could be resolved ;)

**Comment by Mobe91** [comment]
I know

**Comment by beikov** [comment]
As we discussed today, we are going to implement a general expression type determination. This is necessary for being able to render parameters correctly and also makes a lot of type determination code we currently have a lot less clumsier.

**Comment by beikov** [comment]
When we have this, we could also determine if boolean expressions are valid regarding the type comparisons for `@MappingCorrelatedSimple`.

**Comment by beikov** [comment]
To do this, we must change the JpqlFunction contract in an incompatible way, so this will be done as part of https://github.com/Blazebit/blaze-persistence/issues/334 in 2.0
