### ISSUE TITLE
DataNucleus function "MONTH" doesn't need overriding for "datanucleus-5"

### ISSUE THREAD

**Issue by andyjefferson** [Blazebit/blaze-persistence#230]
While in DataNucleus v4.x MONTH obeys Java conventions, with DataNucleus v5.x there are two methods
MONTH (like SQL, 1-12), MONTH_JAVA (like Java, 0-11). Consequently you don't need to override any method definition for DataNucleus v5.x. I won't be backporting this to v4.x since people will likely be using that method, so more convenient to changeover at a major release 4 -> 5.

Also COUNT(*) is supported in JPQL by DataNucleus v4.x and v5.x (mapping to internal function "COUNTSTAR", provided by the RDBMS plugin), so don't think you need to provide your own there either.

**Comment by beikov** [comment]
Thanks for the info, I'll fix that in a minute!

**Comment by beikov** [comment]
Hmm, a query like ```SELECT COUNT(*) FROM SomeEntity e``` does not seem to work. Do you mean the function is supported in the sense that I can use "COUNTSTAR" instead of my custom "COUNT_STAR"?

**Comment by andyjefferson** [comment]
I can do JPQL "SELECT COUNT(*) FROM Person p" and it is compiled generically to

QueryCompilation:
  [result:InvokeExpression{STATIC.COUNTSTAR(<none>)}]
  [from:ClassExpression(alias=p)]
  [symbols: p type=mydomain.model.Person]

and the resultant SQL becomes
SELECT COUNT(*) FROM PERSON P

**Comment by beikov** [comment]
Ah ok, so the parser doesn't like the additonal spaces after the star character. I have a query like ```SELECT COUNT(*    ) FROM SomeEntity e``` to be able to efficiently replace the count call with a custom function in a string builder. I'll have to stick to my custom function then until the parser ignores the whitespaces.
