### ISSUE TITLE
How to properly create a where/or criteria? It translates to an AND now.

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#237]
The following part of my criteriabuilder:

`.whereOr().where("fn.endDate").isNull().endOr().where("fn.endDate").gt(LocalDateTime.now())`

Translates to:

` (contract3_.end_date is null) and contract3_.end_date>? `

Am I using it wrong?

**Comment by JWGmeligMeyling** [comment]
Should have been `                    .whereOr().where("fn.endDate").isNull().where("fn.endDate").gt(LocalDateTime.now()).endOr()`

I may add some examples :smile:

**Comment by beikov** [comment]
Thanks :)
