### ISSUE TITLE
Pagination fails for CTE queries (at least recursive ones)

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#239]
During testing I found that Pagination doesn't work properly for CTE queries (at least recursive ones). May add a test case later on, as I am currently working around the issue.

**Comment by beikov** [comment]
This is more or less expected. Pagination currently only works for "normal"/non-sql replacing queries.
A testcase would be very helpful!

**Comment by beikov** [comment]
It works now but query caching is currently problematic. I will fix that issue in the final version.

**Comment by JWGmeligMeyling** [comment]
Cool, thats solved quickly then! 😉 Yesterday I presented some Hibernate CTE queries with `blaze-persistence` as part of my talk at the [IT Dev Cafe](http://www.meetup.com/IT-Development-Cafe/events/234086830/?).

**Comment by beikov** [comment]
Very nice! Happy to see you spread the word :)
