### ISSUE TITLE
Question about Hibernate scrollable results

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#253]
Hibernate supports streaming results, as such:

```java
Query query = session.createQuery(query);
query.setReadOnly(true);
query.setFetchSize(100);
ScrollableResults results = query.scroll(ScrollMode.FORWARD_ONLY);
while (results.next()) {
   Object row = results.get();
   // process the entity here
}
results.close();
```

The `createQuery` takes either a `java.lang.String` or `javax.persistence.criteria.CriteriaQuery`. Is it possible to use this scrollable result with blaze-persistence criteria queries?

**Comment by JWGmeligMeyling** [comment]
See also https://blog.informatech.cr/2014/12/17/java8-jpa-streams/ which shows how the `ScrollableResults` can be wrapped in a `java.util.stream.Stream` which may allow us to implement something more generic.

**Comment by beikov** [comment]
Do you want to process results in chunks or just use the stream API?
The problem with chunking like that is that it can't possibly support collections and can thus only work with scalar queries.

**Comment by JWGmeligMeyling** [comment]
Aha. I wasn’t (yet) aware of that limitation of chunking in Hibernate. I just started to play with it. I actually have to process a quite big result set, so I was hoping that chunking and detaching would reduce my memory footprint. I can imagine ScrollableResults conflicting with collections. Where is this documented?

https://docs.jboss.org/hibernate/orm/3.5/api/org/hibernate/ScrollableResults.html



On 28 Sep 2016, at 18:44, Christian Beikov <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you want to process results in chunks or just use the stream API?
The problem with chunking like that is that it can't possibly support collections and can thus only work with scalar queries.

**Comment by beikov** [comment]
Well I don't know for sure if it prohibits it, but as far as I know the code, it does JDBC batching which can't possibly work with non-scalar results.
Since some JDBC drivers don't support batching, this is also not really portable.
I would suggest you do chunking based on keysets. I have done a lot of big batch queries that way and it works perfectly.
If you can show me the query, I can help you rewriting it for keyset based paging/chunking.

**Comment by JWGmeligMeyling** [comment]
Thanks for the help but it's quite a query haha :wink:

```java
    <T> CriteriaBuilder<T> getRecursiveScopeChildrenCriteriaBuilder(Scope<?,?> start, Class<T> clasz) {
        return cbf.create(entityManager, clasz)
            .withRecursive(ScopeCte.class)
                .from(Scope.class, "scope")
                .bind("id").select("scope.id")
                .bind("ancestor").select("scope.parent")
                .where("scope").eq(start)
            .unionAll()
                .from(Scope.class, "scope")
                .from(ScopeCte.class, "parentScope")
                .bind("id").select("scope.id")
                .bind("ancestor").select("scope.parent")
                .where("scope.parent.id").eqExpression("parentScope.id")
            .end();
    }

public Stream<OrderEntry> getOrderEntries(Scope<?, ?> start, LocalDateTime begin, LocalDateTime end) {
        val query = scopeEntityManager.getRecursiveScopeChildrenCriteriaBuilder(start, OrderEntry.class)
            .from(OrderEntry.class).where("product").in()
                .from(ScopeCte.class, "s")
                .select("s.id")
                .end()
            // omitted another where clause filtering by date range.
            .fetch("order");

        return query.getResultList().stream();
    }
```

The `Stream` will then consume the `OrderEntries` in a `Collector`. The `Collector` detaches the `OrderEntries` after its done with that entry. Because the list of orders is potentially huge (depending on the time range, and the depth of the scope chosen), ideally I limit the number of entries loaded in memory, because I really only need them one by one.

**Comment by beikov** [comment]
I can see how a scrollable result would help, I will put it on my TODO list.
In case of a recursive CTE, the keyset pagination is probably not that efficient, but it should do the job.

First of all, you need some kind of ordering and limit the results. Something like the following

```
val query = scopeEntityManager.getRecursiveScopeChildrenCriteriaBuilder(start, OrderEntry.class)
            .from(OrderEntry.class).where("product").in()
                .from(ScopeCte.class, "s")
                .select("s.id")
                // You need the ordering so you can paginate on value ranges
                .orderByAsc("s.id")
                // The keyset is the id
                .where("s.id").gtExpression(":lastId")
                // The fetch size
                .setMaxResults(100)
                .end()
            .fetch("order")
            .getQuery();

// The iterator fetches from that query, remembering the last id for the next fetch
Iterator<OrderEntry> iterator = new Iterator<OrderEntry>() {
            List<OrderEntry> results;
            int position;
            int lastId = 0;

            private void fetch() {
                        query.setParameter("lastId", lastId);
                        results = query.getResultList();
                        position = 0;
            }

            public boolean hasNext() {
                        if (results != null && results.isEmpty()) {
                                    return false;
                        } else if (results == null || position == results.size()) {
                                    fetch();
                        }
                        return position < results.size();
            }

            public OrderEntry next() {
                        if (!hasNext()) {
                                    throw new IllegalArgumentException();
                        }
                        OrderEntry entry = results.get(position++);
                        lastId = entry.getId();
                        return entry;
            }
};

// Put that iterator into a stream
Stream<OrderEntry> stream = StreamSupport.stream(
          Spliterators.spliteratorUnknownSize(iterator, Spliterator.ORDERED),
          false);
return stream;
```

I see it's not ideal because it executes the CTE everytime a fetch is triggered. Another possible way would be to fetch all ids into memory, partition them to equal sized chunks and let the query for OrderEntry run for each chunk similar to what I just wrote.

I don't know what the concrete use case is that you have, but from experience, queries that do all at once like that don't work well in environments where you have concurrent operations. I rewrote many of my own queries to this kind of style because I wanted to apply throttling so concurrent operations aren't affected too much by the load.

How deep is the tree normally? Maybe you can partition on the root scopes and then the re-execution of the CTE is not such a big problem because it's for specific root scopes.

Also note that if you are doing any writes back to the database, update statements can also have CTEs ;)

**Comment by JWGmeligMeyling** [comment]
Thanks for the query, I'll definitely try that out. The depth is worst case `5` levels with a total of `2500` nodes, and the tree is quite well balanced, so at lower levels it becomes less quite fast. From my observations, the recursive part of the query is relatively fast, and the big result set (in combination with the size of the cross product with some of the fetched entities) is responsible for most of the execution time. So I have good hopes that pagination will do the trick (but truly streaming still would reduce the query time).

This particular query is by the way for analytical purposes, so I do not necessarily have a lot of concurrency on this particular query. I do have some intensive queries that are accessed concurrently :wink:

Thanks!

**Comment by beikov** [comment]
In that case I'd recommend you to paginate on root scopes. First fetch all root scopes and then execute the original query for every root scope.

You're welcome
