### ISSUE TITLE
Implement support for chunk-processing

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#254]
See #253 for details about the discussion.
Basically what we need is an API that allows chunk-wise processing similar to what Hibernate offers with it's scrollable result.

**Comment by JWGmeligMeyling** [comment]
JPA 2.2 will bring `Query#getStream()`, that defaults to `Query#getResultList().stream()` but which ORM vendors may override with a more performant implementation. Hibernate 5 already offers a `Query#stream()` method but barely optimises this. Optimisation of `Query#stream()` (and the future `Query#getStream()`) is planned for Hibernate 6.0. 

Simply put, I think that if you want to use this today, you have to use Hibernate 6.0 and call `getQuery().getStream()` on your criteria builder. Even then, the actual optimisation may not yet be fully implemented (I am uncertain what the current state of development of HH6 is).

**Comment by beikov** [comment]
Hibernate 6 is currently expected to be released by the end of this year. I'd like to avoid the requirement of using streams, after all, it is based on an Iterator/Spliterator and the scrollable API of Hibernate exposes this, so there is no need to force the Stream API on the user. By simply implementing proper iterators, we can support both, normal Iterable usage and Stream usage.
Implementing optimizations like the ones the Hibernate team is speculating about is out of scope for this issue.

**Comment by soberich** [comment]
@beikov @JWGmeligMeyling
What do you think about this streaming? Say, we have tens of thousands rows to stream.
Any severe drawbacks/disadvantages? (regardless transaction and considering we have lazy fetching where possible)
```kotlin
    @Transactional(NOT_SUPPORTED)
    override fun streamEmployees(): Stream<Employee> = 
            em.createQuery("SELECT e FROM EmployeeEntity e", EmployeeEntity::class.java)
                    .resultStream.map { evm.convert(it, EmployeeListingView::class.java) }
```

**Comment by beikov** [comment]
Fixed via https://github.com/Blazebit/blaze-persistence/pull/1344
