### ISSUE TITLE
Create Spring Data integration

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#261]
Since many users out there use Spring Data, it would be nice if we can provide an integration for that too. The integration would be similar to the CDI integration I think.

**Comment by beikov** [comment]
Would be nice if you also created some example projects in a sub-module `examples/basic-entity-views` e.g. `entity-view-model`, `cdi-showcase` and `spring-showcase` to showcase the integrations as well as showing best practices.

**Comment by nghib** [comment]
+1

**Comment by Mobe91** [comment]
@beikov I created a separate issue for your suggestion: #265

**Comment by Mobe91** [comment]
fixed via	bcb189e - 6ed0fa3
