### ISSUE TITLE
Create some examples on the GitHub Wiki

### ISSUE THREAD

**Issue by vladmihalcea** [Blazebit/blaze-persistence#263]
As a newcomer, it's very difficult to figure out what this framework can do. That's why I'd love to see some examples listed on the GitHub wiki.

Currently, the README file only shows the Maven dependencies, which plays the role of an Instalation Guide. Check out how I designed [the documentation for FlexyPool](https://github.com/vladmihalcea/flexy-pool) to get a better picture of what I'm talking about.

**Comment by beikov** [comment]
Thanks for the feedback Vlad. What a coincidence, I am working on exactly that right at this moment ^^
Hope you can give me some more feedback when I add the first steps 😄

**Comment by vladmihalcea** [comment]
Of course. Looking forward to reading more about this framework.

**Comment by JWGmeligMeyling** [comment]
@vladmihalcea Have you found the ASCII doc in the repository? At least for CTE queries there is quite some information there. For EntityViews there is a bit as well. Obviously it could use a lot more examples, but from your description it seems you haven't found this documentation yet. The documentation is stored in the repository https://github.com/Blazebit/blaze-persistence/tree/master/documentation/src/main/asciidoc . I assume further amendments to the documentation will also go there. You can also look at the issues labeled as [`question`](https://github.com/Blazebit/blaze-persistence/issues?q=is%3Aissue+label%3Aquestion+is%3Aclosed).

**Comment by vladmihalcea** [comment]
I haven't noticed it. Very interesting that you offer support for CTE. That's really great! Does it support Recursive CTE as well?

**Comment by JWGmeligMeyling** [comment]
Yes it does! See for example [this testcase](https://github.com/Blazebit/blaze-persistence/blob/master/core/testsuite/src/test/java/com/blazebit/persistence/testsuite/CTETest.java#L163-L181).
