### ISSUE TITLE
Create Spring Integration

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#264]
Create a basic Spring integration for that enables the auto-discovery and registration of entity views.

**Comment by beikov** [comment]
Please also add documentation sections in the reference manual in https://github.com/Blazebit/blaze-persistence/blob/master/documentation/src/main/asciidoc/core/manual/en_US/01_getting_started.adoc and https://github.com/Blazebit/blaze-persistence/blob/master/documentation/src/main/asciidoc/core/manual/en_US/03_configuration.adoc

**Comment by Mobe91** [comment]
I don't know of any specifics that would belong into https://github.com/Blazebit/blaze-persistence/blob/master/documentation/src/main/asciidoc/core/manual/en_US/03_configuration.adoc.

**Comment by beikov** [comment]
Ok sorry, thought that the configuration section also had a part about integrations.
