### ISSUE TITLE
EntitiyViews cannot handle primitive id fields

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#272]
If I map the id field to an `@IdMapping("id") long getId()` I get a `java.lang.IllegalArgumentException: Primitive type not allowed for the getter` exception. If I change `long` to `Long` instead, I get `java.lang.IllegalArgumentException: The given mapping constructor 'null' does not map to a constructor of the proxy class:`, with the cause `java.lang.IllegalArgumentException: The given mapping constructor 'Caused by: java.lang.NoSuchMethodException: com.pallasathenagroup.view.OrderEntryFeedView_$$_javassist_entityview_.<init>(long, java.lang.Integer)`.

Probably id fields should not be primitives by convention, but JPA does allow for it.

**Comment by beikov** [comment]
Just as a side note, this is a long standing documentation issues #82.
I'll look into it to see if I can remove the restriction, but the problem is that left joins can produce null values for subviews and with primitives there is no "sentinel" value.

**Comment by beikov** [comment]
Ok so this isn't as simple as I thought. Primitives require special byte codes and special assignability checks which is exactly why I didn't support them in the beginning.
This will need some time to get finished. The best way to make this work right now is by using object/wrapper types.

**Comment by JWGmeligMeyling** [comment]
You don't have to go through that hassle for me, I can easily migrate my fields to boxed values 😄 . But the fields I am accessing are all non-optional many-to-ones, so left joins are not necessarily required in that case. (And in fact, Hibernate uses inner joins in that occasion as well)

**Comment by beikov** [comment]
Would you mind confirming that your use case works? I have some tests in place but no full coverage.
