### ISSUE TITLE
Introduce configuration property for defining jpa provider version

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#274]
Since a fat jar deployment would make version detection impossible to some extents as has been discussed in #258, we should add a property which can be used to configure the jpa provider implementation version.

**Comment by beikov** [comment]
You can now put an implementation of HibernateVersionProvider on your classpath which provides the version via a method. This should do the trick for fat jar deployments.

**Comment by JWGmeligMeyling** [comment]
Great! I'd been working on other pieces of my code as the minor 5.2.3.Final release introduced breaking changes with setting native query parameters (they switched from `0` to `1` as start index). Pretty annoying, so I didn't have a chance to look into this issue more :)
