### ISSUE TITLE
Support @Embeddable bindings in CTEs

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#275]
Currently we only support the binding of simple attributes in CTEs. In some cases it would be handy to be able to bind e.g. embedded ids like:
```
.bind("id.a").select(...)
.bind("id.b").select(...)
```

**Comment by beikov** [comment]
This is roughly about the same: https://github.com/Blazebit/blaze-persistence/issues/300

I will bind expression to the target columns instead of on attribute level to make this and also the other usage as shown in #300 possible.
