### ISSUE TITLE
Fix polymorphic property tests for Eclipselink

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#311]
`com.blazebit.persistence.testsuite.PolymorphicPropertyTest` is currently failing for Eclipselink.

`com.blazebit.persistence.testsuite.PolymorphicPropertyTest#testSelectSubProperty` should become a negative test.

`com.blazebit.persistence.testsuite.PolymorphicPropertyTest#testSelectSubPropertyWithTreat` fails with Eclipselink because the Eclipselink metamodel, in contrast to Hibernate, correctly resolves the type parameter for the subtypes PolymorphicSub1 and PolymorphicSub2 and returns different attributes for the respective subtypes.

**Comment by beikov** [comment]
I haven't exactly fixed it, but rewritten the test to be a negative one. The implicit downcast stuff was buggy anyway in the jpa provider implementations. Using treat is much safer and we can emulate that on non jpa 2.1 providers with implicit downcasting behind the scenes.
