### ISSUE TITLE
Fix metamodel lookup of generic type attributes

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#319]
Each metamodel attribute might potentially receive its type via a generic type parameter so we cannot trust `attribute.getJavaType()` to return the concrete type. Instead we have to manually resolve the attribute type against the concrete type the attribute is used in. There are several spots across blaze-persistence where this needs to be fixed, just look for usages of `attribute.getJavaType()`.

**Comment by beikov** [comment]
As far as I can remember EclipseLink returns the concrete types. Hibernate will too in future versions as per https://hibernate.atlassian.net/browse/HHH-10690
I don't know about DataNucleus but I guess it might be a good idea to implement fallbacks to manual type resolving where possible.

**Comment by beikov** [comment]
Fixed as part of #362
