### ISSUE TITLE
Report type parameter resolving hibernate metamodel bug

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#320]
Hibernate currently fails to fully resolve type parameters when building its metamodel. This results in missing embeddable types in the metamodel which then leads to problems in blaze-persistence.
Until this issue is resolved in Hibernate, we use CTE entity classes containing explicit references to all embeddables as a workaround.

**Comment by beikov** [comment]
Maybe we can use the hibernate native metamodel to workaround this in older versions.

**Comment by beikov** [comment]
Working on this right now: https://hibernate.atlassian.net/browse/HHH-10690

**Comment by beikov** [comment]
I implemented a fix in Hibernate for this, let's see when it get's applied.
