### ISSUE TITLE
Allow providing custom EntityViewSetting to spring data repositories

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#325]
Right now, the repositories are bound to a specific entity view type that is defined statically.
Since one of the nice things about entity views is, that the type, filters and sortings can be dynamically defined by the client, we should also allow passing in the entire `EntityViewSetting` object or maybe even just subsets of it into a repository via parameters.

**Comment by Mobe91** [comment]
I understand the idea but I think that spring data repositories is very static by nature and I am not sure if there is much to gain for the users if we allow more dynamicity. After all, the user can always fall back to using the CriteriaBuilder directly which provides access to the full set of features. I rather see the spring data integration as a nice tool to quickly have the most commonly used data access methods at hand without writing a lot of code.

**Comment by beikov** [comment]
As you can see by this user request, the expectation is that there is some support: https://github.com/Blazebit/blaze-persistence/issues/350

**Comment by beikov** [comment]
The PR was just a partial fix that added support for `@OptionalParam`

**Comment by beikov** [comment]
Superseded by #622
