### ISSUE TITLE
Implement pagination integration for spring data

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#326]
I know that spring-data offers pagination support and it might be nice to have an integration for that too. That integration should be possible for core and entity view separately, so maybe we should begin to split up the spring-data module into **blaze-persistence-integration-core-spring-data** and **blaze-persistence-integration-entity-view-spring-data**.

**Comment by Mobe91** [comment]
The current state of the integration already supports the pagination mode provided by spring data which does not do keyset pagination though. So the sole benefit would be to have keyset pagination with spring data.

**Comment by beikov** [comment]
This was fixed as part of a first implementation for https://github.com/Blazebit/blaze-persistence/issues/373
