### ISSUE TITLE
Implement DeltaSpike Data integration

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#328]
DeltaSpike Data is the analogous in CDI to what the Spring Data is in Spring DI. Therefore we should provide an integration to be able to make use of Entity Views and other features as well.

**Comment by JWGmeligMeyling** [comment]
@Mobe91 How's this going? I've recently started to use DeltaSpike in my codebase. Up until now, I have been using my own equivalent for Spring Data (a combination of AbstractRepositories and QueryDSL/Blazepersistence criteriabuilders), but I am planning to slowly migrate to DeltaSpike Data altogether. What are the current ideas that a DeltaSpike integration should have? And is any help stil welcome here?

**Comment by beikov** [comment]
He's nearly done as far as I know. Shouldn't be too long until this is on master.

**Comment by Mobe91** [comment]
Yeah it is almost finished..
