### ISSUE TITLE
Support subviews in map keys

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#329]
Currently we do not support subviews for map keys, e.g.:
```java
@Entity
public class MyEntity {
    Map<EntityA, EntityB> map;
}

@EntityView(MyEntity.class)
public interface MyEntityView {
    Map<EntityAView, EntityBView> getMap();
}
```
For Hibernate, this is blocked by:
* https://hibernate.atlassian.net/browse/HHH-10537
* https://hibernate.atlassian.net/browse/HHH-10577

**Comment by beikov** [comment]
I implemented it and tested it with EclipseLink. Hibernate should work too as soon as the fixes I made are applied. DataNucleus will most probably also have a solution soon: https://github.com/datanucleus/datanucleus-core/issues/182
