### ISSUE TITLE
NPE after switching from Alpha1 to Alpha2

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#336]
Happens on initialisation of the CriteriaBuilderFactory. Switching back to Alpha1 solved the problem for me.

```
INFO: Blaze-Persistence version: Blaze-Persistence 'Ink' 1.2.0-Alpha2
Exception in thread "main" java.lang.NullPointerException
	at org.hibernate.mapping.Column.getCanonicalName(Column.java:352)
	at org.hibernate.mapping.Table.getColumn(Table.java:232)
	at com.blazebit.persistence.impl.hibernate.HibernateExtendedQuerySupport.getColumnTypes(HibernateExtendedQuerySupport.java:180)
	at com.blazebit.persistence.impl.EntityMetamodelImpl.<init>(EntityMetamodelImpl.java:89)
	at com.blazebit.persistence.impl.CriteriaBuilderFactoryImpl.<init>(CriteriaBuilderFactoryImpl.java:80)
	at com.blazebit.persistence.impl.CriteriaBuilderConfigurationImpl.createCriteriaBuilderFactory(
[....]
```

**Comment by Mobe91** [comment]
What Hibernate version are you using?

**Comment by beikov** [comment]
Would be interesting if you could debug and check for what entity/table and column this happens. Do you have computed columns in your entities maybe?

**Comment by JWGmeligMeyling** [comment]
`5.2.6.Final` with the `blaze-persistence-integration-hibernate-5.2`

**Comment by JWGmeligMeyling** [comment]
I do have one `@Formula` column in one entity, if that counts as a computed column. I am running a few batches on `1.2.0-Alpha1`, but in a few minutes I can test against 1.2.0-Alpha2 again and provide some debugging information.

**Comment by beikov** [comment]
Let me create a test for that so I can make sure this works. I think the persister reports `null` as column name for such properties which is why this exception might happen.

**Comment by beikov** [comment]
Indeed, was able to reproduce it.

**Comment by beikov** [comment]
Can you confirm it works with the latest snapshot? Sorry to say, but it seems you'd have to stick to a custom build for now.
From what I can say, the Alpha3 release is probably 1 month away so either you use the SNAPSHOT now or stick with Alpha1 until then.

**Comment by JWGmeligMeyling** [comment]
Unfortunately the bug is still present in the latest snapshot (I tested against the repository master). After stepping through the code, it seems to happen for a regular column in an abstract entity mapped with `@Inheritance(strategy = InheritanceType.TABLE_PER_CLASS)`. (So the table name actually comes from the subtype)

**Comment by JWGmeligMeyling** [comment]
Thanks for merging! I'll stick with using the latest `SNAPSHOT` for now :wink:
