### ISSUE TITLE
Implement option for inlining CTEs/Subquery in from clause and lateral support

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#337]
Especially for DBs like PostgreSQL where a CTE also is an optimization fence, it might be desireable to inline the subquery directly into the FROM clauses. This should be doable on a per from clause basis and obviously only works for non-recursive CTEs.
The option could be turned on by default for DBMS that don't support CTEs to emulate non-recursive CTEs. This should also be documented in _Chapter 14. DML statements_ and _Chapter 15. CTEs_

Be careful when implementing this. Reordering the CTE queries logically requires the same tricks as for https://github.com/Blazebit/blaze-persistence/issues/305 because of the parameters

Maybe we can also introduce new `from` and `join` methods, something like the following

* `fromSubquery(Class<?> cteClass)` returning a cte builder? conflict with entity version?
* `from(CriteriaBuilder<?> builder, String alias)`
* `fromSubquery(Class<?> entityClass, String alias)` returns a builder that binds all attributes of the entity automatically and doesn't allow an additional select clause or join fetching. DBMS will optimize away unused columns anyway, so this would be very convenient

Also think about allowing something like the following

* `fromTopOfPartition(Class<?> entityClass, String alias, int topCount).partition(String expression).orderBy(...)`

This will transparently implement the top values per category/partition for the user behind the scenes which is quite important for analytics queries. This will render:

```
select ...
from (
  select * from(
    select ..., row_number() over(partition by PARTITION order by ORDER) as rn
    from entity sub
  ) x
  where x.rn <= TOP_COUNT
) alias
```

or 

```
select ...
from entity alias join (
  select ..., row_number() over(partition by PARTITION order by ORDER) as rn
  from entity sub
) x on alias.id = x.id and x.rn <= TOP_COUNT
```

So this is a kind of wrapper/entity-function around the query but also injects the row_number part.

According to https://blog.jooq.org/2017/09/22/how-to-write-efficient-top-n-queries-in-sql/ it is better in PostgreSQL to use `lateral`, so it might be worth rendering the following

```
select ...
from entity alias lateral join (
  select sub.id
  from entity sub
  where alias.PARTITION = sub.PARTITION
  order by ORDER
  limit TOP_COUNT
) x on alias.id = sub.id
```

Maybe the following can be rendered as a last resort

```
select ...
from entity alias 
where alias.id in (
  select sub.id
  from entity sub
  where alias.PARTITION = sub.PARTITION
  order by ORDER
  limit TOP_COUNT
)
```

Support for `lateral` is probably not very hard after we have that. Maybe we could introduce lateral support as part of a PR for this issue. On the contrary, it easier to add lateral than subquery support, because for subqueries we will have to ensure they are not correlated. We need a validation for the subqueries in the from clause that throws when encountering a correlated reference.

Any thoughts on additional methods or naming?

**Comment by JWGmeligMeyling** [comment]
> * `fromSubquery(Class<?> cteClass)` returning a cte builder? conflict with entity version?

I have a few occurrences where I use a CTE for reprojection before aggregration in an outer query, where the `fromSubquery` would yield more readable results than having to specify the CTE separately. I don't think the naming is confusing per say, but not being able to reference outer query variables might become an obstacle.

Why no aliased alternative by the way?

> * `from(CriteriaBuilder<?> builder, String alias)`

Personally I try to stick with 1 `CriteriaBuilder` as much as possible. But I see how this addition would be useful.

> * `fromSubquery(Class<?> entityClass, String alias)` returns a builder that binds all attributes of the entity automatically and doesn't allow an additional select clause or join fetching. DBMS will optimize away unused columns anyway, so this would be very convenient
> 

Do you have an example where this would be useful?

> * `fromTopOfPartition(Class<?> entityClass, String alias, int topCount).partition(String expression).orderBy(...)`

We already discussed that this is a useful addition. The struggle here will be to produce SQL that can actually be optimized fairly well.


> 
> Any thoughts on additional methods or naming?

**Comment by beikov** [comment]
> Why no aliased alternative by the way?
There will be plenty of variants, I just wanted to mention the core ones for readability.

> Do you have an example where this would be useful?
This is for readability I guess. I have many legacy SQL queries that work this way

```
select ...
from (
  select ...
  from entity a
  join a.relation b
  where b.attr = 'some value'
) x
where exists (
  ...
  where x.id = ...
)
```

It's not very optimal because you can't make available joined associations, but I just saw the pattern and wanted to propose it to you folks to see if there is a need for it.

> We already discussed that this is a useful addition. The struggle here will be to produce SQL that can actually be optimized fairly well.

Actually, I think the subquery and lateral LIMIT approach might be pretty efficient on other DBMS as well, but we can try out different strategies to be sure.

> A fluent fromValues perhaps?

Anything more concrete maybe? I'm not sure if a builder would be more readable than using `Arrays.asList()`

**Comment by beikov** [comment]
> not being able to reference outer query variables might become an obstacle.

That's how SQL is defined 😆 
You will have to use `lateral` to allow the use of outer variables, but I would like to ask the user to define that explicitly, as using lateral imposes a pretty strict query plan i.e. nested loop join

**Comment by JWGmeligMeyling** [comment]
> It's not very optimal because you can't make available joined associations, but I just saw the pattern and wanted to propose it to you folks to see if there is a need for it.

But I still don't see the point in using a subquery here? Or is the point to inner join multiple optional associations?

> That's how SQL is defined 😆

I brainfarted, obviously you can only do that either in the select clause or with a lateral join. :)

**Comment by beikov** [comment]
Inner joining there is one option but the main idea is to abstract

**Comment by Mobe91** [comment]
Sounds good.
> fromTopOfPartition

Are there any arguments for introducing such a method apart from comfort? I think it would be more flexible/better to just add a proper window function API to the SelectBuilder.

**Comment by beikov** [comment]
It's a convenience API indeed, but the work you need to do to implement that yourself is pretty big so it's at least better for readability. It also helps with optimizations because some DBMS might be better at optimizing this pattern when rendering window functions, other support correlated subqueries better etc.
Allowing to define the strategy manually makes this the ultimate tool.

We already have window expression support, so you can formulate this manually as well, but as I wrote, it involves quite a lot and might not be optimal for the target DBMS.

I'm undecided on the `fromSubquery(Class<?> entityClass, String alias)` part, so I would like get more feedback on that.

**Comment by beikov** [comment]
Maybe something like `fromTopOfPartition(String entityCollectionPath, String alias, int topCount)` would be useful for fetching only TOP-N elements of a collection. Unfortunately we currently will have to base the query on the entity containing the collection as we don't have a way to extract the SQL that only touches a join table, but it's good enough for now. Also, a DBMS should be able to optimize the join away if the FK from the join table to the parent is non-null. That FK being null should be the exception anyway.

In entity views, we could introduce a `@Limit(order = {}, limit= "integerLiteralOrParameter")` annotation for that purpose. The partition part is implicitly defined as parent identifier i.e. id mapping of the view or as defined via `@MappingIndex` after #401.
