### ISSUE TITLE
Extend array expression to support a predicate

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#342]
Right now, array expressions only support paths, parameters and literals as index expression. The index expression is the used for an equality predicate with the key of the collection represented by the array expression's base. This obviously only works for indexed lists and maps. Today I thought about extending this by allowing a predicate within the brackets. By doing so, we could essentially specify the `ON` clause part of any collection right within the expression itself. Here a little usage example

```java
cb.from(Person.class, "person")
    .select("person.animals[status = AnimalStatus.DEAD AND age > 5].name")
```

produces the following JPQL

```sql
SELECT animals_ext_1.name
FROM Person person
LEFT JOIN person.animals animals_ext_1
          ON animals_ext_1.status = AnimalStatus.DEAD 
        AND animals_ext_1.age > 5
```

Within the brackets the _implicit_ root would change to the collection join alias.
Thoughts?

**Comment by beikov** [comment]
Another nice addition to this would be to allow an expression like `SIZE(animals[status = AnimalStatus.DEAD])` to be transformed correctly by the size transformation. This will simplify many entity views and probably make even more subquery provider usages in entity views unnecessary.

**Comment by beikov** [comment]
Related to #324 as this would make #324 unnecessary

**Comment by jwgmeligmeyling** [comment]
Bracket indexing doesn't really seem to be a sensible syntax for a cardinality increasing operation to me. I actually find a select with an implicit plural join rather suspicious. Combined with the property dereferene, the example query really appears to return a single value for each person although its really not.

I'm not sure if this issue should be considered a full replacement for #210 and #324.

**Comment by beikov** [comment]
It's not a replacement, but I will add support for #210 as part of this.
