### ISSUE TITLE
Clarify SIZE transformation of embedded id collection owners

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#353]
Currently we always require a subquery for `SIZE` invocations of embedded id collection owners: https://github.com/Blazebit/blaze-persistence/blob/1cc36fef290ec8f926477229809e53fb8077f9bb/core/impl/src/main/java/com/blazebit/persistence/impl/transform/SizeTransformationVisitor.java#L194

Is that still required and if so, why?

**Comment by Mobe91** [comment]
Count generation for embeddable collection owners seems to be not supported right now.
