### ISSUE TITLE
Entity view correlation mapping simplifications

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#366]
Since we always require the correlationResult of a correlation mapping to be the alias or an attribute of the correlated entity we could make correlationResult optional and default to the alias introduced through the correlation. Also update the documentation _Correlated mappings_ when doing this.

In addition to that, we should introduce something like `@MappingCorrelatedSimple` that can be used to correlate by a simple expression. This allows to reduce some boilerplate since we can avoid a separate `CorrelationProvider`.

```java
@EntityView(Cat.class)
public interface CatView {
  @MappingCorrelatedSimple(
    correlated = Person.class, 
    correlationBasis = "age", 
    correlationKeyAlias = "customCorrelationKey",
    expression = "age IN customCorrelationKey",
    correlationResult = ""
  )
  Set<Person> getSameAgedPersons();
}
```

**Comment by beikov** [comment]
@Mobe91 What do you think about the name? Have a better idea for naming the annotation?

**Comment by Mobe91** [comment]
Why don't we just add the `expression` attribute to the existing `@MappingCorrelated` and make the `correlator` attribute optional?

**Comment by beikov** [comment]
The `correlationKeyAlias` and `correlated` attributes would also have to be added and it would quickly get out of hand..
