### ISSUE TITLE
Introduce EMBEDDING_VIEW function to refer to the embedding entity view

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#367]
Currently `OUTER` is handled in the core and allows to refer to the query root of a parent query builder. Within entity views this might not be what people expect. This is only problematic when the subquery provider is in a subview which is why nobody complained too much yet. We should adapt that so that `OUTER` refers to the embedding entity view i.e. the entity view that uses the subquery provider instead. Referring to the entity view root which is what `OUTER` does right now can be done by using `VIEW_ROOT`. Since the entity view root could be changed, we might want to consider adding another macro called `QUERY_ROOT` that always refers to the query root.

We should document that using OUTER in a subquery within a subquery provider will still resolve to the embedding entity view.

**Comment by Mobe91** [comment]
I don't really get your idea. Do you want to have different meanings for OUTER depending on whether it is used in the context of entity views or not? I don't think this would be a good idea.

**Comment by beikov** [comment]
Why do you think this is a bad idea? Everyone that used OUTER thought it would refer to the entity of the embedding view, not the query root. The worst of all is, that the wrong use of OUTER might not be apparent because the embedding entity type might have the same attribute as the query root. I say, we either disallow OUTER in entity views or overload it's meaning. Right now it will do more harm by introducing bugs than good.

**Comment by Mobe91** [comment]
I doubt that having one operator with two meanings is comprehensible. Why not introduce a separate operator `OUTER_VIEW`? What if a subquery provider provides a subquery with another nested subquery? Then `OUTER` should have its usual meaning, namely referring to the outer subquery when  used in the nested subquery. Accessing the embedding view should be possible independently.

**Comment by beikov** [comment]
Ok then what should we name it? `OUTER_VIEW`? `EMBEDDING_VIEW` or `PARENT_VIEW`?

**Comment by Mobe91** [comment]
I would go for `EMBEDDING_VIEW` to demarcate it from the `OUTER` semantics.
