### ISSUE TITLE
Primitive boolean attribute doesn't work with entity views

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#375]
Although we support primitive types now, the special case for the boolean type is problematic. When having an abstract method `boolean isAbc()` the attribute name extraction fails.

**Comment by roma2341** [comment]
it seems that it's doesn't work in 1.6.8

**Comment by beikov** [comment]
Thanks for the report @roma2341, but let's discuss the matter about multiset on https://github.com/Blazebit/blaze-persistence/issues/1830
