### ISSUE TITLE
Restructure entity view metamodel

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#376]
Currently the entity view metamodel is kind of wrong and needs to be fixed. The structure of how it should be will be documented in the metamodel section of the documentation. We should adapt it to that design.
IdentifiableViewType should be removed and some methods from ManagedViewType have to be moved down to ViewType.

Actually we should also rename the EmbeddableViewType as it actually represents just a view that has no id. @Mobe91 have an idea for a name? I thought maybe _FlatViewType_ or so. By the way, the `@EmbeddableEntityView` annotation will be removed as it's functionality can be modeled with a normal `@EntityView` after relaxing id requirements with #356

**Comment by Mobe91** [comment]
I would go with `FlatViewType`. Can't think of any better name.
