### ISSUE TITLE
Add documentation(or update roadmap) about entity graphs support

### ISSUE THREAD

**Issue by weblogichub** [Blazebit/blaze-persistence#391]
Add documentation(or maybe update roadmap) about entity graphs support

**Comment by beikov** [comment]
There is no entity graph support. [Entity views](https://persistence.blazebit.com/documentation/entity-view/manual/en_US/index.html#getting-started) are in our opinions the way to go. What kind of support would you expect?

**Comment by weblogichub** [comment]
just for clarification. I'm just interested on point of view of the development team on this widely used JPA feature.

**Comment by beikov** [comment]
Hmm, ok I'll add a section that describes why we don't support entity graphs and how entity views are a better fit in any case. Note that you could still use entity graphs when not using any of the _advanced features_ as it's just a query hint. So this should still work:

```
CriteriaBuilder<Document> cb  = ...;
TypedQuery<Document> query = cb.getTypedQuery();
query.setHint("javax.persistence.fetchgraph", em.getEntityGraph("someEntityGraph"));
```

**Comment by beikov** [comment]
I hope the prefaces for both modules are enough? 

core - https://persistence.blazebit.com/documentation/core/manual/en_US/index.html#preface
entity view - https://persistence.blazebit.com/documentation/entity-view/manual/en_US/index.html#preface
