### ISSUE TITLE
Upgrade spring data integration to support Spring Boot 1.5.x

### ISSUE THREAD

**Issue by anthofo** [Blazebit/blaze-persistence#406]
The EntityViewRepositoryFactoryBean is no longer compatible with spring after upgrading to Spring Boot 1.5.2, because of a default constructor no longer available in the extended TransactionalRepositoryFactoryBeanSupport. The app will crash at startup

**Comment by beikov** [comment]
Sorry you are having trouble. I will look into this. Too bad spring data isn't designed in a way so that other libraries can provide extensions :/

**Comment by anthofo** [comment]
I hope they will improve this in a next release, extending the spring repositories factories is not an easy thing
