### ISSUE TITLE
Missing dependencies for blaze-persistence-spring-data

### ISSUE THREAD

**Issue by anthofo** [Blazebit/blaze-persistence#407]
Hi,

After adding the dependencies 
- blaze-persistence-spring-data:1.2.0-Alpha2 
- blaze-persistence-integration-entity-view-spring:1.2.0-Alpha2

in my project (Spring boot 1.5.2 + hibernate 5.x)  and configuring the **@EnableJpaRepositories(repositoryFactoryBeanClass  = EntityViewRepositoryFactoryBean.class)**, The app crash at startup because of missing classes.

I had to add manually the following dependencies : 

- blaze-persistence-integration-hibernate-5:1.2.0-Alpha2
- blaze-persistence-core-impl:1.2.0-Alpha2

Maybe these dependencies should be added in **blaze-persistence-spring-data** ?

**Comment by anthofo** [comment]
I also had to instanciate a CriteriaBuilderFactory manually : 

    @Bean
    public CriteriaBuilderFactory cbf(EntityManagerFactory emf) {
        return Criteria.getDefault().createCriteriaBuilderFactory(emf);
    }

It is ok, but I was a bit lost after following this doc : https://github.com/Blazebit/blaze-persistence/blob/master/documentation/src/main/asciidoc/entity-view/manual/en_US/09_spring_data.adoc

Adding this as a pre-requisite in the documentation for using spring data integration would be helpful I think :)

**Comment by beikov** [comment]
You are right about the impl dependency, this could be improved, but you still need to declare the Hibernate dependency as you could use Spring Data with other JPA providers too.
Actually the link to the setup section is there, it's just broken. I'll fix that and also add a small section about the required parts. Note that these dependencies are actually documented, it's just that when you are starting from the Spring data section you could miss these parts I guess.
By the way, the documentation is deployed here: https://persistence.blazebit.com/documentation.html
There are two parts, one for the core and another for the entity views module.
