### ISSUE TITLE
Adapt keyset predicate to be easier for DBMS to optimize

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#419]
Markus Winand explains this very nicely in his [article](http://use-the-index-luke.com/de/sql/partielle-ergebnisse/blaettern) that although the current form for keyset predicates that is implemented might be easier understandable, DBMS might not see through it that easily. Since DBMS can only use top level conjuncts for index lookups, we should rewrite the predicate generation to that form so we get more efficient execution plans.

**Comment by Mobe91** [comment]
fixed via a48439d
