### ISSUE TITLE
Comparison conditions for optimized key set predicate rendering is broken for embedded ids

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#444]
### Description

The row value comparison handling for the optimized keyset pagination handling currently produces broken SQL. When a order by for an embeddable is done, the `RowValueComparisonFunction` receives arguments like `['<', '(col1, col2)', '?']` which finally renders SQL like `where (col1, col2) < (?)`. This is obviously wrong and produces an error. There should be a second question mark for the second column.

Now the problem is, that Hibernate can't render the parameter as `(?,?)` because it doesn't know the parameter type and can't infer it because we pass it to a function. We could try to _treat_ the parameter so that it gets a proper type, but I'm not sure this will work across persistence providers.
If all that doesn't work, we have to _tupleize_ i.e. flatten the value manually, although I am not sure how easy that would be.

In additon to that, the "normal" optimized key set pagination code also produces invalid JPQL when embeddables are involved. A query contains a condition like `embedded < :param` which doesn't work. We would have to tupleize/flatten that too I guess.

**Comment by beikov** [comment]
Actually, I just found out that embedded ids generally don't work with keyset pagination currently because of generating `embedded < :param` code which isn't supported by hibernate as you can see here: https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/BinaryLogicOperatorNode.java#L127

**Comment by JWGmeligMeyling** [comment]
> Actually, I just found out that embedded ids generally don't work with keyset pagination currently because of generating `embedded < :param code` which isn't supported by hibernate as you can see here: https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/hql/internal/ast/tree/BinaryLogicOperatorNode.java#L127


So the generated query should split the expression into `col1 < ? and col2 < 3`? I by the way assume that this also applies for entities with a compound key using `@IdClass`?

Nevertheless, I really stopped using compound keys in Hibernate because it can break so many things so easily. And I always ended up having to map the same column to two mappings and tweak my mapping with `JoinFormula`'s and `insertable=false` columns ¯\_(ツ)_/¯

**Comment by beikov** [comment]
Yes it has to be split. I guess this applies to IdClasses as well however I'm not sure IdClass support is already that good to even hit the optimization. I'd expect the query generation fails for IdClasses right now.
