### ISSUE TITLE
Provide optional bounded ExpressionCache implementation

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#452]
In order to safely use blaze-persistence in production, a bounded expression cache should be used. Thus, we should provide a bounded ExpressionCache implmentation as a separate module to allow users to quickly get up and running. We may base the implementation on https://github.com/ben-manes/caffeine.

**Comment by JWGmeligMeyling** [comment]
I am not sure if this issue is still relevant. We have since fixed a memory leak issue in the ExpressionCache implementation, and the cache should now be naturally bounded. At least in my case, it stays within very reasonable sizes, and I have since removed my custom bounded expression cache.

**Comment by beikov** [comment]
We don't need this anymore. If a use case arises, please refer to this issue or let's reopen this one
