### ISSUE TITLE
Reuse of list parameters is not working

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#460]
When registering a list parameter e.g. with `entityViewSetting.addOptionalParameter("listParam", list)` and reusing this parameter in multiple spots in a query like `.inExpressions(":listParam")`, the query execution fails because not all parameter indices seem to be bound.

Workaround is to register a fresh parameter in every use site, e.g. with `.in(list)`.

**Comment by beikov** [comment]
Can't reproduce the error. If you run into this again, please attach a testcase for it.
