### ISSUE TITLE
Add temporal functions that allow adding a time unit to a timestamp

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#524]
It is sometimes a lot better to do something like `timestamp + 3 hours > ?` rather than `? - timestamp > 3` but currently we only have _diff_ functions which allow to get the difference in a unit between two timestamps. We should add functions that allow adding units to a timestamp as well.
I propose we add the following

* add_microseconds
* add_milliseconds
* add_second
* add_minute
* add_hour
* add_day
* add_week
* add_month
* add_quarter
* add_year

The functions take a timestamp and an integer value representing the value to be added as unit as defined by the function name. The return type is a timestamp. The value obviously can be negative which allows to subtract a value.

**Comment by JWGmeligMeyling** [comment]
Personally I use:

```
        metadataBuilder.applySqlFunction(
            "DATE_ADD_INTERVAL",
            new SQLFunctionTemplate(LocalDateTimeType.INSTANCE, "(?1 + interval ?2)")
        );
```

And then in queries: `FUNCTION('DATE_ADD_INTERVAL', :date, '5 hours')`

I also have implemented a custom type that maps Postgresql's `interval` to `Duration`, and allows me to do `:date + :duration` (which as far as I remember should be casted back to a date in order to figure out the correct output type of the expression).

**Comment by beikov** [comment]
That's great, but I don't think other DBMS support the same syntax so if we wanted to use the same style, we'd have to parse the string. Anyway, this seems to be on par with what is planned to be done for #168 so I'm in favor of this approach. :)

**Comment by JWGmeligMeyling** [comment]
So the `add_...` methods should work epoch based? Or how do you envision support throughout all DBMSes? :)
