### ISSUE TITLE
JOIN generation for inheritance hierarchies in mappings can be faulty

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#547]
Given entities `A > B` and `A > C > D`, where `B` has `D`'s, and `D` has a back reference to its parent `B`. Also given the entity views `AView` which has simple mapping to `DView`s of these `D`'s. Both `B` and `C` have a value for - say for example - `email`, where the value in subtypes of C (such as D) may override the default from B. In our mapping we now want to do something like:

```java
@EntityView(B.class)
interface BView {
    @IdMapping Long getId();

    @Mapping("children")
    DView getChildren()
}

@EntityView(D.class)
interface DView {
     @Mapping("COALESCE(email, TREAT(parent AS B).email")
     String getEmail();
}
```

However, this fails. The produced query left joins `B` with `C`, and attempts to get the `email` field from `C`. Because `B` cannot be `C`, the value is always `null`.

I think somehow the property resolvation for mappings is broken on inheritance entities. Perhaps there is some code that attempts to resolve the property by iterating over the subtypes, or some logic that assumes a mapping can only refer to a property of a single table.

I have tried to work around the issue using subquery mappings, with both `OUTER` and `VIEW_ROOT`, but they both failed with the same problem.

I'll further investigate this issue tomorrow, and hopefully I can create a somewhat neater reproducer/example than the brief summary of the domain I am facing the issue on now.

*Edit*:
By the way: simply `@Mapping("TREAT(parent AS B).email` in `DView` already attempts to read the `email` property from the joined `C` entity.

### Environment

Version:            
JPA-Provider:       
DBMS:               
Application Server:

**Comment by beikov** [comment]
Seems to be related to https://hibernate.atlassian.net/browse/HHH-11544 which is a Hibernate bug that is now fixed
