### ISSUE TITLE
Optimisation: reuse query root if mapped through inverse property within JOIN FETCH 

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#550]
While debugging issue #547, I found that, given entities:

```java
@Entity public class A {
     @Id String id;
     String someProp;
     @OneToMany(mappedBy = "children") Collection<B> children;
}

@Entity public class B {
    @Id String id;
    @ManyToOne parent;
}
```

And Entityviews:
```java
@EntityView(A.class) interface AView {
     @IdMapping String getId();
     @Mapping Collection<BView> getChildren();
}

@EntityView(B.class) interface BView {
    @Mapping("parent.someProp") String getSomeProp();
}
```

when querying for `A` as `AView` with the `BView` children eagerly joined, then table `A` is joined twice in the underlying query. This is because the resulting expression for `getSomeProp()` is `(root)children.parent.someProp` rather than `(root).someProp`. Perhaps it would be nice if we could eliminate the unnecessary join for the inverse property here. Its unfortunately probably not so easy to do so, as I already found out in #526 that finding inverse properties within the metamodel is not very straightforward.

### Environment

Version:            
JPA-Provider:       
DBMS:               
Application Server:

**Comment by beikov** [comment]
Seems to be a duplicate of #481

**Comment by JWGmeligMeyling** [comment]
Indeed a duplicate, sorry, I should have looked beter 😄 I'll close this one.
