### ISSUE TITLE
Binding NULL to an embeddable CTE property results in missing columns

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#567]
E.g. for a CTE Location and an embeddable Point:
```java
@CTE
class Location {
   private Point p;
   @Embedded
   public Point getP() { return p; }
   public Point setP(Point p) { this.p = p; }
}
```
```java
with(Location.class)
   .from(SomeEntity.class)
   .bind("p").select("NULL")
```
The above will produce a CTE definition with only 1 select clause item.

A simple workaround is to just bind the properties of the embeddable one by one:

```java
with(Location.class)
   .from(SomeEntity.class)
   .bind("p.x").select("NULL")
   .bind("p.y").select("NULL")
```

**Comment by jwgmeligmeyling** [comment]
I have a tentative fix in https://github.com/Blazebit/blaze-persistence/compare/master...jwgmeligmeyling:issues/567?expand=1 . I am also looking at #992 . I don't have a reproducer yet, it certainly is not applicable to basic types, so it seems specific to Maps or plural associations.
