### ISSUE TITLE
Support updatable collections in embeddables

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#597]
### Description

Giovanni Lovato is pushing the boundaries again 😁 
Using an updatable collection/map in an updatable flat view fails with weird exceptions. Query flushing doesn't fall back to entity flushing for that collection as it should and when configuring entity flushing, the produced JPQL for the fetching of dirty attributes is messed up.
This will be a Hibernate only thing again since collections in embeddables are only support by Hibernate as far as I know.

### Environment

Version:            
JPA-Provider:       
DBMS:               
Application Server:

**Comment by heruan** [comment]
I don't know if it's just Hibernate supporting this, but the spec just states in §2.6 that an embeddable contained in a collection must not contain a collection itself:

> An embeddable class (including an embeddable class within another embeddable class) that is contained within an element collection must not contain an element collection.

But of course each provider can have its own take on what the spec omits 😃
