### ISSUE TITLE
CriteriaBuilder orderBy generates strange query

### ISSUE THREAD

**Issue by FerreiraRaphael** [Blazebit/blaze-persistence#607]
### CriteriaBuilder orderBy generates strange query

**blaze-persistence.version**: 
I'm using the CriteriaBuilder method orderBy like in the docs:
https://persistence.blazebit.com/documentation/1.2/core/manual/en_US/#anchor-order-by-clause
```java
CriteriaBuilder<Tuple> cb = cbf.create(em, Tuple.class)
    .from(Cat.class)
    .select("age")
    .select("id")
    .orderByAsc("age");
```
and expected to receive a sql like in the docs, but the sql comes with a case when, that I don't understand from where it comes.
### Expected behavior
SQL like in the [docs](https://persistence.blazebit.com/documentation/1.2/core/manual/en_US/#anchor-order-by-clause):
```sql
SELECT cat.age, cat.id
FROM Cat cat
ORDER BY
    cat.age ASC NULLS LAST
```

or simple:

```sql
SELECT cat.age, cat.id
FROM Cat cat
ORDER BY
    cat.age ASC
```

### Actual behavior
```sql
SELECT cat.age, cat.id
FROM Cat cat
ORDER BY CASE WHEN
    cat.age IS NULL THEN 1 ELSE 0 END, cat.age ASC
```

### Steps to reproduce

Followed the docs setup steps:
[Maven Setup](https://persistence.blazebit.com/documentation/1.2/core/manual/en_US/#maven-setup)
[Hibernate 4.3 Setup](https://persistence.blazebit.com/documentation/1.2/core/manual/en_US/#maven-setup-hibernate43)
[Spring Environment Setup](https://persistence.blazebit.com/documentation/1.2/core/manual/en_US/#environments-spring)
### Environment

Version:            1.2.0
JPA-Provider:       Hibernate 4.3.11.Final
DBMS:               MYSQL 5.7.22
Application Server: Spring Boot 1.4.4.RELEASE

**Comment by beikov** [comment]
Hi! The problem is that MySQL does not support the NULLS FIRST/LAST clause which is why the expression you see is rendered. If the attribute is non-nullable, it will not render this emulation.

**Comment by beikov** [comment]
If you have any further questions, don't hesitate to create a new issue or join us on [Slack](https://blazebit.herokuapp.com/)

PS: The queries in the docs are usually JPQL or what we call JPQL.next
