### ISSUE TITLE
Strategies on how to serialize / deserialize Keyset ? 

### ISSUE THREAD

**Issue by ieugen** [Blazebit/blaze-persistence#652]
Hello,

I've experimented with blaze in our graphql based API to provide keyset pagination. One thing that struck me is that it is quite hard to properly set this up and I've decide to open this discussion so that maybe this situation improves. I'm trying to implement [relay-connection-cursor] and do pagination like that. 

From my understanding, I would have to serialize the whole Keyset page and it's kind of a lot of information to fit into a cursor. Any ways on how to avoid this? As per spec, each element has it's own cursor and I think it should be quite small. 

The solution that I have came up with is to provide a Ser/Deser strategy per each Entity that I do pagination on. When the request comes I know what strategy to use and I use that to encode / decode the token. 

By having a custom strategy I can encode the token efficiently by leveraging domain knowledge. 
I also have some limitation in place, some come from keyset pagination, some from our app:
- you can only order by one direction for all columns: either asc or desc
- you can only order by one column at a time (i'm not doing a spreadsheet)

With these limitations in place I can have a short cursor. The cursor uses a separator between columns and I encode values efficiently for web: 
- strings are encoded as base64 url safe
- ints, longs, etc are encoded as hex strings
- dates are split into longs and encoded as hex strings
- fields are separated by a character not belonging to encoding like `.` 

Now, this is kind of different than what a Keyset looks like and this is one area where I got stuck.

Not sure if I'm clear enough but it would be great to be able to efficiently serialize/deserialize  the Keyset information so that the cursor can be made part of the URL. 

Any ideas? 

[relay-connection-cursor] https://facebook.github.io/relay/graphql/connections.htm

**Comment by JWGmeligMeyling** [comment]
Keyset implements Java serializable, one approach could be to use an ObjectOutputStream that wraps a ByteArrayOutputStream, write the Keyset to the OOS, get the bytes from the BAOS and convert these bytes to Base64. Equivalently a ByteArrayInputStream and a ObjectInputStream can be used to extract the Keyset from a byte array.

Probably there are cleaner ways to serialize the keyset but I havent played with keyset paging let alone react cursus my self too much :)

**Comment by JWGmeligMeyling** [comment]
Nevermind didnt read your post entirely, we need someone else for this :)

**Comment by beikov** [comment]
The keyset contains only the values of the first and the last elements of the current page by which you ordered by. If you have a query like `FROM SomeEntity e ORDER BY e.id DESC` then the keyset will have `lowest = [1]` and `highest = [10]` i.e. the ids 1 and 10. This is as minimal as it gets, but serialization is a different story. You would normally not have to separately serialize the keyset, unless you want to provide URLs to the client that should be used for navigation. Normally, the keyset object is kept in a session but you could also serialize it to JSON. The spring data rest integration actually deserializes JSON to the keyset based on the defined entity type in `@KeysetConfig`. Also see https://persistence.blazebit.com/documentation/1.3/entity-view/manual/en_US/#spring-data-rest-integration
