### ISSUE TITLE
Provide built-in boolean aggregate functions

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#690]
Provide built-in boolean aggregate functions for supporting DBMS:
* `or_agg`
* `and_agg`

**Comment by JWGmeligMeyling** [comment]
As I am using these I'd like to contribute these methods. I am just not sure what the default method is to provide custom functions. Do we have any example of built-in functions that we already provide that I can use as an example?

**Comment by beikov** [comment]
Take a look at how `GROUP_CONCAT` is implemented.

**Comment by JWGmeligMeyling** [comment]
The default SQL names for `bool_or` and `bool_and` aggregation are `EVERY` and `SOME` in SQL. I've noticed other criteria builders also use `ALL` and `ANY` as function names for these aggregations (https://github.com/querydsl/querydsl/blob/2bf234caf78549813a1e0f44d9c30ecc5ef734e3/querydsl-core/src/main/java/com/querydsl/core/types/Templates.java#L275).

The PostgreSQL documentation states the following:

> *Note:* Boolean aggregates `bool_and` and `bool_or` correspond to standard SQL aggregates every and `any` or `some`. As for any and some, it seems that there is an ambiguity built into the standard syntax:
>
> ```sql
> SELECT b1 = ANY((SELECT b2 FROM t2 ...)) FROM t1 ...;
> ```
> 
> Here `ANY` can be considered either as introducing a subquery, or as being an aggregate function, if the subquery returns one row with a Boolean value. Thus the standard name cannot be given to these aggregates.

WDYT? Which naming should we go for?
* SQL standard `all` / `some` ([undecided](https://ronsavage.github.io/SQL/sql-2003-2.bnf.html#quantified%20comparison%20predicate)) or `any`
* QueryDSL standard for SQL : `all` / `any`
* QueryDSL standard for JPQL :  `every` / `some`
* PostgreSQL convention : `bool_and` / `bool_or`
* @Mobe91 's suggestion: `or_agg` / `and_agg`

**Comment by beikov** [comment]
IMO the question is whether we actually can implement aggregate functions for booleans for all DBMS. It's functionally a bit different to what the quantifiers `EVERY` and `SOME/ANY` provide, because the quantifiers only work for subquery predicates. An aggregate function can appear anywhere as an expression and one can also use it as a window function.
I like `or_agg` and `and_agg` as names for the aggregate functions.

**Comment by JWGmeligMeyling** [comment]
I know about the lack thereof in ANSI and the ambiguity in other dialects. MySQL and SQL Server seem to use ANY / EVERY as allowed boolean aggregates nontheless (at least that is suggested in https://stackoverflow.com/a/6060414/2104280 ).
