### ISSUE TITLE
Unexpected behaviour of counting size of collection of collection

### ISSUE THREAD

**Issue by haderlena** [Blazebit/blaze-persistence#695]
### Description

I  tried mapping the number of elements of a collection in my EntityView that required two joins (e.g. `@Mapping("SIZE(carrierProfiles.supplierEntries)")`).

### Expected behavior

Retrieving the number of elements of the collection, without changing the number of results.

### Actual behavior

Using COUNT and SIZE  both results in a subquery that counts the elements, but when using SIZE, the results of the entity view query are not grouped after joining. Thereby the mapping unexpectedly increases the results of the query.

### Environment

Version: 1.3.0-Alpha3           
JPA-Provider:       
DBMS:               
Application Server:

**Comment by beikov** [comment]
I will not deviate from what the JPA specification says about the `SIZE` function which is, that the last attribute in the path must be a plural attribute and for that, it will determine the count. To count the overall size of all elements, one will have to write a subquery.
