### ISSUE TITLE
Entity View: Multiple attribute filters fails with exception IllegalArgumentException

### ISSUE THREAD

**Issue by sharadborhade** [Blazebit/blaze-persistence#726]
### Description
Multiple filters to EntityView fails with below exception.

    java.lang.IllegalArgumentException: At most one active attribute filter per attribute is allowed!  attributeName = 'attribute'

Filter is defined as below:

    @AttributeFilters({
        @AttributeFilter(ContainsIgnoreCaseFilter.class),
        @AttributeFilter(name = "containsCaseSensitive", value = ContainsFilter.class)
	})

### Expected behavior
As per [documentation](https://persistence.blazebit.com/documentation/1.4/entity-view/manual/en_US/index.html#filter-api), we can only add one default filter (i.e. filter without name), but exception says we could add only one active filter.
Expectation was system will allow multiple filters.

### Actual behavior

    java.lang.IllegalArgumentException: At most one active attribute filter per attribute is allowed!  attributeName = 'attribute'

### Environment

Version:       1.3.1     
JPA-Provider:      Hibernate 
DBMS:               DB2
Application Server: Tomcat

**Comment by beikov** [comment]
As you can see in the ![documentation](https://user-images.githubusercontent.com/358916/51614325-b5736380-1f25-11e9-96a5-6662b0e40bae.png), it states that there may only be one active filter. I agree that the example might lead to confusion though, I will adapt the documentation accordingly.

**Comment by sharadborhade** [comment]
Oh my bad, multiple feature will be really helpful. 

My use case was use default filter to create to prepare base query and append Gui filters on top of it.

**Comment by beikov** [comment]
I'll create a separate issue for adding support for that. In the meantime, you could workaround this by having a [view filter](https://persistence.blazebit.com/documentation/1.4/entity-view/manual/en_US/index.html#view-filters) for the base query stuff.

**Comment by sharadborhade** [comment]
Thanks for the `blazing` fast response.
