### ISSUE TITLE
Case when expression with TREAT fails to parse

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#747]
The following mapping expression fails to parse:
```java
@Mapping("CASE WHEN parent.type = :baseProductNodeType THEN TREAT(parent AS BaseProduct) WHEN parent.parent.type = :baseProductNodeType THEN TREAT(parent.parent AS BaseProduct) ELSE NULL END")
```
The error is:
```
no viable alternative at input 'CASE WHEN parent.type = :baseProductNodeType THEN TREAT(parent AS BaseProduct) WHEN'
```

**Comment by beikov** [comment]
That's kind of expected. You can't have an object type i.e. non-scalar value in a CASE WHEN expression.

**Comment by JWGmeligMeyling** [comment]
Ah recently stumbled upon this one too. Wasn't sure if it was a grammar error or language limitation. Seems its the latter. Thanks!
