### ISSUE TITLE
Adapt rendering non-recursive CTEs when a recursive CTE is present

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#758]
When we consider a query with multiple CTEs, one of the being a recursive one, PostgreSQL will bail out when encountering the non-recursive CTEs saying that it requries all CTEs to have a UNION ALL part when the RECURSIVE keyword is used.
We can workaround this limitation of PostgreSQL by generating a dummy UNION ALL query which we already do for emulating normal CTEs for H2.
The workaround is to do this manually.

**Comment by JWGmeligMeyling** [comment]
Which version of Postgresql is this? I use recursive and non recursive CTE's along side all the time?

**Comment by beikov** [comment]
@Mobe91 which version are you using? You have been affected by this

**Comment by Mobe91** [comment]
Postgresql 9.6

**Comment by Mobe91** [comment]
I was using entity inheritance with my CTE entities and this messed up the query generation. When I removed the use of entity iheritance, this issue went away. I created a separate issue #762 for checking the use of entity inheritance in CTE entities.
