### ISSUE TITLE
Raise exception when encountering CTE entities that use entity inheritance

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#762]
CTE entity classes are not allowed to use entity inheritance. This should be checked and a meaningful error message should be generated.

**Comment by JWGmeligMeyling** [comment]
I suppose this primarily applies to the JOINED and UNION strategy? JOINED as we would need to be able to model multiple tables for the CTE and UNION because UNIONs are already reserved for recursive CTE's?

**Comment by beikov** [comment]
@JWGmeligMeyling this happened by accident. One CTE entity extending another CTE entity caused the issue. The fix is to have a mapped superclass and both CTE entities extending that mapped super class.

**Comment by beikov** [comment]
Fixed by 14f6d08
