### ISSUE TITLE
Introduce special comparison operator methods for compile time constants that inline values

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#778]
It is often the case that users make use of the parameterized APIs although they make use of compile-time constants which is an unnecessary burden on many DBMS optimizers.

For example, the following is a common pattern seen in user code

```
cb.where("deleted").eq(false)
```

This will generate a query like `... e.deleted = :param_1` which is problematic for some optimizers. If we were to generate `... e.deleted = false` for these compile-time constant values, this would produce much better query plans.

I'm thinking of introducing companion methods i.e. `eqValue` which would inline the values as literals rather than making use of a parameter. It would also be great if we could suggest a checkstyle rule that detects these inefficient uses and reports the other form.

**Comment by JWGmeligMeyling** [comment]
I have experienced this inconvenience with boolean values myself too. But to what extend does this apply for numeric or string expressions? Those arent really optimizable right?  I try to avoid to use magic variables in my code and I am pretty sure I have little to no occurrences for this except for booleans.

So maybe just introduce isTrue() and isFalse(), which will be fairly trivial to implement, probably just delegate to eqExpression(“true”).

**Comment by beikov** [comment]
For booleans, I have thought of exactly that, but it might still be interesting to support other kinds of literal handling methods for e.g. enums, status codes etc. via a generalized method pattern e.g. `eqValue()`. Other types than boolean have this problem as well in certain domains.
