### ISSUE TITLE
Shade antlr runtime

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#802]
### Description

Shade the antlr runtime since there are many other libraries out there that use antlr as well and we want to avoid conflicts.

### Environment

Version:            
JPA-Provider:       
DBMS:               
Application Server:

**Comment by JWGmeligMeyling** [comment]
I thought this wasnt really an issue because antlr uses different artifact ids for major version releases?

I am not a real fan of shading but as BP is the only library that I use that uses antlr4 I am not really affected by the possibility of loading multiple Antlrs anyway 😄

**Comment by beikov** [comment]
It does, but @heruan used a different minor version which apparently broke backwards compatibility.
