### ISSUE TITLE
CTE support in entity views

### ISSUE THREAD

**Issue by heruan** [Blazebit/blaze-persistence#804]
Currently to use a CTE in an entity view one needs to map a bogus `SubqueryProvider` to be able to issue the `with`/`withRecursive` methods. It would be easier and more straightforward to have a declarative way to do this, for example with a `@With` annotation on the entity view:

```java
@EntityView(MyEntity.class)
@With(cte = MyCte.class, provider = MyCteProvider.class)
interface MyEntityView {

    @MappingCorrelatedSimple(correlated = MyCte.class, ...)
    long someMapping();
	
    @CTE
    @Entity
    class MyCte {
        ...
    }
    
    class MyCteProvider implements CteProvider {
        
        public void bindCte(FullSelectCTECriteriaBuilder builder) {
            builder.from(...).bind("id").select(...).end();
        } 
    }
}
```

The `@With` annotation would have a `recursive` boolean parameter and would be repeatable, e.g.

```java
@EntityView(MyEntity.class)
@With(cte = MyCte.class, provider = MyCteProvider.class)
@With(cte = MyRecursiveCte.class, recursive = true, provider = ...)
interface MyEntityView { ... }
```

**Comment by beikov** [comment]
There are multiple parts to this

* Define annotation and provider interface + tests
* Extend metamodel, annotation reader etc.
* Implement the provider collecting and calling logic in `ViewTypeObjectBuilderTemplate`

I think the first two parts are easily doable for beginners. Just take a look at how the support for the `BatchFetch` annotation is implemented.
