### ISSUE TITLE
HibernateHpqlFunctionAdapter does not support custom types

### ISSUE THREAD

**Issue by JWGmeligMeyling** [Blazebit/blaze-persistence#813]
The problem lies in the statement:

```java
return sfi.getClassMetadata(returnType) != null ? sfi.getTypeHelper().entity(returnType) : sfi.getTypeHelper().custom(returnType);
```

It appears that Hibernate recently started throwing a `MappingException` if `getClassMetadata` gets invoked with a non-managed type.

### Environment

Version:            
JPA-Provider:       
DBMS:               
Application Server:

**Comment by Mobe91** [comment]
What version? This should have been fixed with 18f422a63e9115470625212662d0de1c375dc0c1.

**Comment by JWGmeligMeyling** [comment]
Ah, that should be it, I am still on the latest stable, 1.3.x. I'll test with 1.4.x.

**Comment by JWGmeligMeyling** [comment]
@Mobe91 do you know whether this works for `TypeDefs` by the way?   I am struggeling a bit to get them found by `typeInfo.custom(x)`.

**Comment by Mobe91** [comment]
@JWGmeligMeyling Yes, I think that should also help custom types to be resolved correctly when used as return types in JpqlFunctions.
