### ISSUE TITLE
Make CTEProvider parameterizable

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#814]
Allow a CTEProvider to be parameterized via the EntityViewSettings.

**Comment by heruan** [comment]
What's the purpose of having the map of parameters in the `CTEProvider`? You can still refer to them when binding the CTE. Do you have a use case for this?

**Comment by Mobe91** [comment]
@heruan Afaik not when I want to use .fromValues() for example. This is exactly my use case.

**Comment by Mobe91** [comment]
Maybe it would be better to extend EntityViewSettings to be able to register CteProvider instances there. Then the instances could be parameterized via constructor e.g. and the interface could stay the same.

**Comment by Mobe91** [comment]
As @beikov pointed out, it is possible to parameterize .fromValues() by using the `fromValues(Class<?> valueClass, String alias, int valueCount)` overload.
Nevertheless, registering CteProviders dynamically or allowing to parameterize them could still be useful e.g. if a different version of a cte query should be rendered depending on some parameter.

**Comment by Mobe91** [comment]
@beikov On this matter we decided to pass the optional parameters to the CTEProvider instead of providing means for dynamic registration.
