### ISSUE TITLE
com.blazebit.persistence.view.impl.EntityViewSettingHelper#getName returns fully qualified class name

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#816]
`com.blazebit.persistence.view.impl.EntityViewSettingHelper#getName` uses the fully qualified class name (which includes dots) if the `managedViewTypeImplementor` is not a `ViewType`. Since the dots are not substituted, this causes errors later on when the path is interpreted as a property path. So it would be better to return `managedViewTypeImplementor.getJavaType().getSimpleName()`

**Comment by JWGmeligMeyling** [comment]
Are we sure the name should end up in a property path in the first place?

**Comment by beikov** [comment]
Would you mind explaining where this is problematic @Mobe91 ?
Do you try to fetch a flat view and apply attribute sorters? The workaround would obviously be to mark some attribute as `@IdMapping`. Then the view is no flat view anymore and you don't have that problem. I agree that this is less then ideal and should be fixed. 

I actually don't know anymore what I wanted to do with `ViewType#getName()` so unless we find a use case, we can actually deprecate that and switch to using the class simple name for alias generation.
In JPA, the entity name is used for entity literals and also for from clause items. Even with #252 I can't think of a use case where the view name could be used to refer to a view. Also, we didn't check for uniquness of the name so suddenly doing that would probably lead to requiring setting a proper name on a lot of views.

I'm for deprecating `ViewType#getName()` and using the simple class name here. Any other thoughts?

**Comment by beikov** [comment]
See https://github.com/Blazebit/blaze-persistence/issues/855
