### ISSUE TITLE
Allow subquery provider to have alternative constructors

### ISSUE THREAD

**Issue by Mobe91** [Blazebit/blaze-persistence#826]
Currently, a validation error is throw when a subquery provider with more than 1 constructor is encountered:
```
Caused by: java.lang.IllegalArgumentException: Invalid subquery provider with more than a single constructors:
```
Instead, the validation should only assert that there a zero arguments constructor exists.

**Comment by beikov** [comment]
This was done to enable https://github.com/Blazebit/blaze-persistence/issues/173 which requires us to be able to select a constructor that should be invoked. We can of course adapt the code to not consider constructors that don't have `@MappingParameter` annotations and assert that we have a single constructor or a no-args constructor.
