### ISSUE TITLE
RSQL filter integration

### ISSUE THREAD

**Issue by j0nm1** [Blazebit/blaze-persistence#828]
Hi,
I just wanted to ask, if it's possible to combine this library with rsql (https://github.com/jirutka/rsql-parser) or even this on https://github.com/tennaito/rsql-jpa.
In the basic examples of rsql-jpa they use a CriteriaQuery but I am afraid that blazebit expects a CriteriaBuilder and is therefore incompatible. 
I also inspected the docs but didn't find anything.

Am I missing something?

**Comment by JWGmeligMeyling** [comment]
RSQL seems to use the JPA Criteria API. @beikov wrote a JPA Criteria API wrapper for blaze-persist. Can you check if that works? https://github.com/Blazebit/blaze-persistence/tree/master/jpa-criteria

**Comment by beikov** [comment]
IMO this should be easily possible with the example that is shown here: https://github.com/tennaito/rsql-jpa#jpapredicatevisitor-class

```
// We will need a JPA EntityManager
EntityManager manager;
// We will need a Blaze-Persistence Core CriteriaBuilderFactory
CriteriaBuilderFactory criteriaBuilderFactory;

// Create criteria and from 
BlazeCriteriaBuilder builder = BlazeCriteria.get(criteriaBuilderFactory);
BlazeCriteriaQuery<Course> criteria = builder.createQuery(Course.class);
From root = criteria.from(Course.class);

// Create the JPA Predicate Visitor
RSQLVisitor<Predicate, EntityManager> visitor = new JpaPredicateVisitor<Course>().defineRoot(root);

// Parse a RSQL into a Node
Node rootNode = new RSQLParser().parse("id==1");

// Visit the node to retrieve CriteriaQuery
Predicate predicate = rootNode.accept(visitor, manager);

// Use generated predicate as you like
criteria.where(predicate);

// Execute and get results
List<Course> courses = criteria.getResultList();
```

If you still have question, please reopen the issue
