### ISSUE TITLE
Integrating criteria api with client side via REST

### ISSUE THREAD

**Issue by avifatal** [Blazebit/blaze-persistence#835]
Hi,
Do you have serializable query objects so I can automate the work from the client via rest?
I want to pass from the client a query similar to this very clumsy JSON:

```
{
  pageSize: 50,
  nextResult: 250,
  query:{
    [
      { and: [
         { prop: 'name', comparer: 'eq', value: 'ron'},
         { prop: 'age', comparer: 'gt', value: 31'},
      ], or:  [
         { prop: 'name', comparer: 'eq', value: 'ron'},
         { prop: 'age', comparer: 'gt', value: 31'},
      ],
  }
```
this way I can actually expose a queryable criterion object to the client and avoid writing methods to translate each search criteia to the Blazebit api.

Possible?
Thanks

**Comment by beikov** [comment]
We have integrations with Spring Data JPA and Spring MVC as well as DeltaSpike Data and JAX-RS with which you can achieve similar things. Also see the examples here

* https://github.com/Blazebit/blaze-persistence/tree/master/examples/spring-data-rest
* https://github.com/Blazebit/blaze-persistence/tree/master/examples/deltaspike-data-rest

There is no completely generic interface that we provide, although we are considering exposing Blaze-Persistence Entity-View structures via GraphQL: https://github.com/Blazebit/blaze-persistence/issues/373

Still, that requires you to define the scope via Java interfaces that are projections of JPA entities. I personally doubt that you will be happy with a generic approach in a real world project, but if that is what you are looking for, you would have to look for a different solution as Blaze-Persistence is a library that helps you write efficient queries/projections in a declarative and easy to maintain manner.

**Comment by beikov** [comment]
I'll close this for now. If you have any further questions, feel free to reopen the issue
