### ISSUE TITLE
Out of memory after activating Blaze-Permission

### ISSUE THREAD

**Issue by EugenMayer** [Blazebit/blaze-persistence#849]
### Description
After activating BP i get a OOM heap exception on a test.
This tests writes about 70k records batched:

```java

    Lists.partition(allPermissions, 1000).forEach(chunk -> {
      entityManager.flush();
      entityManager.clear();
      chunk.forEach(entityManager::persist);
    });
```

`allPermissions` is a `Collection of `PermissionCache` entries looking like this

```java
@Entity
@Data
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@NoArgsConstructor(access = AccessLevel.PRIVATE)
@AllArgsConstructor
public class PermissionCache
{
  @EmbeddedId
  @EqualsAndHashCode.Include
  PermissionCacheId permissionId = new PermissionCacheId();

  public PermissionCache(final Long spaceId, final Long uid)
  {
    this.permissionId.setSpaceId(spaceId);
    this.permissionId.setUid(uid);
  }
}
```

And the EmbeddedId is

```java
@Data
@Embeddable
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
public class PermissionCacheId implements Serializable
{
  @EqualsAndHashCode.Include
  @Column(name = "space_id", columnDefinition = "INT(11)")
  private Long spaceId;

  @EqualsAndHashCode.Include
  @Column(name = "uid", columnDefinition = "INT(11)")
  private Long uid;
}
```

I'am using batched writes with 

`useServerPrepStmts=false&rewriteBatchedStatements=true` 
on the JDBC URL and

```
spring.jpa.properties.hibernate.jdbc.batch_size=1000
# suppress inspection "SpringBootApplicationProperties"
hibernate.jdbc.batch_size=1000
```

In the properties

I understand that batch size can be one of the reasons here - but since that code has never thrown an OOM ever yet, and does so with BP, i suspect a memory leak we are yet not aware of

### Expected behavior
Perform the same way as without BP

### Actual behavior
OOM exception

```

  org.springframework.jdbc.datasource.init.UncategorizedScriptException: Failed to execute database script; nested exception is java.lang.OutOfMemoryError: Java heap space

  Caused by: java.lang.OutOfMemoryError: Java heap space
```

Full stacktace: https://dpaste.de/ociG

### Steps to reproduce
Probably use the describe Entity with a simple `JpaRepository` (save/saveAll not overriden)
Write arround 70k entries batched in one session

### Environment
Version: 9.9-snapshot based on non-HEAD #846
JPA-Provider: hibernate 5.4.5
DBMS: mariadb10.3
Application Server: spring boot 2.1.7

**Comment by beikov** [comment]
AFAICS blaze-persistence is not involved in this test, so the reason for this error has to be a different one. You will require a little more, but constant amount, of memory when using blaze-persistence because it has it's own metadata, but depending on your model, this would be at most a few MBs

**Comment by EugenMayer** [comment]
@beikov i would love to believe that - but enable PB, test fails. disable BP test ist alright.

100% reproduceable, each and every time. I checked, the test yet never failed before BP was introduced ( several months ).

So i would really think there is something that happens which you did not expect to happen or something. 

E.g. i would expect, since that is EM, that efter each flush, all batched entries are loaded - and that will most probably utilize the repo, but this one uses your new BPrepoFactory - so it might be involved here, could that be possible?

**Comment by EugenMayer** [comment]
@JWGmeligMeyling i checked the maximum heap size and if i get this all right it is 8GB

```
java -verbose:sizes -version
  -Xmca32K        RAM class segment increment
  -Xmco128K       ROM class segment increment
  -Xmcrs200M      compressed references metadata initial size
  -Xmns2M         initial new space size
  -Xmnx939904K    maximum new space size
  -Xms8M          initial memory size
  -Xmos6M         initial old space size
  -Xmox3758016K   maximum old space size
  -Xmx3760064K    memory maximum
  -Xmr16K         remembered set size
  -Xlp:objectheap:pagesize=4K	 large page size
                  available large page sizes:
                  4K
  -Xlp:codecache:pagesize=4K	 large page size for JIT code cache
                  available large page sizes for JIT code cache:
                  4K
  -Xmso256K       operating system thread stack size
  -Xiss2K         java thread stack initial size
  -Xssi16K        java thread stack increment
  -Xss1M          java thread stack maximum size
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Linux amd64-64-Bit Compressed References 20190717_286 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)
```

The test server has 14GB of ram, so most probabl 8GB could have been used.

On the other side i found out that running the test isolated ( test class or just the method ) i will not get the OOM - it seems when i run all integration tests in a suite this happens. What i would deduct is:
 
 - it might be a different tests and therefor other codebase being the reason for the OOM ( one that runs before )
 - it is harder to find out for me

Are you guys used to work with the core dumps?

```
JVMDUMP039I Processing dump event "systhrow", detail "java/lang/OutOfMemoryError" at 2019/09/20 21:10:37 - please wait.
JVMDUMP032I JVM requested System dump using '/dwcore_java/core.20190920.211037.175.0001.dmp' in response to an event
JVMDUMP010I System dump written to /dwcore_java/core.20190920.211037.175.0001.dmp
JVMDUMP032I JVM requested Heap dump using '/dwcore_java/heapdump.20190920.211037.175.0002.phd' in response to an event
JVMDUMP010I Heap dump written to /dwcore_java/heapdump.20190920.211037.175.0002.phd
JVMDUMP032I JVM requested Java dump using '/dwcore_java/javacore.20190920.211037.175.0003.txt' in response to an event
JVMDUMP010I Java dump written to /dwcore_java/javacore.20190920.211037.175.0003.txt
JVMDUMP032I JVM requested Snap dump using '/dwcore_java/Snap.20190920.211037.175.0004.trc' in response to an event
JVMDUMP010I Snap dump written to /dwcore_java/Snap.20190920.211037.175.0004.trc
```

The coredump is 1.3GB so fairly hard to share but maybe the Snap / javacore / heapdump ? 

You would need 
 - https://www.eclipse.org/mat/downloads.php
 - And there install https://help.eclipse.org/2019-03/index.jsp?topic=%2Forg.eclipse.mat.ui.help%2Ftasks%2FinstallDTFJ.html  since it is a phd not an hprof

I tried to open the heapdump but i could not due to 

`Parsing heap dump from '/home/em/Downloads/oom/heapdump.20190920.211037.175.0002.phd'`

Eventhough i am able to open the format, it is recognised. I could run the test on a non openj0 jvm so we might have a usual hprof dump, but maybe you guys have a better / another idea.

Here are the heapdump/javacore and snap https://we.tl/t-riiWkh2Kyl

**Comment by EugenMayer** [comment]
I was able to open the PHD, it just took long and should me the error from the previous try during that .. software...

Interestingly the coredump shows that about 280MB have been used, nothing about 8GB

`Size: 270.5 MB Classes: 20.8k Objects: 5.3m Class Loader: 578`

So i either missunderstand the heap size calculation or something else goes on.

Those are the openj9 flags i start the tests with:

```
  if (project.hasProperty('debug')) {
        jvmArgs = ["-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=*:5007"]
    }

    // hide all the refelction access warnings during compile
    //allow embedded executer to modify environment variables
    jvmArgs += "--add-opens=java.base/java.util=ALL-UNNAMED"
    //allow embedded executer to inject legacy types into the system classloader
    jvmArgs += "--add-opens=java.base/java.lang=ALL-UNNAMED"

    // ****************************************************
    // ************* speed optimization *******************
    // ****************************************************
    jvmArgs += "-noverify"

    // ************************** openj9 only
    // openj9 only
    // start quicker

    jvmArgs += "-Xquickstart"
    // optimize for containers
    jvmArgs += "-Xtune:virtualized"
    // use shared cache
    jvmArgs += "-Xshareclasses:cacheDir=/tmp/cache -XX:SharedCacheHardLimit=200m -Xscmx100m "
``

I seem to not override the heap size at all?

**Comment by JWGmeligMeyling** [comment]
with  “ java -XX:+PrintFlagsFinal -version | grep -iE 'HeapSize|PermSize|ThreadStackSize'” you should be able to view the heap size used, I doubt its 8GB, because your dump is much smaller. Let me try to open it in Jprofiler.

**Comment by EugenMayer** [comment]
At least the first analysis shows involvment of BP:

![image](https://user-images.githubusercontent.com/136934/65370157-03c43800-dc56-11e9-8cb1-75cad13935df.png)

![image](https://user-images.githubusercontent.com/136934/65370178-3d953e80-dc56-11e9-933f-fe374b5f9e3c.png)

![image](https://user-images.githubusercontent.com/136934/65370204-7df4bc80-dc56-11e9-87e2-95875d157f9e.png)

**Comment by EugenMayer** [comment]
i think that does not work with openj9 @JWGmeligMeyling 

```
java -XX:+PrintFlagsFinal -version | grep -iE 'HeapSize|PermSize|ThreadStackSize'
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.15.1, JRE 11 Linux amd64-64-Bit Compressed References 20190717_286 (JIT enabled, AOT enabled)
OpenJ9   - 0f66c6431
OMR      - ec782f26
JCL      - fa49279450 based on jdk-11.0.4+11)
```

**Comment by Mobe91** [comment]
@beikov wth is `com.blazebit.persistence.spring.data.base.repository.EntityViewAwareCrudMethodMetadataPostProcessor#INTERCEPTOR_CACHE`?

**Comment by Mobe91** [comment]
I guess the issue is that references to EntityViewManager remain cached in `com.blazebit.persistence.spring.data.base.repository.EntityViewAwareCrudMethodMetadataPostProcessor#INTERCEPTOR_CACHE`. Every test case probably creates a new entity view manager instance. Since the entity view manager references all kind of stuff this accumulates a large memory footprint over time. 
The cached `com.blazebit.persistence.spring.data.base.repository.EntityViewAwareCrudMethodMetadataPostProcessor.CrudMethodMetadataPopulatingMethodInterceptor` instances again hold references to the entity view manager - also a problem.

**Comment by JWGmeligMeyling** [comment]
Seems a good use candidate for a `WeakHashMap` I think

**Comment by Mobe91** [comment]
Yes, using `WeakHashMap` here should fix it.

**Comment by EugenMayer** [comment]
@Mobe91 sounds about very right, just checked the code too. I think due to the nature of the tests, that thing is just never freed and GC cannot handle, so it just sums up until it blows up the heap.

Still, also in a production env, this should get freed from time to time, otherwise this is pure addtive for the whole runtime - when i understand this correctly, doing X requests on a e.g. rest controller would create X EVM which then never get freed also, right?

**Comment by EugenMayer** [comment]
Wow, was not even aware of a build in feature like https://docs.oracle.com/javase/7/docs/api/java/util/WeakHashMap.html .. nice learning and sounds about exactly what might be needed

**Comment by Mobe91** [comment]
But be careful, `WeakHashMap` is not thread-safe so it cannot be directly used to replace INTERCEPTOR_CACHE here.

**Comment by Mobe91** [comment]
@EugenMayer 
>Still, also in a production env, this should get freed from time to time, otherwise this is pure addtive for the whole runtime - when i understand this correctly, doing X requests on a e.g. rest controller would create X EVM which then never get freed also, right?

No, in a production environment you would typically have 1 instance of entity view manager per entity manager factory. So this should only cause issues in your test environment.

**Comment by EugenMayer** [comment]
Couldnt we not just cleanup the EMV instance properly on context destoy?

`ServletContextListener`

with 

`public void contextDestroyed(ServletContextEvent event)`

Or by registering to `SessionFactoryObserver` which is getting a signal on `EMF.close` AFAICs in `org.hibernate.internal.SessionFactoryImpl#close`

**Comment by Mobe91** [comment]
@JWGmeligMeyling 
Actually, I do not think using a variant of `WeakHashMap` is sufficient here because the map values hold references to the entity view manager which prevents it to be garbage collected - so not map entries would be removed.

**Comment by Mobe91** [comment]
@EugenMayer 
The entity manager view itself does not have a cleanup functionality so your only bet is to make the entity view manager instances finalizable by the garbage collector. For this, you would need to manually call clear() on the `com.blazebit.persistence.spring.data.base.repository.EntityViewAwareCrudMethodMetadataPostProcessor#INTERCEPTOR_CACHE` - assuming that this is the only place where entity manager view instances are cached. For the time being, you can obtain a reference to `INTERCEPTOR_CACHE` via reflection an clear it manually. That should fix it.

**Comment by JWGmeligMeyling** [comment]
Ah yes, I forgot about the EVM references everywhere. I think this should address that:

```diff
diff --git a/integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/repository/EntityViewAwareCrudMethodMetadataPostProcessor.java b/integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/repository/EntityViewAwareCrudMethodMetadataPostProcessor.java
index 2ce085c75..0f5e2c98b 100644
--- a/integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/repository/EntityViewAwareCrudMethodMetadataPostProcessor.java
+++ b/integration/spring-data/base/src/main/java/com/blazebit/persistence/spring/data/base/repository/EntityViewAwareCrudMethodMetadataPostProcessor.java
@@ -41,10 +41,12 @@ import org.springframework.util.ClassUtils;
 
 import javax.persistence.LockModeType;
 import javax.persistence.QueryHint;
+import java.lang.ref.WeakReference;
 import java.lang.reflect.Method;
 import java.util.Collections;
 import java.util.HashMap;
 import java.util.Map;
+import java.util.WeakHashMap;
 import java.util.concurrent.ConcurrentHashMap;
 import java.util.concurrent.ConcurrentMap;
 
@@ -59,7 +61,7 @@ import java.util.concurrent.ConcurrentMap;
  */
 public class EntityViewAwareCrudMethodMetadataPostProcessor implements RepositoryProxyPostProcessor, BeanClassLoaderAware {
 
-    private static final ConcurrentMap<EntityViewManager, MethodInterceptor> INTERCEPTOR_CACHE = new ConcurrentHashMap<>();
+    private static final Map<EntityViewManager, MethodInterceptor> INTERCEPTOR_CACHE = Collections.synchronizedMap(new WeakHashMap<>());
     private final MethodInterceptor interceptor;
     private ClassLoader classLoader = ClassUtils.getDefaultClassLoader();
 
@@ -119,10 +121,10 @@ public class EntityViewAwareCrudMethodMetadataPostProcessor implements Repositor
     private static final class CrudMethodMetadataPopulatingMethodInterceptor implements MethodInterceptor {
 
         private final ConcurrentMap<EntityViewMetadataCacheKey, EntityViewAwareCrudMethodMetadata> metadataCache = new ConcurrentHashMap<>();
-        private final EntityViewManager evm;
+        private final WeakReference<EntityViewManager> evmReference;
 
         private CrudMethodMetadataPopulatingMethodInterceptor(EntityViewManager evm) {
-            this.evm = evm;
+            this.evmReference = new WeakReference<>(evm);
         }
 
         /*
@@ -141,7 +143,7 @@ public class EntityViewAwareCrudMethodMetadataPostProcessor implements Repositor
             EntityViewAwareCrudMethodMetadata methodMetadata = metadataCache.get(cacheKey);
 
             if (methodMetadata == null) {
-                methodMetadata = new EntityViewAwareDefaultCrudMethodMetadata(cacheKey.proxyClass, method, evm);
+                methodMetadata = new EntityViewAwareDefaultCrudMethodMetadata(cacheKey.proxyClass, method, evmReference.get());
                 EntityViewAwareCrudMethodMetadata tmp = metadataCache.putIfAbsent(cacheKey, methodMetadata);
 
                 if (tmp != null) {
```

**Comment by JWGmeligMeyling** [comment]
I'm not sure why we even need the cache though. There seems a 1:1 relation between `BlazePersistenceRepositoryFactory`, `EntityViewManager` and `EntityViewAwareCrudMethodMetadataPostProcessor`. Aren't these all effectively singleton?

**Comment by Mobe91** [comment]
@JWGmeligMeyling I got the same impression. Spring's original `org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor` does not have a global method metadata cache either, it just caches locally in the interceptor. That should also be sufficient for `EntityViewAwareCrudMethodMetadataPostProcessor`. Maybe @beikov can shed some light into this?

**Comment by beikov** [comment]
In spring data 1.x `CrudMethodMetadataPopulatingMethodInterceptor` was implemented as singleton and I simply tried to do it like spring data did it. I'll fix that.

**Comment by EugenMayer** [comment]
I guess it is time for me to have an own develop branch with #843 seems to become a integration branch :) i will rebuild to 9-12 and try to test this. Thank you guys for working this one out!

**Comment by EugenMayer** [comment]
This fixed this oom and nothing else broke on our side! Thank you
