### ISSUE TITLE
Test flush of a declared readonly flat view with an updatable flat view object

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#859]
An updatable type declares an attribute with a readonly flat view type but should be allowed to accept an updatable flat view object and also properly flush it when being configured to do so.
Currently, the flush fails with an index out of bounds exception when annotating the attribute with `@UpdatableMapping` which I think is related to the fact that we don't select the composite flusher based on the runtime type but rather on the declared type.

```
@UpdatableEntityView
@EntityView(SomeEntity.class)
interface View {
  @UpdatableMapping
  ReadonlyFlatView getEmbeddable();
}

@EntityView(SomeEmbeddable.class)
interface ReadonlyFlatView {
  String getAttr1();
}

@UpdatableEntityView
@EntityView(SomeEmbeddable.class)
interface UpdatableFlatView extends ReadonlyFlatView {
  void setAttr1(String attr1);
}
```

Without the `@UpdatableMapping`, setting the instance is successful, but not flushed. IMO it might be better to fail with an exception in such a case. Or should we consider the attribute as updatable i.e. not require the `@UpdatableMapping` since a setter exists?

**Comment by heruan** [comment]
> Without the `@UpdatableMapping`, setting the instance is successful, but not flushed. IMO it might be better to fail with an exception in such a case. Or should we consider the attribute as updatable i.e. not require the `@UpdatableMapping` since a setter exists?

I'd go with the latter, can't think of scenarios where it's not what the developer expects.

**Comment by beikov** [comment]
In fact, the latter is what we do for normal entity views, so it seems reasonable to do the same for flat views.
