### ISSUE TITLE
Support controlling whether empty flat views or null should be produced

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#860]
Currently we always initialize flat views as empty objects which is especially nice for updatable flat views and matches what hibernate does by default, but it might be desirable to support initializing null instead. You could null it down in the constructor as a workaround for now, but a general mechanism would be nice.
Maybe we can think of a mechanism to control the "null object" in general as there were requests for custom default values in the past. How about using a default method implementation for that purpose? We need the user to annotate that method then to make the intent clear though. I'm not sure if the following is a good, idea, probably it's better to have a special annotation i.e. `@DefaultValue` or something like that. Any thoughts?

```
@EntityView(SomeEntity.class)
interface TestView {
  @Mapping
  default String getName() {
    return "the default";
  }
}
```

**Comment by heruan** [comment]
I like using default methods! Must be clear though that the method won't be invoked if the database returns a non-null value. Could be something like:

```java
@EntityView(SomeEntity.class)
interface TestView {

    String getFoo(); // if null on database: null (default)

    @Mapping
    default String getBar() {  // if null on database: "bar"
        return "bar";
	}

    @Mapping(createEmptyComposites = false)
    Embeddable getEmbedded(); // if empty on database: null

}
```
