### ISSUE TITLE
Add @Repeatable to some annotations

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#861]
We already compile with JDK8+ and even when running on Java 7, using the `@Repeatable` annotation shouldn't be a problem as non-existing annotations shouldn't pose a problem for class loading. We might still want to make sure this boots properly, as I'm not sure how CDI behaves in such a case, but I doubt this is an issue.

So in the end, we would simply have to annotate `@Repeatable` on a few annotations and test that locally if it works properly with a Java 7 runtime.

**Comment by EugenMayer** [comment]
Would be great on `ViewFilter`, `AttributeFilter` (more to come)
