### ISSUE TITLE
Add documentation section about Jackson, Spring MVC, DeltaSpike Data JAX-RS and JAX-RS integrations

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#916]
We are currently lacking documentation sections for these integrations. The sections can be very small but should contain at least the dependency information and a few words.

The Jackson integration should document the `com.blazebit.persistence.integration.jackson.EntityViewAwareObjectMapper` and that it can be used for deserializing. Create view types are created with `evm.create()`, other types via `evm.getReference()`.

The Spring MVC/Data integration offers the `@KeysetConfig` annotation and generally supports injecting `KeysetPageable` objects. Maybe mention the `com.blazebit.persistence.spring.data.rest.impl.KeysetPageableHandlerMethodArgumentResolver` is used and can be customized.
It depends on the Jackson integration and contributes the `com.blazebit.persistence.spring.data.rest.impl.json.EntityViewAwareMappingJackson2HttpMessageConverter`.

The JAX-RS integration is currently just about adding support for the Jackson integration.

The DeltaSpike Data JAX-RS integration adds support for `@KeysetConfig` just like the Spring MVC/Data integration and also integrates the JAX-RS integration. The DeltaSpike Data JAX-RS integration API also offers annotations like `PageableDefault` and `SortDefault` similar to what Spring Data supports.

**Comment by EugenMayer** [comment]
Could you give me an idea how to work on the docs - what format, how to contribute those and so on. I guess https://github.com/Blazebit/blaze-persistence/tree/master/documentation

i guess https://github.com/Blazebit/blaze-persistence/tree/master/documentation/src/main/asciidoc/core/manual/en_US

Any preferred section?

**Comment by beikov** [comment]
Right, I would prefer a new chapter i.e. file like e.g. `12_spring_data.adoc`, notice that you will have to rename a few sections e.g. from `12_spring_data.adoc` to `13_spring_data.adoc` and update the `index.adoc` if you introduce new chapters in between.
I'd say we introduce a chapter about integrations and as soon as the integrations "grow too large" we introduce a new chapter for them. The Spring Data and DeltaSpike Data integrations are quite big, that's why they have their own chapters, but the Jackson and JAX-RS integration are quite small. We can also work with a single integrations chapter and put every integration there, but I personally don't see a normal user using e.g. the Jackson integration directly. This should be consumed via the JAX-RS or the Spring MVC/Data integration which is why I wouldn't create a separate chapter for that, but you are free to propose a different style if you have a better idea :)

**Comment by EugenMayer** [comment]
I can try to help with the Spring Data part, i do not know DeltaSpike so that one maybe can be taken on by someone else.

I have to understand the integration first and read the docs of that section so i can make up my mind about this. I will try to do so on the weekend and see what i can do with it.

**Comment by beikov** [comment]
Thanks, having the Jackson and Spring parts would be a very big help.

**Comment by beikov** [comment]
Fixed by 1bf129fd5aa61d75ad68789d2367c5c8ecc9a472
