### ISSUE TITLE
Create Spring HATEOAS integration for keyset pagination

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#917]
In Spring 2.2+ which is IMO the only version we should support here, the contracts changed completely. It seems it is intended to inject a `PagedResourcesAssembler` parameter to the controller method which can then be used to transform a `Page` to a `PagedModel`. That also adds the links since it knows the URI and the page numbers.

We will have to essentially duplicate this for the `KeysetAwarePage` and add additional parameters as needed.

**Comment by ask4gilles** [comment]
Hi @beikov,

To follow up on https://github.com/Blazebit/blaze-persistence/issues/1080#issuecomment-628873792

First, thank you for taking the time to have a look at this, I really appreciate!

> With a KeysetAwarePage, which you can declare as return type in your repository method, you can construct the JSON structure that is expected for a @KeysetConfig parameters and finally also construct the prev and next links to use keyset pagination.

Yes, that's exactly the setup I'm currently using.

So, here is some pseudo code of what I'm currenlty using:
A controller woulkd look like:
```
@GetMapping("search")
        public ResponseEntity<List<MyDto>> search (MyFilter myFilter,
                @SortDefault.SortDefaults({
                        @SortDefault(sort = "someField"),
                        @SortDefault(sort = "someOtherField"),
                        @SortDefault(sort = "againAnotherField")
                })
                @KeysetConfig(MyEntity.class)
                        KeysetPageable keysetPageable,
                PagedResourcesAssembler <MyDto> assembler){
            KeysetAwarePage<MyDto> response = interactor.search(myFilter, keysetPageable);

            HttpHeaders responseHeaders = pagingHeadersFactory.create(response,
                    linkTo(MyRestController.class).slash("search").withSelfRel());

            return new ResponseEntity<>(response.getContent(), responseHeaders, HttpStatus.OK);
        }
```
To construct the headers, I'm currently using: (own interface)
```
import org.springframework.data.domain.Page;
import org.springframework.hateoas.Link;
import org.springframework.http.HttpHeaders;

public interface PagingHeadersFactory<T> {

    HttpHeaders create(Page<T> page, Link selfLink);
}
```
And currently, an offset implementation...
```
public class OffsetPagingHeadersFactory<T> implements PagingHeadersFactory<T> {

    private final PagedResourcesAssembler<T> assembler;

    public OffsetPagingHeadersFactory(PagedResourcesAssembler<T> assembler) {
        this.assembler = assembler;
    }

    @Override
    public HttpHeaders create(Page<T> page, Link selfLink) {
        List<String> links = new ArrayList<>();
        HttpHeaders responseHeaders = new HttpHeaders();

        if (page != null) {

            PagedModel<EntityModel<T>> pagedModel = assembler.toModel(page, selfLink);

            addLink(links, pagedModel, IanaLinkRelations.FIRST_VALUE);
            addLink(links, pagedModel, IanaLinkRelations.PREVIOUS_VALUE);
            addLink(links, pagedModel, IanaLinkRelations.NEXT_VALUE);
            addLink(links, pagedModel, IanaLinkRelations.LAST_VALUE);

            if (!links.isEmpty()) {
                responseHeaders.add(HttpHeaders.LINK, gatherLinkHeaders(links.toArray(new String[0])));
            }

            responseHeaders.add("X-Total-Count", String.valueOf(page.getTotalElements()));
        }

        return responseHeaders;
    }

    private void addLink(List<String> links, PagedModel<EntityModel<T>> pagedModel, String rel) {
        if (pagedModel.getLink(rel).isPresent()) {
            links.add(createLinkHeader(pagedModel.getLink(rel).get().getHref(), rel));
        }
    }

    private String createLinkHeader(String uri, String rel) {
        return "<" + uri + ">; rel=\"" + rel + "\"";
    }

    private String gatherLinkHeaders(String... uris) {
        return String.join(",", uris);
    }
```
>  I could provide a utility to create this JSON string, but I think that's about all an integration could do. Do you have any ideas how we could integrate here? Maybe you know a bit more than me about Spring HATEOAS, I have never used it before, but I don't know if or how I can get the URL for the current resource and replace a query parameter in that URL. If such a thing is possible, we could try to do that in the integration.

Indeed, that's what I tried to do: using the link provided by the pageAssembler in order to concat values from the page so that they are handled on subsequent requests by the `KeysetPageableHandlerMethodArgumentResolver`. But I failed miserably...
Probably because I was using the wrong values...

Here is what I tried to do in a KeysetPagingHeadersFactory implementation... before giving up :)
```
    @Override
    public HttpHeaders create(UUID correlationId, Page<T> page, Link selfLink) {
        List<String> links = new ArrayList<>();
        HttpHeaders responseHeaders = new HttpHeaders();

        KeysetAwarePageImpl<T> keysetAwarePage = (KeysetAwarePageImpl<T>) page;
        KeysetPage keysetPage = keysetAwarePage.getKeysetPage();
        try {
            PagedModel<EntityModel<T>> pagedModel = assembler.toModel(page, selfLink);
            String offset = String.valueOf(keysetAwarePage.getPageable().getOffset());
            String[] lowestTuple = objectMapper.readValue(objectMapper.writeValueAsString(keysetPage.getLowest().getTuple()), String[].class);
            String lowest = lowestTuple[0];
            String[] highestTuple = objectMapper.readValue(objectMapper.writeValueAsString(keysetPage.getHighest().getTuple()), String[].class);
            String highest = highestTuple[0];


            if (pagedModel.getLink(IanaLinkRelations.NEXT_VALUE).isPresent()) {
                long currentPage = pagedModel.getMetadata().getNumber();
                long previousPage = currentPage - 1;
                String prevPage = String.valueOf(previousPage);
                String href = selfLink.getHref().concat("?page=" + currentPage + "&prevPage=" + prevPage + "&lowest=\"" + lowest + "\"&highest=\"" + highest + "\"");
                links.add(createLinkHeader(href, IanaLinkRelations.NEXT_VALUE));
            }

        } catch (JsonProcessingException e) {
            e.printStackTrace();
        }

        if (!links.isEmpty()) {
            responseHeaders.add(HttpHeaders.LINK, gatherLinkHeaders(links.toArray(new String[0])));
        }

        responseHeaders.add("X-totalElements", String.valueOf(keysetAwarePage.getTotalElements()));

        return responseHeaders;
    }
```
I hope it gives you a bit more context and food for thought :)

**Comment by beikov** [comment]
I'm currently working on supporting the KeysetAwarePage through something similar to the `PagedResourcesAssembler`. Would that be enough for you already? I guess you could move the links to the HTTP headers then if you like, but as far as I understand HATEOAS, the `RepresentationModelAssembler` is the abstraction that should be used here.

**Comment by ask4gilles** [comment]
Of course, I'm just using it because I  didn't find a better alternative yet.

**Comment by beikov** [comment]
I worked on the integration today and it looks like it works out. You can try it out here: https://github.com/Blazebit/blaze-persistence/pull/1092

Would love to hear some feedback!

**Comment by ask4gilles** [comment]
I’ll do next week for sure, thanks again!
