### ISSUE TITLE
Support Spring PathVariable and JAX-RS PathParams in the integrations for updatable entity views

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#923]
Currently we require the identifier to be part of the message body which is bad. IMO we should use a path variable or path param. We could do that somehow with interecptors pushing the value on a thread local for spring. In JAX-RS I think we have access to the UriInfo.

**Comment by EugenMayer** [comment]
We already do both aspects in our application, means "Interceptor + method annotation + path variable extraction + thread local" - so i could provide an implementation for that fairly easy

**Comment by beikov** [comment]
That would be awesome :)

**Comment by EugenMayer** [comment]
Could you write a littel specification of your needs?

E.g the annotation we provide you define which index the path variable has, which should be used as an id variable, usually this is 0 ( first path variable ) - this is what we could also do.

How should the annotation look like here? What would you like the thread local class to be named?

**Comment by beikov** [comment]
I'd like to introduce an annotation e.g. 

```
package com.blazebit.persistence.spring.data.rest;

@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.PARAMETER)
public @interface EntityViewId
```

The implementation for extracting the argument value should live in `com.blazebit.persistence.spring.data.rest.impl` and could look like

```
final class PathVariableHolder {

  static final ThreadLocal<Object> VALUE = new ThreadLocal<>();

  private PathVariableHolder () {
  }

}
```

The interceptor would do something like

```
Object pathVariable = ...
PathVariableHolder.VALUE.set(pathVariable);
try {
  intercepted.invoke();
} finally {
  PathVariableHolder.VALUE.remove();
}
```

and in `com.blazebit.persistence.spring.data.rest.impl.json.EntityViewAwareMappingJackson2HttpMessageConverter` we can then set the id via `((MutableStateTrackable) deserializedObject).$$_setId(PathVariableHolder.VALUE.get())`.
