### ISSUE TITLE
Should EntityViewConfiguration be a Bean

### ISSUE THREAD

**Issue by EugenMayer** [Blazebit/blaze-persistence#924]
In a spring boot / spring context the usual

```java
  @Bean
  @Scope(ConfigurableBeanFactory.SCOPE_SINGLETON)
  @Lazy(false)
  public EntityViewManager entityViewManager(
    CriteriaBuilderFactory cbf,
    EntityViewConfiguration entityViewConfiguration
  )
  {
    return entityViewConfiguration.createEntityViewManager(cbf);
  }
```

EVM bean exposure leads to an warning that `EntityViewConfiguration` is not a bean (which in fact it is not )

I ask myself, are thre any frameworks `EntityViewConfiguration` is used as a non Bean? If not, can we just annotate it as a `Bean` ?

If it the answer is yes, could we provide a default bean exposure of `EntityViewConfiguration` in the spring implementation?

**Comment by beikov** [comment]
There is a bean definiton in `com.blazebit.persistence.integration.view.spring.impl.EntityViewConfigurationProducer`. I don't know what this warning/error is about, but I don't know enough about Spring to be able to resolve this. I mean it works after all, so not sure why you get this message. Maybe @heruan know something?

**Comment by heruan** [comment]
Is the warning present only on IntelliJ? On Eclipse I do not have any warnings about that. In the Spring implementation, the `EntityViewConfiguration` is in fact exposed as a bean by `EntityViewConfigurationProducer` so the warning makes no sense. Maybe it's just IntelliJ not detecting the producer?

**Comment by beikov** [comment]
Thanks for looking into this @heruan 
It is _just_ an IntelliJ warning, but I wanted to make sure if you as a Spring-Pro have a clue about what this could be :)
Unless someone has an idea how to fix this, I'll close this issue
