### ISSUE TITLE
equals() check on CreateViews of same type are always true

### ISSUE THREAD

**Issue by sullrich84** [Blazebit/blaze-persistence#936]
`CreateViews` of the same type always return `true` on `equals()` check, even if respective field values differ. 

    var foo1 = entityViewManager.create(FooCreateView.class);
    foo1.setFoo("abc");

    var foo2 = entityViewManager.create(FooCreateView.class);
    foo2.setFoo("def");

    foo1.equals(foo2); // true

**Comment by beikov** [comment]
How do these create views look like? The equals method is based on identity equality for normal views or full state equality for flat views.
I assume both instances have the same identifier then?

**Comment by jwgmeligmeyling** [comment]
The views are in unmanged state, so the identifier for both views will be null. This is the traditional JPA equals problem: https://vladmihalcea.com/how-to-implement-equals-and-hashcode-using-the-jpa-entity-identifier/ . Perhaps for unmanaged create views you should fall back to instance based equality (i.e. `super.equals`).

**Comment by beikov** [comment]
In fact, we assume `null != null` when considering ids. The implementation is actually pretty much what you would expect, but I can't say for sure what is going on unless I see the definitions or how it is used.

**Comment by jwgmeligmeyling** [comment]
Hmm interesting, then we’ll need a reproducer 🤷‍♂
