### ISSUE TITLE
Add support for non-primary key associations in updatable entity views

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#940]
Currently, we only support updating associations that use the primary key for the association mapping which can be limiting in various ways. We should add support for non-primary key mappings.
As part of this, we will do some preliminary work on natural id support, but for that to work fully, we still need a few additional adaptions.

**Comment by EugenMayer** [comment]
I would love to see that one implemented - but yes there is so much wishing in here, isn't it :) Thanks for taking on all those issue!
