### ISSUE TITLE
GSON deserialization of Views

### ISSUE THREAD

**Issue by j0nm1** [Blazebit/blaze-persistence#942]
Hi,
I'm really enjoying blazebit persistence but I'm struggling with the deserialization of views. 
Serialization works just fine but because I'm using Interfaces for my views GSON can't create an instance when converting JSON to object.

I thought of getting the implementation of the view interface during the runtime and trying to use this, but is there any better way to do this?

**Comment by jwgmeligmeyling** [comment]
I am not sure if you can pull this off with Gson as it seems to have issues with deserializing interfaces: https://github.com/google/gson/issues/411

However, our Jackson integration should be a good starting point to do this in Gson as well. Basically you should first read the ID property, obtain an EntityView reference instance from the EntityViewManager and then fill this instance using a deserializer that writes to that object: https://github.com/Blazebit/blaze-persistence/blob/master/integration/jackson/src/main/java/com/blazebit/persistence/integration/jackson/EntityViewReferenceDeserializer.java

**Comment by j0nm1** [comment]
Thanks for your quick response. I've never worked with Jackson before but if the support is better then I should be able to switch to Jackson instead of Gson. I just looked into the EntityViewReferenceDeserializer and is there any example on how to use it? Because after a quick google search most of the Deserializers have no-args constructors and I'm not quite sure from where I get the necessary parameters.

**Comment by jwgmeligmeyling** [comment]
See for example the test case in the same integration module: https://github.com/Blazebit/blaze-persistence/blob/master/integration/jackson/src/test/java/com/blazebit/persistence/integration/jackson/EntityViewAwareObjectMapperTest.java#L66

**Comment by j0nm1** [comment]
Thank you so much! It's working great.

**Comment by beikov** [comment]
Essentially, what we are doing for Jackson is just what you described. Getting the implementation class, creating an instance and then letting Jackson do it's thing.
One particular speciality is that instances must be created with the _reference constructor_ i.e. the one accepting the identifier. In Jackson we do this by looking for the identifier property in the JSON structure, getting that out and letting Jackson then deserialize the rest of the properties onto the created instance. Not sure if GSON supports something similar, but if you want to give such an integration a try, you would be on a good path.

We are planning to also create builder classes #913. The builder objects can be mutated via setters, which works with most serialization frameworks. Finally, you'd create the final object.
