### ISSUE TITLE
View Model Duplicates

### ISSUE THREAD

**Issue by j0nm1** [Blazebit/blaze-persistence#945]
Hi,

I'm struggling with fetching data from the database. When querying for a specific RFA view, I get a duplicate for each "history" entity. So with three entries in "history", I get the same RFA three times.
I found out that Hibernate has a ResultTransformer for this problem, but this isn't useable for blazebit when I'm correct.
Furthermore, I didn't find anything helpful in the issue section. Am I missing something?

I got the following two entities:
```
@Entity
@Table(name = "requests")
public class RFA {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected long id;

    @OneToMany(mappedBy = "rfa")
    private Set<StatusEntry> history = new HashSet<>();
}
```

```
@Entity
@Table(name = "status_history")
public class StatusEntry {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rfa_id")
    private RFA rfa;

}
```
Views:

```
@EntityView(RFA.class)
public interface RFAView {

    @IdMapping("id")
    Long getId();

    Set<StatusEntryView> getHistory();
}
```

```
@EntityView(StatusEntry.class)
public interface StatusEntryView {

    @IdMapping("id")
    Long getId();

}
```

**Comment by beikov** [comment]
How are you fetching the views? We have plenty of tests that do similar things, so this should work without a problem.

**Comment by j0nm1** [comment]
```
        EntityManager entityManager = emf.createEntityManager();
        CriteriaBuilder cb = cbf.create(entityManager, RFA.class);

        cb.where("id").eq(1);
        EntityViewSetting setting = EntityViewSetting.create(RFAView.class);
        List l = evm.applySetting(setting, cb).getResultList();

```

**Comment by beikov** [comment]
I used the archetype to generate a sample project that models the same, an inverse one-to-many, but here it works: https://github.com/beikov/bp-945

**Comment by beikov** [comment]
Would you mind creating a sample project that reproduces your issue? Maybe there are parts of your model that are special that you didn't share here?

**Comment by j0nm1** [comment]
Hi, you're right. I removed some of the properties of the RFA entity because the error occurred only in relation to adding more history entries. But after trying to create a sample for you I found the problem.
The RFA also has a property called people that serialized to a JSON string in the database by the converter.

```
    @Column(name = "people")
    @Convert(converter = PersonListConverter.class)
    private List<Person> people;
```

In the view I used: `Object getPeople();`

Because when using anything else, e.g. `List<Person> getPeople();` it would give me this error:
```
The resolved possible types [java.util.List] are not assignable to the given expression type 'java.util.Collection<de.test.interfaces.rfa.model.Person>' of the mapping expression declared by the attribute people[de.test.interfaces.rfa.model.RFAView.getPeople]!
	at com.blazebit.persistence.view.impl.EntityViewManagerImpl.<init>(EntityViewManagerImpl.java:179)
	at com.blazebit.persistence.view.impl.EntityViewConfigurationImpl.createEntityViewManager(EntityViewConfigurationImpl.java:160)

```

**Comment by beikov** [comment]
I see. Well this is a _special case_ that needs a `@MappingSingular` annotation. We probably should improve the error message though. Also see: https://persistence.blazebit.com/documentation/1.4/entity-view/manual/en_US/#singular-collection-type-mappings

**Comment by j0nm1** [comment]
Thank you so much! Now it's working. Is it possible to donate you some money for your help?

**Comment by beikov** [comment]
I'm glad it works for you and thanks for considering donating.

I've never accepted donations before, but I just created a PayPal MoneyPool for such donations: https://paypal.me/pools/c/8kws3g2pRO

Hope that works for you :)

**Comment by j0nm1** [comment]
After some testing, I found out that the problem is indeed gone but there is a new one. Normally I use `cb.setMaxResults(100);` to get exactly 100 entries. But when there would be duplicates in the ResultList I get 100 minus the number of duplicates.

Is there a way to fix that as well?

**Comment by beikov** [comment]
The setMaxResults function works on JDBC/row level, so if you join fetch collections, it will count every collection element as row as well. You can use the pagination API of Blaze-Persistence for paginating even when collections are involved: https://persistence.blazebit.com/documentation/1.4/core/manual/en_US/#pagination

An alternative would be to use a different fetch strategy for the collection which can be defined in the @Mapping annotation in the entity view

**Comment by j0nm1** [comment]
Not sure if I'm getting this right. I get the point but I'm not sure how to fix it.
As far as I know, the pagination with Blazebit only works when sorting by a unique id - this is not usable in my case. And `@MappingSingular` doesn't take a `fetch` parameter. So what should I do?

**Comment by beikov** [comment]
I'm not sure what your model looks like. Maybe you could post it here so I can understand what you are doing? `fetch` only makes sense when you try to fetch join an association and since this seems to be a basic attribute, fetch indeed makes no sense. Maybe you could make a PR on the example project I created or you provide me access to what you are trying to do?

**Comment by j0nm1** [comment]
```
@Entity
@Table(name = "requests")
public class RFA {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected long id;

    @Basic
    @Column(name = "people")
    @Convert(converter = PersonListConverter.class)
    private List<Person> people;

    @Column(name = "rfa_code")
    private String rfaCode;

}
```

```
@EntityView(RFA.class)
public interface RFAView {

    @IdMapping("id")
    Long getId();

    @MappingSingular
    List<Person> getPeople();

    String getRfaCode();
}
```


The problem occurs when I'm trying to receive some `RFAView` objects (sorted by rfaCode). The duplicates are gone but now I'm only receiving six entries when there would be four duplicates out of a limit of ten results.
You mentioned lazy loading but I don't think that this is possible in this case.

**Comment by beikov** [comment]
How can there be duplicates? Pagination works based on the identifier you define in the entity view, so there can't be duplicates. Maybe you can post some example data so I understand what you would expect to happen? Seems like there are 6 request rows in the table. Why would you expect 10 results then?

**Comment by Mobe91** [comment]
As I understand it, @j0nm1 is not using blaze-persistence pagination so far.
But since the above model should not produce a query that uses join fetching, it should not matter and setMaxResults should do the job.
@j0nm1
It sounds to me like you expect the result list to contain duplicates when it does not? But how could there be duplicates if your RFAView contains an IdMapping?

**Comment by j0nm1** [comment]
I think I found a solution. Using `@Basic` isn't correct in this case because it's a custom type. I changed it to be a ´@ElementCollection´. I will test it tomorrow and tell you if it works.

**Comment by beikov** [comment]
How can this be a custom type if you use a converter? If you could share a little example project then I could take a look, but I'm still not fully sure what your model looks like especially since now you were talking about a custom type being used 😄

**Comment by j0nm1** [comment]
Yeah, I'm working on providing a demo project to show the problem. But I need to remove a lot of things because they have nothing to do with the problem and/or I'm not allowed to share here.
`@ElementCollection` didn't change anything so I'm back at using `@Basic`.

**Comment by j0nm1** [comment]
So after a lot of struggling with the data, I finally got a small demo together that shows the issue. Not sure if I'm missing something, but I think there were two issues (the first with the `people` attribute and another one with the `history` attribute)

Demo: https://github.com/j0nm1/view-test

Thanks for your help!

**Comment by beikov** [comment]
Ok, so the problem is that you are using `setFirstResult` and `setMaxResults` for pagination which can't work as you are using a collection in your `RFAView`.
You would need to use something like the following instead

```
        CriteriaBuilder cb = cbf.create(em, RFA.class);
        int pageIndex = 1;
        int pageSize = 10;
        int firstResult = (pageIndex - 1) * pageSize;

        EntityViewSetting<RFAView, PaginatedCriteriaBuilder<RFAView>> setting = EntityViewSetting.create(RFAView.class, firstResult, pageSize);
        PagedList<RFAView> l = evm
                .applySetting(setting, cb)
                .getResultList();
```

The usage of `EntityViewSetting.create(Class<?> viewClass, int firstResult, int maxResults)` translates more or less to using the `PaginatedCriteriaBuilder` API, which you can see when applying that setting. It will return a `PaginatedCriteriaBuilder` then which you could use further for applying other clauses.
For more information about how the pagination API works, see the following section of the documenation: https://persistence.blazebit.com/documentation/1.4/core/manual/en_US/#pagination

**Comment by j0nm1** [comment]
Good idea but as I said before, I need to order the elements by different keys that aren't unique (like e.g. the `createDate` of the RFA. And I'm afraid that this doesn't work with this approach.

**Comment by beikov** [comment]
You can order by the creation date primarily and additionally by id. `orderByDesc("creationDate").orderByDesc("id")` or add attribute sorters for the entity view attributes.

**Comment by beikov** [comment]
So what you can do is either this

```
        CriteriaBuilder cb = cbf.create(em, RFA.class);
        int pageIndex = 1;
        int pageSize = 10;
        int firstResult = (pageIndex - 1) * pageSize;

        EntityViewSetting<RFAView, PaginatedCriteriaBuilder<RFAView>> setting = EntityViewSetting.create(RFAView.class, firstResult, pageSize);
        setting.addAttributeSorter("createDate", Sorters.descending());
        setting.addAttributeSorter("id", Sorters.descending());
        PagedList<RFAView> l = evm
                .applySetting(setting, cb)
                .getResultList();
```

or this


```
        CriteriaBuilder cb = cbf.create(em, RFA.class);
        int pageIndex = 1;
        int pageSize = 10;
        int firstResult = (pageIndex - 1) * pageSize;

        EntityViewSetting<RFAView, PaginatedCriteriaBuilder<RFAView>> setting = EntityViewSetting.create(RFAView.class, firstResult, pageSize);
        cb.orderByDesc("createDate");
        cb.orderByDesc("id");
        PagedList<RFAView> l = evm
                .applySetting(setting, cb)
                .getResultList();
```

**Comment by j0nm1** [comment]
Ok, now it's working fine. Thank you!
