### ISSUE TITLE
Introduce internal JPQL function for rendering of parameters for SELECT statements

### ISSUE THREAD

**Issue by beikov** [Blazebit/blaze-persistence#970]
The idea is to introduce a function e.g. `param(:param_0)` that can be used in the SELECT clause to render parameters. AFAIK Hibernate and some other JPA Providers don't support parameters in the SELECT clause which causes a few problems. The biggest problem might be the rendering of a enum literal. There is no "enum literal" in Hibernate, so we can't really use that in a non-comparison context. We could workaround that issue by using a special function to which we pass the value or maybe a predicate that we then deconstruct in the JPQLFunction to make this work.

I think this will fix https://github.com/Blazebit/blaze-persistence/issues/671 and als, I think we don't need a function. We could use the cast function for this which we would need anyway to be able to use the null value for a parameter.

**Comment by jwgmeligmeyling** [comment]
Note to self: with the presence of this feature we can change the rendering of literals in the Criteria impl.
